---@meta

---@class UABP_Barnacle_C : UEnemyAnimInstance
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AnimGraphNode_Root FAnimNode_Root
---@field AnimGraphNode_Slot FAnimNode_Slot
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_5 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_5 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_4 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_3 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
---@field AnimGraphNode_ApplyAdditive FAnimNode_ApplyAdditive
---@field AnimGraphNode_SequenceEvaluator FAnimNode_SequenceEvaluator
---@field AnimState Enum_BarnacleAnimState::Type
---@field BarnacleRootsClose float
UABP_Barnacle_C = {}

---@param AnimGraph FPoseLink
function UABP_Barnacle_C:AnimGraph(AnimGraph) end
function UABP_Barnacle_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Barnacle_AnimGraphNode_TransitionResult_F205B4CA4184183CA650859B3DE7EBB7() end
function UABP_Barnacle_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Barnacle_AnimGraphNode_TransitionResult_4AD977CE488B399BC3621C8A554AE260() end
function UABP_Barnacle_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Barnacle_AnimGraphNode_TransitionResult_F34E3EDE474D047574E19FB258562FF3() end
function UABP_Barnacle_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Barnacle_AnimGraphNode_TransitionResult_D944E5104228795AFBB46C858DD6ED5C() end
function UABP_Barnacle_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Barnacle_AnimGraphNode_TransitionResult_6A2D28694D0B766EDF5F1684C038B6EE() end
function UABP_Barnacle_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Barnacle_AnimGraphNode_TransitionResult_CCA6E5D641C956FF3DB9778AEB4BA6C4() end
function UABP_Barnacle_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Barnacle_AnimGraphNode_TransitionResult_14D53B114324F6B87247FDBB3377A849() end
function UABP_Barnacle_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Barnacle_AnimGraphNode_TransitionResult_D07B54DB4579579233349595D95DEA0F() end
function UABP_Barnacle_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Barnacle_AnimGraphNode_TransitionResult_8DD14A51497410F8968FE98518E39AEF() end
---@param Request FAnimationRequest
function UABP_Barnacle_C:OnUntrackedRequestStarted(Request) end
---@param DeltaTimeX float
function UABP_Barnacle_C:BlueprintUpdateAnimation(DeltaTimeX) end
---@param EntryPoint int32
function UABP_Barnacle_C:ExecuteUbergraph_ABP_Barnacle(EntryPoint) end


