---@meta

---@class UABP_Player_New_C : UPlayerAnimInstance
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AnimGraphNode_Root FAnimNode_Root
---@field AnimGraphNode_BlendListByBool_69 FAnimNode_BlendListByBool
---@field AnimGraphNode_RotationOffsetBlendSpace_5 FAnimNode_RotationOffsetBlendSpace
---@field AnimGraphNode_Slot_16 FAnimNode_Slot
---@field AnimGraphNode_LayeredBoneBlend_11 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_TransitionResult_153 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_152 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_151 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_150 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_149 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_148 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_147 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_146 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_145 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_144 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_143 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_142 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_141 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_140 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_139 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_138 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_137 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_136 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_135 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_134 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_133 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_132 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_131 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_130 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_129 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_123 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_66 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_122 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_65 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_121 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_64 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_120 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_63 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_119 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_118 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_68 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByEnum_21 FAnimNode_BlendListByEnum
---@field AnimGraphNode_BlendListByEnum_20 FAnimNode_BlendListByEnum
---@field AnimGraphNode_SequencePlayer_117 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_116 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_62 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_115 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_61 FAnimNode_StateResult
---@field AnimGraphNode_RotateRootBone_4 FAnimNode_RotateRootBone
---@field AnimGraphNode_SequencePlayer_114 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_60 FAnimNode_StateResult
---@field AnimGraphNode_RotationOffsetBlendSpace_4 FAnimNode_RotationOffsetBlendSpace
---@field AnimGraphNode_RotateRootBone_3 FAnimNode_RotateRootBone
---@field AnimGraphNode_BlendListByBool_67 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_113 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_66 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_112 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_65 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_111 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_110 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_64 FAnimNode_BlendListByBool
---@field AnimGraphNode_ModifyCurve_20 FAnimNode_ModifyCurve
---@field AnimGraphNode_ModifyCurve_19 FAnimNode_ModifyCurve
---@field AnimGraphNode_ModifyCurve_18 FAnimNode_ModifyCurve
---@field AnimGraphNode_ModifyCurve_17 FAnimNode_ModifyCurve
---@field AnimGraphNode_BlendListByEnum_19 FAnimNode_BlendListByEnum
---@field AnimGraphNode_SequencePlayer_109 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_108 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_107 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_106 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_59 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_13 FAnimNode_StateMachine
---@field AnimGraphNode_StateResult_58 FAnimNode_StateResult
---@field AnimGraphNode_TransitionResult_128 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_127 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_126 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_125 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_124 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_123 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_122 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_121 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_120 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_105 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_57 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_104 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_56 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_103 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_63 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_102 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_55 FAnimNode_StateResult
---@field AnimGraphNode_RotationOffsetBlendSpace_3 FAnimNode_RotationOffsetBlendSpace
---@field AnimGraphNode_RotateRootBone_2 FAnimNode_RotateRootBone
---@field AnimGraphNode_ModifyCurve_16 FAnimNode_ModifyCurve
---@field AnimGraphNode_ModifyCurve_15 FAnimNode_ModifyCurve
---@field AnimGraphNode_ModifyCurve_14 FAnimNode_ModifyCurve
---@field AnimGraphNode_ModifyCurve_13 FAnimNode_ModifyCurve
---@field AnimGraphNode_BlendListByEnum_18 FAnimNode_BlendListByEnum
---@field AnimGraphNode_BlendSpacePlayer_39 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_38 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_37 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_36 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_35 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByBool_62 FAnimNode_BlendListByBool
---@field AnimGraphNode_StateResult_54 FAnimNode_StateResult
---@field AnimGraphNode_RotationOffsetBlendSpace_2 FAnimNode_RotationOffsetBlendSpace
---@field AnimGraphNode_RotateRootBone_1 FAnimNode_RotateRootBone
---@field AnimGraphNode_ModifyCurve_12 FAnimNode_ModifyCurve
---@field AnimGraphNode_ModifyCurve_11 FAnimNode_ModifyCurve
---@field AnimGraphNode_ModifyCurve_10 FAnimNode_ModifyCurve
---@field AnimGraphNode_ModifyCurve_9 FAnimNode_ModifyCurve
---@field AnimGraphNode_BlendListByEnum_17 FAnimNode_BlendListByEnum
---@field AnimGraphNode_BlendSpacePlayer_34 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_33 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_32 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_31 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_30 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByBool_61 FAnimNode_BlendListByBool
---@field AnimGraphNode_StateResult_53 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_12 FAnimNode_StateMachine
---@field AnimGraphNode_StateResult_52 FAnimNode_StateResult
---@field AnimGraphNode_TransitionResult_119 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_118 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_117 FAnimNode_TransitionResult
---@field AnimGraphNode_BlendListByBool_60 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_101 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_100 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_59 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_58 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_99 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_98 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_57 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_97 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_96 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_56 FAnimNode_BlendListByBool
---@field AnimGraphNode_StateResult_51 FAnimNode_StateResult
---@field AnimGraphNode_StateResult_50 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_11 FAnimNode_StateMachine
---@field AnimGraphNode_ApplyMeshSpaceAdditive_1 FAnimNode_ApplyMeshSpaceAdditive
---@field AnimGraphNode_TransitionResult_116 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_115 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_114 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_113 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_112 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_111 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_110 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_109 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_108 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_107 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_106 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_105 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_104 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_103 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_102 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_101 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_100 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_99 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_98 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_97 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_96 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_95 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_94 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_93 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_92 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_91 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_90 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_89 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_88 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_87 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_86 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_85 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_84 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_83 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_82 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_81 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_80 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_79 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_78 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_77 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_76 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_75 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_74 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_73 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_72 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_71 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_70 FAnimNode_TransitionResult
---@field AnimGraphNode_BlendListByEnum_16 FAnimNode_BlendListByEnum
---@field AnimGraphNode_SequencePlayer_95 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_94 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_55 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_93 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_92 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_54 FAnimNode_BlendListByBool
---@field AnimGraphNode_StateResult_49 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_91 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_90 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_53 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByEnum_15 FAnimNode_BlendListByEnum
---@field AnimGraphNode_SequencePlayer_89 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_88 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_52 FAnimNode_BlendListByBool
---@field AnimGraphNode_StateResult_48 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_87 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_51 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_86 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_50 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_49 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_85 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_84 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_48 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_47 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_83 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_82 FAnimNode_SequencePlayer
---@field AnimGraphNode_TwoWayBlend_12 FAnimNode_TwoWayBlend
---@field AnimGraphNode_SequencePlayer_81 FAnimNode_SequencePlayer
---@field AnimGraphNode_TwoWayBlend_11 FAnimNode_TwoWayBlend
---@field AnimGraphNode_SequencePlayer_80 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendSpacePlayer_29 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByBool_46 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_45 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_28 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByEnum_14 FAnimNode_BlendListByEnum
---@field AnimGraphNode_SequencePlayer_79 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_44 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_43 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_78 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_77 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_47 FAnimNode_StateResult
---@field AnimGraphNode_TransitionResult_69 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_68 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_67 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_66 FAnimNode_TransitionResult
---@field AnimGraphNode_StateResult_46 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_76 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByEnum_13 FAnimNode_BlendListByEnum
---@field AnimGraphNode_SequencePlayer_75 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_45 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_74 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByEnum_12 FAnimNode_BlendListByEnum
---@field AnimGraphNode_SequencePlayer_73 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_44 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_10 FAnimNode_StateMachine
---@field AnimGraphNode_StateResult_43 FAnimNode_StateResult
---@field AnimGraphNode_TransitionResult_65 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_64 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_72 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByEnum_11 FAnimNode_BlendListByEnum
---@field AnimGraphNode_SequencePlayer_71 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_42 FAnimNode_StateResult
---@field AnimGraphNode_BlendListByEnum_10 FAnimNode_BlendListByEnum
---@field AnimGraphNode_SequencePlayer_70 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_69 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_41 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_68 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByInt_2 FAnimNode_BlendListByInt
---@field AnimGraphNode_BlendListByInt_1 FAnimNode_BlendListByInt
---@field AnimGraphNode_SequencePlayer_67 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_66 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_65 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByEnum_9 FAnimNode_BlendListByEnum
---@field AnimGraphNode_StateResult_40 FAnimNode_StateResult
---@field AnimGraphNode_BlendListByBool_42 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_41 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_27 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByBool_40 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_26 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_25 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByBool_39 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_24 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_SequencePlayer_64 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_63 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_38 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_37 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_62 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_61 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_60 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendSpacePlayer_23 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_22 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByBool_36 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_59 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_58 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_57 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_56 FAnimNode_SequencePlayer
---@field AnimGraphNode_ModifyCurve_8 FAnimNode_ModifyCurve
---@field AnimGraphNode_ModifyCurve_7 FAnimNode_ModifyCurve
---@field AnimGraphNode_ModifyCurve_6 FAnimNode_ModifyCurve
---@field AnimGraphNode_ModifyCurve_5 FAnimNode_ModifyCurve
---@field AnimGraphNode_BlendListByEnum_8 FAnimNode_BlendListByEnum
---@field AnimGraphNode_BlendListByEnum_7 FAnimNode_BlendListByEnum
---@field AnimGraphNode_BlendListByBool_35 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_34 FAnimNode_BlendListByBool
---@field AnimGraphNode_StateResult_39 FAnimNode_StateResult
---@field AnimGraphNode_BlendListByBool_33 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByEnum_6 FAnimNode_BlendListByEnum
---@field AnimGraphNode_SequencePlayer_55 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_32 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_31 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_54 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_53 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_30 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByEnum_5 FAnimNode_BlendListByEnum
---@field AnimGraphNode_SequencePlayer_52 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_51 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_50 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_49 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_38 FAnimNode_StateResult
---@field AnimGraphNode_ApplyAdditive_9 FAnimNode_ApplyAdditive
---@field AnimGraphNode_BlendSpacePlayer_21 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByBool_29 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_28 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_48 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_47 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_46 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_27 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_20 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_ApplyAdditive_8 FAnimNode_ApplyAdditive
---@field AnimGraphNode_TransitionResult_63 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_62 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_61 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_60 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_59 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_58 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_57 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_56 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_55 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_54 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_53 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_52 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_51 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_50 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_49 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_48 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_45 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_37 FAnimNode_StateResult
---@field AnimGraphNode_TransitionResult_47 FAnimNode_TransitionResult
---@field AnimGraphNode_BlendListByBool_26 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_44 FAnimNode_SequencePlayer
---@field AnimGraphNode_TwoWayBlend_10 FAnimNode_TwoWayBlend
---@field AnimGraphNode_SequencePlayer_43 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_42 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_36 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_41 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByEnum_4 FAnimNode_BlendListByEnum
---@field AnimGraphNode_SequencePlayer_40 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_35 FAnimNode_StateResult
---@field AnimGraphNode_BlendListByBool_25 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_19 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_18 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_34 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_17 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_33 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_39 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_24 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_38 FAnimNode_SequencePlayer
---@field AnimGraphNode_TwoWayBlend_9 FAnimNode_TwoWayBlend
---@field AnimGraphNode_BlendSpacePlayer_16 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_32 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_37 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByBool_23 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_15 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_31 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_9 FAnimNode_StateMachine
---@field AnimGraphNode_RotationOffsetBlendSpace_1 FAnimNode_RotationOffsetBlendSpace
---@field AnimGraphNode_ModifyCurve_4 FAnimNode_ModifyCurve
---@field AnimGraphNode_RotateRootBone FAnimNode_RotateRootBone
---@field AnimGraphNode_TransitionResult_46 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_45 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_44 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_43 FAnimNode_TransitionResult
---@field AnimGraphNode_BlendSpacePlayer_14 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_13 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_SequencePlayer_36 FAnimNode_SequencePlayer
---@field AnimGraphNode_TwoWayBlend_8 FAnimNode_TwoWayBlend
---@field AnimGraphNode_BlendListByBool_22 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_35 FAnimNode_SequencePlayer
---@field AnimGraphNode_TwoWayBlend_7 FAnimNode_TwoWayBlend
---@field AnimGraphNode_ModifyCurve_3 FAnimNode_ModifyCurve
---@field AnimGraphNode_StateResult_30 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_12 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_11 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_SequencePlayer_34 FAnimNode_SequencePlayer
---@field AnimGraphNode_TwoWayBlend_6 FAnimNode_TwoWayBlend
---@field AnimGraphNode_BlendListByBool_21 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_33 FAnimNode_SequencePlayer
---@field AnimGraphNode_TwoWayBlend_5 FAnimNode_TwoWayBlend
---@field AnimGraphNode_ModifyCurve_2 FAnimNode_ModifyCurve
---@field AnimGraphNode_StateResult_29 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_10 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_9 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_SequencePlayer_32 FAnimNode_SequencePlayer
---@field AnimGraphNode_TwoWayBlend_4 FAnimNode_TwoWayBlend
---@field AnimGraphNode_BlendListByBool_20 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_31 FAnimNode_SequencePlayer
---@field AnimGraphNode_TwoWayBlend_3 FAnimNode_TwoWayBlend
---@field AnimGraphNode_ModifyCurve_1 FAnimNode_ModifyCurve
---@field AnimGraphNode_StateResult_28 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_8 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_7 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_SequencePlayer_30 FAnimNode_SequencePlayer
---@field AnimGraphNode_TwoWayBlend_2 FAnimNode_TwoWayBlend
---@field AnimGraphNode_BlendListByBool_19 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_29 FAnimNode_SequencePlayer
---@field AnimGraphNode_TwoWayBlend_1 FAnimNode_TwoWayBlend
---@field AnimGraphNode_ModifyCurve FAnimNode_ModifyCurve
---@field AnimGraphNode_StateResult_27 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_8 FAnimNode_StateMachine
---@field AnimGraphNode_BlendListByBool_18 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer_6 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_5 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByBool_17 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendListByBool_16 FAnimNode_BlendListByBool
---@field AnimGraphNode_StateResult_26 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_7 FAnimNode_StateMachine
---@field AnimGraphNode_StateResult_25 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_6 FAnimNode_StateMachine
---@field AnimGraphNode_SaveCachedPose_22 FAnimNode_SaveCachedPose
---@field AnimGraphNode_Slot_15 FAnimNode_Slot
---@field AnimGraphNode_LayeredBoneBlend_10 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_SaveCachedPose_21 FAnimNode_SaveCachedPose
---@field AnimGraphNode_ComponentToLocalSpace_3 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_Fabrik FAnimNode_Fabrik
---@field AnimGraphNode_SaveCachedPose_20 FAnimNode_SaveCachedPose
---@field AnimGraphNode_Slot_14 FAnimNode_Slot
---@field AnimGraphNode_SaveCachedPose_19 FAnimNode_SaveCachedPose
---@field AnimGraphNode_TransitionResult_42 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_41 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_40 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_39 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_38 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_37 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_36 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_35 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_34 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_33 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_32 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_31 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_30 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_29 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_28 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_27 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_26 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_25 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_24 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_28 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_24 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_27 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_23 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_26 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_22 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_25 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_21 FAnimNode_StateResult
---@field AnimGraphNode_BlendListByBool_15 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_24 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_23 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_20 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_22 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_19 FAnimNode_StateResult
---@field AnimGraphNode_StateResult_18 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_5 FAnimNode_StateMachine
---@field AnimGraphNode_LayeredBoneBlend_9 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_SaveCachedPose_18 FAnimNode_SaveCachedPose
---@field AnimGraphNode_BlendSpacePlayer_4 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_3 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendSpacePlayer_2 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_BlendListByInt FAnimNode_BlendListByInt
---@field AnimGraphNode_BlendSpacePlayer_1 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult_17 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_4 FAnimNode_StateMachine
---@field AnimGraphNode_ApplyAdditive_7 FAnimNode_ApplyAdditive
---@field AnimGraphNode_ApplyAdditive_6 FAnimNode_ApplyAdditive
---@field AnimGraphNode_SaveCachedPose_17 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_51 FAnimNode_UseCachedPose
---@field AnimGraphNode_TransitionResult_23 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_22 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_21 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_20 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_21 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_16 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_20 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_15 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_19 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_14 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_18 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_13 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_3 FAnimNode_StateMachine
---@field AnimGraphNode_UseCachedPose_50 FAnimNode_UseCachedPose
---@field AnimGraphNode_LocalToComponentSpace_3 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ModifyBone_9 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_8 FAnimNode_ModifyBone
---@field AnimGraphNode_ComponentToLocalSpace_2 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_TwoBoneIK_1 FAnimNode_TwoBoneIK
---@field AnimGraphNode_TwoBoneIK FAnimNode_TwoBoneIK
---@field AnimGraphNode_ModifyBone_7 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_6 FAnimNode_ModifyBone
---@field AnimGraphNode_SaveCachedPose_16 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_49 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_14 FAnimNode_BlendListByBool
---@field AnimGraphNode_ComponentToLocalSpace_1 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_LocalToComponentSpace_2 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ModifyBone_5 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_4 FAnimNode_ModifyBone
---@field AnimGraphNode_LocalToComponentSpace_1 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_BlendListByBool_13 FAnimNode_BlendListByBool
---@field AnimGraphNode_BlendSpacePlayer FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_ApplyAdditive_5 FAnimNode_ApplyAdditive
---@field AnimGraphNode_BlendListByBool_12 FAnimNode_BlendListByBool
---@field AnimGraphNode_SaveCachedPose_15 FAnimNode_SaveCachedPose
---@field AnimGraphNode_TransitionResult_19 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_18 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_17 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_16 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_17 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_12 FAnimNode_StateResult
---@field AnimGraphNode_BlendListByBool_11 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_16 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_15 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_11 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_14 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_10 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_2 FAnimNode_StateMachine
---@field AnimGraphNode_ApplyMeshSpaceAdditive FAnimNode_ApplyMeshSpaceAdditive
---@field AnimGraphNode_SaveCachedPose_14 FAnimNode_SaveCachedPose
---@field AnimGraphNode_Inertialization FAnimNode_Inertialization
---@field AnimGraphNode_Slot_13 FAnimNode_Slot
---@field AnimGraphNode_LayeredBoneBlend_8 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_SaveCachedPose_13 FAnimNode_SaveCachedPose
---@field AnimGraphNode_Slot_12 FAnimNode_Slot
---@field AnimGraphNode_SaveCachedPose_12 FAnimNode_SaveCachedPose
---@field AnimGraphNode_TransitionResult_15 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_14 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_13 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_12 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_11 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_10 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_13 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_9 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_12 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_8 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_11 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_7 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_10 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_6 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_1 FAnimNode_StateMachine
---@field AnimGraphNode_BlendListByBool_10 FAnimNode_BlendListByBool
---@field AnimGraphNode_SequencePlayer_9 FAnimNode_SequencePlayer
---@field AnimGraphNode_ApplyAdditive_4 FAnimNode_ApplyAdditive
---@field AnimGraphNode_Slot_11 FAnimNode_Slot
---@field AnimGraphNode_ApplyAdditive_3 FAnimNode_ApplyAdditive
---@field AnimGraphNode_BlendListByEnum_3 FAnimNode_BlendListByEnum
---@field AnimGraphNode_BlendListByBool_9 FAnimNode_BlendListByBool
---@field AnimGraphNode_SaveCachedPose_11 FAnimNode_SaveCachedPose
---@field AnimGraphNode_LayeredBoneBlend_7 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_SequencePlayer_8 FAnimNode_SequencePlayer
---@field AnimGraphNode_UseCachedPose_48 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_47 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_46 FAnimNode_UseCachedPose
---@field AnimGraphNode_SequencePlayer_7 FAnimNode_SequencePlayer
---@field AnimGraphNode_BlendListByEnum_2 FAnimNode_BlendListByEnum
---@field AnimGraphNode_LayeredBoneBlend_6 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_BlendListByBool_8 FAnimNode_BlendListByBool
---@field AnimGraphNode_SaveCachedPose_10 FAnimNode_SaveCachedPose
---@field AnimGraphNode_LayeredBoneBlend_5 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_Slot_10 FAnimNode_Slot
---@field AnimGraphNode_Slot_9 FAnimNode_Slot
---@field AnimGraphNode_BlendListByEnum_1 FAnimNode_BlendListByEnum
---@field AnimGraphNode_BlendListByBool_7 FAnimNode_BlendListByBool
---@field AnimGraphNode_SaveCachedPose_9 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_45 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_44 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_43 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_42 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot_8 FAnimNode_Slot
---@field AnimGraphNode_LayeredBoneBlend_4 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_BlendListByBool_6 FAnimNode_BlendListByBool
---@field AnimGraphNode_SaveCachedPose_8 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_41 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_40 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_39 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_38 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_37 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_36 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_35 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot_7 FAnimNode_Slot
---@field AnimGraphNode_UseCachedPose_34 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot_6 FAnimNode_Slot
---@field AnimGraphNode_BlendListByBool_5 FAnimNode_BlendListByBool
---@field AnimGraphNode_SaveCachedPose_7 FAnimNode_SaveCachedPose
---@field AnimGraphNode_LayeredBoneBlend_3 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_Slot_5 FAnimNode_Slot
---@field AnimGraphNode_SaveCachedPose_6 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_33 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_32 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_31 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_30 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_29 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_28 FAnimNode_UseCachedPose
---@field AnimGraphNode_RotationOffsetBlendSpace FAnimNode_RotationOffsetBlendSpace
---@field AnimGraphNode_BlendListByBool_4 FAnimNode_BlendListByBool
---@field AnimGraphNode_SaveCachedPose_5 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_27 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_26 FAnimNode_UseCachedPose
---@field AnimGraphNode_SequencePlayer_6 FAnimNode_SequencePlayer
---@field AnimGraphNode_ApplyAdditive_2 FAnimNode_ApplyAdditive
---@field AnimGraphNode_UseCachedPose_25 FAnimNode_UseCachedPose
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_5 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_5 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_4 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_3 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
---@field AnimGraphNode_ApplyAdditive_1 FAnimNode_ApplyAdditive
---@field AnimGraphNode_SaveCachedPose_4 FAnimNode_SaveCachedPose
---@field __CustomProperty_EyeRotationPct_C5D5195E4F4ABEBC21C557AFC87A2FCE float
---@field __CustomProperty_TorsoRotationPct_C5D5195E4F4ABEBC21C557AFC87A2FCE float
---@field __CustomProperty_LookAtRot_C5D5195E4F4ABEBC21C557AFC87A2FCE FRotator
---@field __CustomProperty_LookAtEnabled_C5D5195E4F4ABEBC21C557AFC87A2FCE boolean
---@field AnimGraphNode_ControlRig FAnimNode_ControlRig
---@field AnimGraphNode_SaveCachedPose_3 FAnimNode_SaveCachedPose
---@field AnimGraphNode_Slot_4 FAnimNode_Slot
---@field AnimGraphNode_UseCachedPose_24 FAnimNode_UseCachedPose
---@field AnimGraphNode_ApplyAdditive FAnimNode_ApplyAdditive
---@field AnimGraphNode_SaveCachedPose_2 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_23 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_22 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_21 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_20 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_19 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_18 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_17 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_16 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_15 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_1 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_14 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_13 FAnimNode_UseCachedPose
---@field AnimGraphNode_TwoWayBlend FAnimNode_TwoWayBlend
---@field AnimGraphNode_UseCachedPose_12 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_3 FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose_11 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_10 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_2 FAnimNode_BlendListByBool
---@field AnimGraphNode_UseCachedPose_9 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot_3 FAnimNode_Slot
---@field AnimGraphNode_LayeredBoneBlend_2 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose_8 FAnimNode_UseCachedPose
---@field AnimGraphNode_ModifyBone_3 FAnimNode_ModifyBone
---@field AnimGraphNode_LocalToComponentSpace FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ComponentToLocalSpace FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_UseCachedPose_7 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot_2 FAnimNode_Slot
---@field AnimGraphNode_UseCachedPose_6 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot_1 FAnimNode_Slot
---@field AnimGraphNode_LayeredBoneBlend_1 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose_5 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool_1 FAnimNode_BlendListByBool
---@field AnimGraphNode_SaveCachedPose FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_4 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_3 FAnimNode_UseCachedPose
---@field AnimGraphNode_ModifyBone_2 FAnimNode_ModifyBone
---@field AnimGraphNode_ModifyBone_1 FAnimNode_ModifyBone
---@field AnimGraphNode_LayeredBoneBlend FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose_2 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_1 FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByBool FAnimNode_BlendListByBool
---@field AnimGraphNode_Slot FAnimNode_Slot
---@field AnimGraphNode_UseCachedPose FAnimNode_UseCachedPose
---@field AnimGraphNode_BlendListByEnum FAnimNode_BlendListByEnum
---@field AnimGraphNode_ModifyBone FAnimNode_ModifyBone
---@field WalkSpeed float
---@field IsAiming boolean
---@field IsDashing boolean
---@field IsJumpStarted boolean
---@field IsGrounded boolean
---@field AimingDeltaHorizontal float
---@field AimingDeltaVertical float
---@field HitDirection float
---@field ReloadTime float
---@field IsDamaged boolean
---@field IsReloading boolean
---@field IsShooting boolean
---@field CachedPlayer APlayerCharacter
---@field LookAtTarget FVector
---@field ChargePistolCharging float
---@field IsVaulting boolean
---@field IsDoubleJumping boolean
---@field Velocity FVector
---@field WeaponMoveSet ENUM_WeaponChooser::Type
---@field GunType EGunType
---@field IsSprinting boolean
---@field IsDashInterrupted boolean
---@field IsIdleTimerReached boolean
---@field IdleTimer float
---@field IsHookShotting boolean
---@field StartIdleAction boolean
---@field IdleActionChooser int32
---@field IsAccelerating boolean
---@field TeleportDepart boolean
---@field TeleportArrival boolean
---@field ReviveDir ENUM_Revive::Type
---@field IdleActionCounter int32
---@field IsPassiveIdle boolean
---@field AnimWalkSpeed float
---@field WalkSpeedForward float
---@field WalkSpeedRight float
---@field rightFootDown boolean
---@field RightFootDownAtStop boolean
---@field CardinalDir CardinalDir::Type
---@field CardinalAngleFwd float
---@field CardinalAngleBackward float
---@field CardinalAngleLeft float
---@field CardinalAngleRight float
---@field DirectionOffset float
---@field IsAimingAtStop boolean
---@field CardinalBlendTimeJump float
---@field AimStartBlendTime float
---@field AimStopBlendTime float
---@field UseCardinalDirection boolean
---@field JumpLandToRun boolean
---@field LeanAngle float
---@field IsHurt boolean
---@field DebugTextSpacer FString
---@field IsLanding boolean
---@field ActiveImmobilizingHazardMontage UAnimMontage
---@field WalkSpeedForwardHistory FDebugFloatHistory
---@field AccelerationSizeHistory FDebugFloatHistory
---@field HardTurn boolean
---@field WeaponIKAlpha float
---@field HasPhysicsRanOnce boolean
---@field StartRobotIdle boolean
---@field RobotIdleChooser int32
---@field IsRobotIdleTimeReached boolean
---@field RobotFidgetCount int32
---@field RobotMaxFidgetCount int32
---@field RobotPos int32
---@field TargetAimingDeltaHorizontal float
---@field TargetAimingDeltaVertical float
---@field RobotAlpha float
---@field IsAlive boolean
---@field InHeavySandstorm boolean
---@field MatLightAlpha float
---@field WarningLightOn boolean
---@field AimLightOn boolean
---@field isCollecting boolean
---@field collectingLightOn boolean
---@field ObCollectorClr FVector
---@field Healing boolean
---@field StatusLightAlpha float
---@field StatusLightTarget float
---@field EnableFootIK boolean
---@field RightFootBoneName FName
---@field LeftFootBoneName FName
---@field ZOffsetInterpSpeed_SpeedRange FVector2D
---@field ZOffsetInterpSpeed_ValueRange FVector2D
---@field TraceLengthAboveFoot float
---@field TraceLengthBelowFoot float
---@field FootIK_Alpha float
---@field LeftFootTransform FTransform
---@field RightFootTransform FTransform
---@field FwdLeanAngle float
---@field FwdSpeedBeforeStop float
---@field RightSpeedBeforeStop float
---@field LeanGrounded FVector2D
---@field IsRunning boolean
---@field IsScanning boolean
---@field StartHardTurn boolean
---@field TWEAKABLE_PlayerTestsA float
---@field WantsToRun boolean
---@field IsMoving boolean
---@field MinSpeedForStopAnimation float
---@field HardTurnIsCW boolean
---@field InputAndVelocityDirDiff float
---@field PendingHardTurn boolean
---@field HardTurn_SpeedReq float
---@field HardTurn_DirDiffReq float
---@field IsMoving_SpeedReq float
---@field IsLeansAllowed boolean
---@field HardTurn_StartAngleDif float
---@field RobotIdleTimer float
---@field ExertionLevel float
---@field AimAlpha float
---@field SprintStarted boolean
---@field FinalWarningLight boolean
---@field MovementInputWorldSpace FVector
---@field WantsToMove boolean
---@field GroundMovementType EGroundMovementType
---@field AnimWalkSpeedSandStorm float
---@field UseDiscreetMovement boolean
---@field GroundMovementTypeBeforeStop EGroundMovementType
---@field InCinematic boolean
---@field GunStockType EGunStockType
---@field LandingStrengthAlpha float
---@field PendingLanding boolean
---@field NewCombatLocEnabled boolean
---@field InMelee boolean
---@field FirstPersonTag FGameplayTag
---@field MaxRunSpeed float
---@field SmoothedRootYawOffset float
---@field RootYawOffsetInterpSpeed float
---@field CardinalForwardAreaAngle float
---@field CardinalBackwardAreaAngle float
---@field VelocityHeadingOffset float
---@field DashDirection CardinalDir::Type
---@field DashAngleForward float
---@field DashAngleRight float
---@field DashAngleLeft float
---@field DashAngleBackward float
---@field DashDirectionBlendTime float
---@field InJump boolean
---@field TWEAKABLE_PlayerTestsB float
---@field TWEAKABLE_PlayerTestsC float
---@field InInteract boolean
---@field FireRate float
---@field AnimSetInUse UBPDA_PlayerAnimSet_C
---@field AnimSet_Pistol TSoftObjectPtr<UBPDA_PlayerAnimSet_C>
---@field AnimSet_Rifle TSoftObjectPtr<UBPDA_PlayerAnimSet_C>
---@field AdditiveLeanAlpha float
---@field FullBodyTransitionSlot FName
---@field FullBodyTransitionAlpha float
---@field isShopping boolean
---@field ShoppingIndex int32
---@field RunDuration float
---@field ScanFinished boolean
---@field ['180TurnsEnabled'] boolean
---@field Start180Turn boolean
---@field ['180TurnThreshold'] float
---@field TWEAKABLE_Bool_A boolean
---@field LastRootYawRot float
---@field In180Turn boolean
---@field ['180TurnIsCW'] boolean
---@field YawRotationMontage UAnimMontage
---@field StopMoveInputHandle FTouristGameplayEffectHandle
---@field speedBeforeLand float
---@field Acceleration FVector
---@field GroundedLeanInterpSpeed float
---@field InReload boolean
---@field IsAnyMontageActive boolean
---@field ['180TurnPending'] boolean
---@field ['180TurnTimer'] float
---@field InFirstPerson boolean
---@field TurnOnSpotOn boolean
---@field TurnOnSpotCW boolean
---@field ExertionIncrease_Sprint float
---@field ExertionIncrease_Run float
---@field ExertionMax_Sprint float
---@field MaxRunDuration float
---@field ExertionMax_Run float
---@field ExertionDecrease_Sprint float
---@field ExertionDecrease_Run float
---@field MeshComponentInitialOffset FVector
---@field AimState EAimState
---@field CardinalTwistReductionForwardBack float
---@field CardinalTwistReductionLeftRight float
---@field CardinalRifleRotOffset float
---@field CardinalRotYaw float
---@field DownedState EDownedState
---@field AimOffsetDelay boolean
---@field PickUpAnimEnabled boolean
---@field PickUpAnimStopMovement boolean
---@field ScanningRotOffset FRotator
---@field PendingCardinalUpdate boolean
---@field IsInjured boolean
---@field TalkPicker int32
---@field isTalking boolean
---@field WalkDuration float
---@field WantsToRunAtStop boolean
---@field ['DEBUG FOOT IK'] boolean
---@field LookAtControlRigAlpha float
---@field InputAndFacingDirDiff float
---@field InjuredWalkDuration float
---@field InjuredFallDelay float
---@field InjuredHasFallen boolean
---@field LookAtEnabled boolean
---@field LookAtRotOffset FRotator
---@field HitReactionAlpha float
---@field HitReactionAlphaTarget float
---@field HitReactionAlphaInterpSpeed float
---@field KnockdownWaitingForLanding boolean
---@field KnockdownSafetyTimer float
---@field IsMovementAllowed boolean
---@field FloorDistance float
---@field IsPushedBack boolean
---@field KnockdownCooldown float
---@field Exit180 boolean
---@field AimIntoDash boolean
---@field DfltGrpMontagePlaying boolean
---@field InSlowdown boolean
---@field FloorNormal FVector
---@field FloorRot FRotator
---@field FloorRotTarget FRotator
---@field AlignToFloorAlpha float
---@field AlignToFloorInterpSpeed float
---@field IsSprintingAtStop boolean
---@field MoveFromMelee boolean
---@field OutOfHookshot boolean
---@field FootIK_OldStyle boolean
---@field MinLimitsIdle FVector
---@field MaxLimitsIdle FVector
---@field PelvisOffset float
---@field LeftFootOffsetTargets_Relative FVector
---@field RightFootOffsetTargets_Relative FVector
---@field RightFootOffsets FVector
---@field LeftFootOffsets FVector
---@field ZOffsetInterpSpeedUp float
---@field SlopeFwdAngle float
---@field SlopeRightAngle float
---@field HookShotEndLocation FVector
---@field HookShotPitch float
---@field HookShotPitchTarget float
---@field HookShotPhase float
---@field ZOffsetInterpSpeedDown float
---@field FootIK_Alpha_Left float
---@field FootIK_Alpha_Right float
---@field FootIK_HitLocation_Left FVector
---@field FootIK_HitLocation_Right FVector
---@field FootLock_Left float
---@field FootLock_Right float
---@field IsLeftFootInFront boolean
---@field IsRightFootInFront boolean
---@field IKPelvisOffset_Running UCurveFloat
---@field IKPelvisOffset_Walking UCurveFloat
---@field VisualsCorrectionZ float
---@field VisualsCorrectionZ_Target float
---@field VisualsCorrectionZ_InterpSpeed float
---@field FloorImpactPoint FVector
---@field VisualsCorrectionZ_Range FVector2D
---@field FootIK_UseSweep boolean
---@field TWEAKABLE_Bool_B boolean
---@field FootIK_SweepRadius float
---@field VisualsCorrectZ_Hit FHitResult
---@field AnimSet_Pistol_HardRef UBPDA_PlayerAnimSet_C
---@field AnimSet_Rifle_HardRef UBPDA_PlayerAnimSet_C
---@field FootIKTraces_WalkableCheck boolean
---@field FootIK_DebugDisable boolean
---@field LandingInMelee boolean
---@field FootIK_UseCpp boolean
---@field InjuredHeavyTag FGameplayTag
---@field InjuredMediumTag FGameplayTag
---@field DisableLipSync boolean
---@field GravityScaleMultiplier float
---@field RobotDeltaHorizontal float
---@field RobotDeltaVertical float
---@field RobotLookAtTargetLocation FVector
---@field RobotHasLookAtTarget boolean
---@field HardTurnsPlayRate float
---@field HardTurnsStartPosition float
---@field CardinalAngles FVector4
---@field UseCppOptimizations boolean
---@field RifleOffsetYaw float
---@field SmoothedRootYawOffsetCpp float
---@field DashCardinalAngles FVector4
---@field HardTurnBlockTimer float
---@field UseCardinalBeforeLand boolean
---@field KnockDownDir ENUM_KnockbackType::Type
UABP_Player_New_C = {}

---@param AnimGraph FPoseLink
function UABP_Player_New_C:AnimGraph(AnimGraph) end
---@param ForceOrigin FVector
---@param KnockdownImpulse float
---@param KnockdownAngle float
function UABP_Player_New_C:KnockDownWithForce(ForceOrigin, KnockdownImpulse, KnockdownAngle) end
---@param LocalHitDirection FVector
---@param KnockdownImpulse float
---@param KnockdownAngle float
---@param KnockDownDirection ENUM_KnockbackType::Type
function UABP_Player_New_C:KnockDownWithImpulse(LocalHitDirection, KnockdownImpulse, KnockdownAngle, KnockDownDirection) end
---@param DeltaTime float
function UABP_Player_New_C:CalculateLeanValuesFast(DeltaTime) end
---@param NewState boolean
function UABP_Player_New_C:MeleeStateChanged(NewState) end
---@param DeltaTime float
function UABP_Player_New_C:UpdateRobot(DeltaTime) end
---@param NewState boolean
function UABP_Player_New_C:VaultStateChanged(NewState) end
---@param FootBoneName FName
---@param CapsuleBottomLoc FVector
---@param OutFootRelative FVector
---@param OutHitLocation FVector
---@param OutInFront boolean
function UABP_Player_New_C:DoFootIKTrace(FootBoneName, CapsuleBottomLoc, OutFootRelative, OutHitLocation, OutInFront) end
---@param NewEnabled boolean
UABP_Player_New_C['Set Move Input Enabled'] = function(NewEnabled) end
function UABP_Player_New_C:EndKnockdown() end
---@param DeltaTime float
function UABP_Player_New_C:UpdateLookAt(DeltaTime) end
---@param DeltaTime float
function UABP_Player_New_C:UpdateCardinalSystem(DeltaTime) end
---@param WorldVector FVector
---@param ForwardRotation FRotator
---@param ForwardAreaAngle float
---@param BackwardAreaAngle float
---@param YawOffset float
---@param CardinalDir CardinalDir::Type
function UABP_Player_New_C:WorldVectorToCardinalDir(WorldVector, ForwardRotation, ForwardAreaAngle, BackwardAreaAngle, YawOffset, CardinalDir) end
---@param OptimalSpeed float
---@param MaxPlayrateUp float
---@param MaxPlayrateDown float
---@param CappedPlayrate float
function UABP_Player_New_C:GetCappedPlayrate(OptimalSpeed, MaxPlayrateUp, MaxPlayrateDown, CappedPlayrate) end
---@param DeltaTime float
function UABP_Player_New_C:Exertion(DeltaTime) end
function UABP_Player_New_C:SpeedBeforeStopFunction() end
function UABP_Player_New_C:RagdollIK() end
---@param DeltaTime float
function UABP_Player_New_C:FootIK(DeltaTime) end
---@param DeltaTime float
---@param StartIdleActionTrue boolean
---@param StartIdleActionFalse boolean
function UABP_Player_New_C:RobotActionTimer(DeltaTime, StartIdleActionTrue, StartIdleActionFalse) end
function UABP_Player_New_C:DrawDebugInfo() end
---@param SyncGroup FName
---@param MarkerName FName
function UABP_Player_New_C:DebugSyncMarkers(SyncGroup, MarkerName) end
---@param HitReactionData FHitReactionEvent
function UABP_Player_New_C:HandleHitReaction(HitReactionData) end
function UABP_Player_New_C:CollapseFunction() end
function UABP_Player_New_C:ReviveFunction() end
function UABP_Player_New_C:RecoilFunction() end
---@param DeltaTime float
---@param StartIdleActionTrue boolean
---@param StartIdleActionFalse boolean
function UABP_Player_New_C:IdleActionTimer(DeltaTime, StartIdleActionTrue, StartIdleActionFalse) end
function UABP_Player_New_C:ReadPlayerState() end
---@param Loaded UObject
function UABP_Player_New_C:OnLoaded_AD55DA71431ABF2584337AB82C4EF2C4(Loaded) end
---@param Loaded UObject
function UABP_Player_New_C:OnLoaded_81E710DF4917FD9ADF9FB1A1D1B5C4C6(Loaded) end
---@param Loaded UObject
function UABP_Player_New_C:OnLoaded_DBD7837F47D0867A0A9B74BBEF6373B9(Loaded) end
---@param Loaded UObject
function UABP_Player_New_C:OnLoaded_966CFA134CFFDE2BA50D5AB2FCE46154(Loaded) end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_403B8C78437EA5DE230B6ABF59752641() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_CE072F3947F1C99EE47E3A887D063EF2() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_A704C2A94B80500923D916BF9428A40C() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_3D6D3C6D492292B54BCA809E6AE3A14B() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_C0E4FB19459A53A5069A4EB293D79F97() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_1B4A9C924EF45BF62B60B3AE5A0C9442() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_6D1574AB489FB6F41428D58BF4BAFD40() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_992D657F44C2D4144D4AA689C9ECF5F1() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_AA0FEA9C4D5DC4700BEE4F95DA5C4A59() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_2D50189D428F42DA8171109F71BA60F7() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_345BC9AF4B18224E60CE769410821247() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_DE69FC894FACBC29DEE6DB9FA9B8577A() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_9F9C63D541259FEE7AF1B48A28BD6414() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_7C7582014C82CB660259A99C680E7FAF() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_FFD4F6EC425A04B6FA422BBF299E38F9() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TwoWayBlend_7241577B4CBF26CDD0D71BBBEA3637F7() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TwoWayBlend_B764F24642F0F8B2BDD30889D060659E() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_D23188A74666746AB1614EAECE5956E3() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_0181C74D47E7AC4D941DCEBF8298E7DA() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_9846F280494487019EF36398F6191291() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_9DDC0B9344E70DD635F2C188326B7C5A() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_25EF6044493D0CEE1FA362AA139E814F() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_AAA30CDB4AAA5A88395D95B768B060DF() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_D82FA1AF446D6A0A3AE87CBF3A9DA122() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_6522761A47F1663EA6C1E79FB33DE7C2() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_DDB22EA34D3913521C7505A62D3147F0() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_3CE9570341F5476522D7B5BD315C086F() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_8BACC3D545E21D7DBBBEBA8CE4A49D74() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_7309EE8645ABF528EFC56B84B668E804() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_96A14DD94D1221EF0E9240B9726E2704() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_D569CFB7478C2C94ED11F89D41E0C5F1() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_002E42924DCA78D2C3487AACB20D2E78() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_F3AF450B4B4D2ACD26C08A93D6FBED77() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_D2ADBCF44C55D89BFB183EBDB5DE4DF0() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_EF27858547242915A956C0ABE26597E1() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendListByBool_616F884E49292F9B1F8EC89B355FC198() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_F04F0AE249A9479EEC58F297938FA924() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendListByBool_DC9092E441842AA0CD2F8EBD4635256F() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_DAB9732B4227780EBD252EAEBA7E1C7B() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_661B2A9E468F11BA37447E8A98B838B9() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_ApplyAdditive_3DB0370F4FC1EF989D110BBBB4526DAA() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendListByBool_38D5F551413EA2C10D3F1AA58FD1BBE0() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendListByBool_4B36EA2A4E7F11C04BF060B71D365E9D() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_459910B440EB542E571F14A60561C724() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_04B799D548E6F44CBC06FF8B9D4D44AA() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_3DBA6C604A07906D05D76580E13443FE() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_AF40237F4323EC81C4AD7FAEE5870992() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_45CA7E9A4FE87FC957E877B80A819B29() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_EDD9578F42AF5897C80D27B02F4B4CD8() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_B6FA865F4EC07DA78CC281869B5A317D() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_180A22824111B57090E2F4A028AB7DCA() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_85E0EA974B39968B5555418739C0C6D0() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_250657B14956A3E3D231989B70B1E486() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_229A25EA417B0209CA46EC97AD622A6E() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_D1220B0C4E2AFDAE6F7B5590038CBDA4() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_6A4B51EE446A661C40C9AC915529B0A1() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendListByBool_1112051D4F1A2B6F57E1FDAF324FCAF9() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_DF47B1F443876CEDDE0109828DAD87E8() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TwoWayBlend_42ACBB2148715538EFAD3CBE7F112183() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_2D07EC304868EEAA2B6DACA4E7F042DB() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_3BDC81254FD3903D9CC372A9BD651CE7() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_BDBE043E486955843A09E69B2C14D73D() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_54C3D9E6451E8700F5BD889876A04C80() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_E03C4B224B39B2701402DB823B02E1EB() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_3A8974A9451D769D401031B7BE44B7DE() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_376C6448420E05D689B9CEB424666EBF() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TwoWayBlend_2D351CDE406992E84D1185941D5D701B() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_2A58F0A149D7AE250FEBD68D2B739E7A() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_27294AB04165D794D5CE4DA62A4FA067() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_F43A6A574817A54A34CEAAA9211D82EA() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_3ABD579942F4E67ED5E0C9BA02AE1B75() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_RotationOffsetBlendSpace_AB5D56374C08124B02CF5997F1B499DE() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_8D7644AD41E0559CCEA4369C4144FAEF() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_D006922C43F1BD9189D0FCACF1719F50() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_899777354C7F753FD89EF08CA729A8AF() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_11E62136461004E389F0B9A66604B3D7() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_B9EE2B5A49BB0E66700C0EA1B9531C6B() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_ADD32EC3457D6C6A0EFCAFBC84D6F9AD() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_5D8120E844D56A2B73A0D6BA7ECADFDD() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TwoWayBlend_9EDD2481423E1CA66778AF963E33094C() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_5381C0954B78642243F2FFB72CBF83B4() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TwoWayBlend_E48210314F70746DEEC821A706C65516() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_B3ACDF934ABA1E6AD54C85B935813E9E() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_1DCF28264B4DDAFAEB685F85954AD1A2() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_8E3FB13840F9459DC47C669D1621B6FD() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TwoWayBlend_5EABAB1245533AAFD1F48F8BDA741E87() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_6FB418144BD9C3E9E4FEE7A74E3C93DE() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TwoWayBlend_D1A8E2264C6493045900BBAE8E81F305() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_7211A4EA409115390D3A199A71F923E5() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_6434C7384610AB93C27DFDB55B587EEA() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_108F933F4D735F27CC5B1EA56D2A92F0() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_9F61C7134CD97E9FFCA77CBDA3B2ADBC() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TwoWayBlend_1E1150084AFE3FC301CDE5895B185E12() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_5E585D334E32B46F3D60E8BE9B98BA15() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TwoWayBlend_AEBF134B4FD750A7FF3F318E8BF1DE05() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_251EC9F1496FA4BFC864DDA0AEEE4018() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_C9BC4EC24A78AD5C468062B9181ED50A() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_7448824C44A7B9D49825A4B44AA123DC() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TwoWayBlend_DC16746A47B1EF4E43D6DA8A1A9F1D95() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_476C64E540C7B84A5C1F2E830C21C7BD() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TwoWayBlend_372B2BFA4D82831B94160C993C4F031A() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_83DFBB624BDA353422585D8A96ACE160() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_1FA874DB472E848088CEC3B456704608() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_22772AFF44FCCBBCD8E7458EDAD62964() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_12407F064475ABE36ED8DA95E17B4ECF() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_7C880AFD46979B1F9B5B0B9E77BE4090() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_D058BCB449BE86765AFF418A7ECDA512() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_814BF3384CBC5863AC1A69AE6964DEC2() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_EDED10694E31C6E8E4F1DF9EA9B55E00() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_48A6B50F4F8DD6F82EB15899EE65BDCA() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_3C9D9C5B45F9E6CD8481BB852B08E6AA() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_D99429C64A2693F41C11D6B7911EEB4E() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_B0A04F504CE19F37001219BDD767DF3F() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_6120F3754B52B1EF7CDEA79FD23CD6D5() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_ECC3ADDF49BFC687B2B10CB05FF20EDB() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_99DD43504CB6973B86076C9CFBAA5DE6() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_1A6EBD054E3AD3FA7168C98908BE640B() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_230E81C948D5AC76EEAD3B80B06CFDB4() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_635E1EF843219CC29C5D888FA8FBA282() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_F385314F48CD7FB3566D50831C06755A() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_B5BA9A924894F38F0FFD5AADFA2F8C0F() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_129AC31A4EDA1DFDD83279A98CAADAA5() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_ED9C8E494166855427C1A4B5516CA576() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_05DBABA04D81BAA0E0EF15AFB93C04C1() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_1B81CAB64F82A76B2895F99FD8B297A8() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_ModifyBone_A79C5930406BB1000C762AB17749829D() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_ModifyBone_88D06C0C454476254D2D679795356B85() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_ModifyBone_6ED05A8D44D5F2634A2B2C9AF1C27850() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_ModifyBone_BE917AA745B45252890C74BED7BA95A9() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_ModifyBone_3BEDCD444595700E6DC8578B51F2240B() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_ModifyBone_140CB7864249C58896C9929CCEEFC44A() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendListByBool_72B456114E3ECC865E817AA28C07A091() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_09573B1E408B5198A05DDC8EE209602B() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendListByBool_EC18DF984D65C1E7618DEEB0B33A0C80() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_2292A9B04553F34558F10A80B79279AC() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_FF85A5E74261580BEEC0BD8F94B6E652() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_4FE9D0C3487622AA66B361B3F866869A() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_3A8FA67D4220B1C4453179B82A98DAF9() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_97611A4A4F805958B5C18AA50AA23456() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_6E6CDF974C563B4305EEA19B598D3FB8() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendListByBool_2C31D1EF4DEF3DDFB9A94F9171C34DDC() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendListByBool_465FB7034702687002968DBB01DB5293() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendListByBool_A74105D54AAE12A4714FE9A8FAA8DCC9() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_0A96BEFD4D238EF0B9F6B186AD4BECA2() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_BD9E9460425DABC91E6A40B6CB37BD33() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_9D6E8E07432F362712BE62BE1AED7FDE() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_4D4743DD4E34FBA6128BFA9291B47D0B() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_3FA60CDF42FF2AC10956F18F541FC3F7() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_68C2635D4F91A646D47F1397583B492A() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_BFCF28BB448669BDBCBEBBAFAB21FA6C() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_92EA86D14277A564BDFB2F8CEFB9E621() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_F5A393C04A97FF02CD85B89C86474250() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_E4C6478044FC91D47962ECAE05778F9C() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_ControlRig_C5D5195E4F4ABEBC21C557AFC87A2FCE() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TwoWayBlend_4FEEDDC5476381E6A23DAE82EC8AA0C3() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_ModifyBone_7CCE01484027B6AE6F176786C32326BA() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_ModifyBone_6229E42B4CD8B433D64E3E9CDC058D11() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_ModifyBone_5B9D0F4949354DE74EADEB85C430A256() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_322ECE364E5B271E6197E1B84F795631() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendListByBool_0BAF32CE4B2082DB61AD5A8C548567C7() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendListByBool_76962C43424595CBEE94A0805FC49EDB() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendListByBool_6593BE454F60DA9B5E88DCAF2D162695() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendListByBool_05E007454EE8276E2B2BF28E21CCF6A7() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_E0B9B7B54A50F7F70659F18A5EDA9F95() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_311617FE4FA4DA9B909DECAF105A2757() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_30F566134092CE6401ACA6927C812A83() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_7E6A82C44ED422D74B1E2995C0700E43() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_88DD4C03447AE6B51AA354A1E133B325() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_CA3C36D6436393F5523618A8F0B9FAB7() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_CCBA3D6D46D44D545C36199085CB7BF0() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_RotationOffsetBlendSpace_EC1D55C041353FF889127AB9D872F211() end
function UABP_Player_New_C:SayBegin() end
function UABP_Player_New_C:SayEnd() end
---@param bNewAnimate boolean
function UABP_Player_New_C:SayAnimate(bNewAnimate) end
---@param DeltaTimeX float
function UABP_Player_New_C:BlueprintUpdateAnimation(DeltaTimeX) end
function UABP_Player_New_C:BlueprintInitializeAnimation() end
function UABP_Player_New_C:AnimNotify_LeftFootDown() end
function UABP_Player_New_C:AnimNotify_RightFootDown() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_4E0EE6C349B51DC36C9039B870A66BC3() end
---@param HitReactionEvent FHitReactionEvent
function UABP_Player_New_C:OnHitReactionEvent(HitReactionEvent) end
---@param LootBox ALootBox
function UABP_Player_New_C:LootBoxOpened(LootBox) end
---@param Door ADoor
---@param Key EInventoryKeyType
function UABP_Player_New_C:DoorUnlocked(Door, Key) end
---@param Item ACollectibleBase
---@param bManually boolean
function UABP_Player_New_C:ItemCollected(Item, bManually) end
---@param Hazard UObject
---@param bCaught boolean
function UABP_Player_New_C:ImmobilizingHazardStateChanged(Hazard, bCaught) end
function UABP_Player_New_C:FellOutOfWorldTeleported() end
function UABP_Player_New_C:FellOutOfWorldCompleted() end
function UABP_Player_New_C:AnimNotify_LandFinish() end
---@param hit FHitResult
---@param Velocity FVector
---@param bHardLand boolean
function UABP_Player_New_C:PlayerLanded(hit, Velocity, bHardLand) end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_74FF4EA44DB20273EC187BB659584022() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_C1A5EE514353CBD432C7A5A49B13CFBC() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_B216234840F21214EC47BC980A0649A3() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_8BBF38E7493E0037E0C1D1AB80545CC8() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_E67EDE7F48D84D5C2E8CD4ADB7835777() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_D50069F448213A9CA262C7BC4CFD9657() end
function UABP_Player_New_C:AnimNotify_IncreaseRobotIdleCount() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_BlendSpacePlayer_980252604DD5AE2BD22681A868CC0283() end
function UABP_Player_New_C:AnimNotify_RobotResetFidgetCounts() end
function UABP_Player_New_C:AnimNotify_RobotL() end
function UABP_Player_New_C:AnimNotify_RobotMidL() end
function UABP_Player_New_C:AnimNotify_RobotMidR() end
function UABP_Player_New_C:AnimNotify_RobotR() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_RotationOffsetBlendSpace_26D691B543E1F21BE9F1BDBB0DFC0E04() end
function UABP_Player_New_C:AnimNotify_CollectionComplete() end
function UABP_Player_New_C:Revived() end
function UABP_Player_New_C:AnimNotify_HardTurnOff() end
function UABP_Player_New_C:AnimNotify_MoveStart_Left() end
function UABP_Player_New_C:AnimNotify_MoveNew_Entered() end
function UABP_Player_New_C:AnimNotify_MoveNew_Left() end
function UABP_Player_New_C:AnimNotify_HardTurn_Entered() end
function UABP_Player_New_C:AnimNotify_HardTurn_Left() end
function UABP_Player_New_C:BlueprintBeginPlay() end
function UABP_Player_New_C:AnimNotify_SprintStarted() end
---@param Weapon APlayerWeapon
function UABP_Player_New_C:ReloadMinigameSuccess(Weapon) end
function UABP_Player_New_C:AnimNotify_Land_State_Entered() end
UABP_Player_New_C['AnimNotify_IdleAim->Move'] = function() end
UABP_Player_New_C['AnimNotify_MoveStop->Move'] = function() end
function UABP_Player_New_C:AnimNotify_ResetRunTimer() end
UABP_Player_New_C['AnimNotify_Walk->Run'] = function() end
function UABP_Player_New_C:AnimNotify_ScanStarted() end
function UABP_Player_New_C:AnimNotify_ScanFinished() end
function UABP_Player_New_C:AnimNotify_StopMoveInput() end
function UABP_Player_New_C:AnimNotify_ResumeMoveInput() end
function UABP_Player_New_C:AnimNotify_180Turn_Entered() end
function UABP_Player_New_C:AnimNotify_180Turn_Left() end
function UABP_Player_New_C:AnimNotify_ReloadFinished() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_6F81DDE14965FE0EBA6B5F9F316D8639() end
---@param WeaponMoveSet ENUM_WeaponChooser::Type
function UABP_Player_New_C:SetAnimSet(WeaponMoveSet) end
---@param OldLocation FVector
---@param Delta FVector
---@param GravDir FVector
function UABP_Player_New_C:OnLedgeMove_Event_0(OldLocation, Delta, GravDir) end
function UABP_Player_New_C:AnimNotify_Collapsed() end
function UABP_Player_New_C:AnimNotify_NotCollapsed() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_D3AF41E447829675ADFB2396045E3DD9() end
function UABP_Player_New_C:AnimNotify_PickFaceAnim() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_CDBE972540155F001CC18F94CC0890C2() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_CC4C68514E37E86F671D799DBCABEB4D() end
function UABP_Player_New_C:AnimNotify_HookShotting() end
function UABP_Player_New_C:AnimNotify_OutOfDash() end
function UABP_Player_New_C:AnimNotify_DashFinished() end
function UABP_Player_New_C:AnimNotify_MovingMelee() end
function UABP_Player_New_C:AnimNotify_OutOfHookshot() end
function UABP_Player_New_C:AnimNotify_Land_State_Left() end
---@param DashComponent UDashAbilityComponent
---@param bPerfectDodge boolean
---@param DashLevel int32
function UABP_Player_New_C:DashStarted(DashComponent, bPerfectDodge, DashLevel) end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_DFD93A634786605D36DD6486A67E882E() end
function UABP_Player_New_C:AnimNotify_ObCollectorPickUp() end
function UABP_Player_New_C:AnimNotify_DisableLipSync() end
function UABP_Player_New_C:AnimNotify_MeleeStarted() end
---@param Cinematic ACinematicActor
function UABP_Player_New_C:OnPreStartCinematicEvent_Event_0(Cinematic) end
function UABP_Player_New_C:AnimNotify_Grounded_Left() end
function UABP_Player_New_C:AnimNotify_Grounded_Entered() end
---@param NewWeapon APlayerWeapon
---@param OldWeapon APlayerWeapon
function UABP_Player_New_C:ChangeSelectedGun(NewWeapon, OldWeapon) end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_5D3C2017455393AC769D4C8C91996979() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_785EA0BB40ADB4683B03FAB5071F1866() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_14F52E194FF5A20F399B96A786EAD983() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_C78EDEAE494AE30E3B5FC89DCF26358A() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_5AE8F5EA41A4F3649A9915B8917DBE15() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_500E5DA94C5F247EA94218870274DEFA() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_ACBB7BCA431E0B59F45E56B7E296F836() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_F07D9791454F39DFE1EEC2A1E5D54DAB() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_03FD55BD4332A40E63777A891101D26D() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_833B75BA4B139D4CA2EDBDB398375815() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_280B74AC401BCD64378D2A9C6DA156D3() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_50969C384C7C850D070E19B055866AB3() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_0E09AC16493D6AF90170478B3149158E() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_SequencePlayer_C166C6F14035A688096D15963AE4F3B5() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_RotateRootBone_66855DAF4F2785BA7800FCAADFD432B5() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_RotationOffsetBlendSpace_46DBF943479F343E8FBDCDBB47888E68() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_RotateRootBone_EE7B30E24CA488B31F8035B2E471E5CB() end
function UABP_Player_New_C:EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Player_New_AnimGraphNode_TransitionResult_B94E0EF6439C2DF485716A85D5C1F31A() end
---@param EntryPoint int32
function UABP_Player_New_C:ExecuteUbergraph_ABP_Player_New(EntryPoint) end


