---@meta

---@class UAudio_Weather_RainShelterSystem_C : UAudioWeatherRainShelterSystem
---@field UberGraphFrame FPointerToUberGraphFrame
---@field StartEnabled boolean
---@field r_IsEnabled boolean
---@field DrawDebugRays boolean
---@field ComponentUpdateRateSeconds float
---@field NoOfEmittersPerRingToUpdateEachCompUpdate int32
---@field PlayerToListenerRootAlpha float
---@field DoInnerCircle boolean
---@field DoOuterCircle boolean
---@field r_INNERRingEmitterDegrees float
---@field r_OUTERRingEmitterDegrees float
---@field OcclusionRefreshInterval float
---@field RootCoverHeightCheck float
---@field r_RainfallRayLength float
---@field NoOfEmittersINNERRing int32
---@field InnerRayPrimaryDistance int32
---@field InnerRaySecondaryDistance int32
---@field OcclusionRaysPerFrame int32
---@field NoOfEmittersOUTERRing int32
---@field OuterRayPrimaryDistance int32
---@field OuterRaySecondaryDistance int32
---@field OuterRayTertiaryDistance int32
---@field OuterRayAboveRootThreshold int32
---@field OuterRayBelowRootThreshold int32
---@field InnerRayTertiaryDistance int32
---@field InnerRayAboveRootThreshold int32
---@field InnerRayBelowRootThreshold int32
---@field MaxNoOfINNERDistanceChecks int32
---@field r_INNERRayCastPositions TArray<FVector>
---@field r_ValidInnerPositions TArray<FVector>
---@field MaxNoOfOUTERDistanceChecks int32
---@field r_OUTERRayCastPositions TArray<FVector>
---@field r_ValidOuterPositions TArray<FVector>
---@field r_OuterEmitters TArray<UAkComponent>
---@field r_OuterMaterials TArray<EPhysicalSurface>
---@field r_NextOUTEREmitterUpdateIndex int32
---@field r_InnerEmitters TArray<UAkComponent>
---@field r_InnerMaterials TArray<EPhysicalSurface>
---@field r_NextINNEREmitterUpdateIndex int32
---@field r_CurrentEmitter UAkComponent
---@field DrawDebugSpheres boolean
---@field r_PlayerSuitRainEmitter UAkComponent
---@field r_IsPlayerSuitCovered boolean
---@field TraceType ETraceTypeQuery
---@field UseComplexCollisions boolean
---@field r_HasInitialised boolean
---@field EmitterTickRate float
---@field R_RainIntensityLastFrame float
---@field LatentDone boolean
---@field InnerRayDistances TArray<float>
---@field OuterRayDistances TArray<float>
---@field CachedRainfallRayLength float
---@field CachedRainfallRayHeight float
---@field CachedRootCoverHeightCheckk float
---@field TimelessTowerOverrideActive boolean
UAudio_Weather_RainShelterSystem_C = {}

function UAudio_Weather_RainShelterSystem_C:SetAkComponentTickRate() end
function UAudio_Weather_RainShelterSystem_C:ResetAllMaterialSwitchesToArrayEntry() end
---@param String FString
function UAudio_Weather_RainShelterSystem_C:Debug_SetAllEmittersToMaterialSwitch(String) end
function UAudio_Weather_RainShelterSystem_C:DebugPrintNamesOfUpdatedEmitters() end
function UAudio_Weather_RainShelterSystem_C:PlaySFX() end
function UAudio_Weather_RainShelterSystem_C:StopSFX() end
---@param Emitter USceneComponent
---@param DebugColour FLinearColor
---@param materialarray TArray<EPhysicalSurface>
---@param index int32
function UAudio_Weather_RainShelterSystem_C:DebugDrawEmitters(Emitter, DebugColour, materialarray, index) end
function UAudio_Weather_RainShelterSystem_C:Init() end
---@param DeltaSeconds float
function UAudio_Weather_RainShelterSystem_C:ReceiveTick(DeltaSeconds) end
function UAudio_Weather_RainShelterSystem_C:ReceiveBeginPlay() end
function UAudio_Weather_RainShelterSystem_C:F_ENABLE() end
function UAudio_Weather_RainShelterSystem_C:F_DISABLE() end
function UAudio_Weather_RainShelterSystem_C:DEBUG_ToggleDrawRays() end
function UAudio_Weather_RainShelterSystem_C:DEBUG_ToggleDrawSpheres() end
function UAudio_Weather_RainShelterSystem_C:DEBUG_SetMaterialToStone() end
function UAudio_Weather_RainShelterSystem_C:ResetMaterials() end
function UAudio_Weather_RainShelterSystem_C:DEBUG_SetMaterialToForestFloor() end
function UAudio_Weather_RainShelterSystem_C:DEBUG_SetMaterialToMetal() end
---@param Active boolean
function UAudio_Weather_RainShelterSystem_C:TimelessTowerSettingsOverride(Active) end
---@param EntryPoint int32
function UAudio_Weather_RainShelterSystem_C:ExecuteUbergraph_Audio_Weather_RainShelterSystem(EntryPoint) end


