---@meta

---@class ABP_AlienForestDoorBase_C : ABP_DoorBase_C
---@field UberGraphFrame FPointerToUberGraphFrame
---@field SM_SDF UStaticMeshComponent
---@field SM_LevelDoor_Highlight UStaticMeshComponent
---@field AkStaticWideRight UAkComponent
---@field AkStaticWideLeft UAkComponent
---@field AkRocks8 UAkComponent
---@field AkRocks7 UAkComponent
---@field AkRocks6 UAkComponent
---@field AkRocks5 UAkComponent
---@field NGParticleGroundDust_CD UNGParticleComponent
---@field NGParticleFallingRocksD_CD UNGParticleComponent
---@field NGParticleFallingRocksC_CD UNGParticleComponent
---@field NGParticleFallingRocksB_CD UNGParticleComponent
---@field NGParticleFallingRocksA_CD UNGParticleComponent
---@field Box10 UBoxComponent
---@field Box9 UBoxComponent
---@field SpotLight_L_2 USpotLightComponent
---@field SpotLight_R_2 USpotLightComponent
---@field SpotLight_Top_2 USpotLightComponent
---@field SpotLight_Top_1 USpotLightComponent
---@field SpotLight_L USpotLightComponent
---@field SpotLight_Lock USpotLightComponent
---@field SpotLight_R USpotLightComponent
---@field BPC_AreaScannable UBPC_AreaScannable_C
---@field RearTransform USceneComponent
---@field FrontTransform USceneComponent
---@field WideMoveR UAkComponent
---@field WideMoveL UAkComponent
---@field AkSpinR UAkComponent
---@field SpinR USceneComponent
---@field AkSpinL UAkComponent
---@field SpinL USceneComponent
---@field AkWideMoveLateR UAkComponent
---@field AkWideMoveLateL UAkComponent
---@field AkWideR UAkComponent
---@field AkWideL UAkComponent
---@field AkTopL UAkComponent
---@field AkCentreLock UAkComponent
---@field CentreR UAkComponent
---@field CentreL UAkComponent
---@field AkTopR UAkComponent
---@field AkEmitters USceneComponent
---@field AkDebrisMid_R UAkComponent
---@field AkDebrisMid_L UAkComponent
---@field AkDebrisHigh_R UAkComponent
---@field AkDebrisHigh_L UAkComponent
---@field AkDebrisLow_R UAkComponent
---@field AkDebrisLow_L UAkComponent
---@field AkRocks4 UAkComponent
---@field AkRocks3 UAkComponent
---@field AkRocks2 UAkComponent
---@field AkRocks1 UAkComponent
---@field NGParticleMeshEmitterUnderwater UNGParticleComponent
---@field SM_Lock UStaticMeshComponent
---@field NGParticleFallingRocksD UNGParticleComponent
---@field NGParticleFallingRocksC UNGParticleComponent
---@field NGParticleFallingRocksB UNGParticleComponent
---@field NGParticleFallingRocksA UNGParticleComponent
---@field NGParticleMeshEmitter UNGParticleComponent
---@field PS_DoorUnlock1 UParticleSystemComponent
---@field PS_DoorUnlock UParticleSystemComponent
---@field SkeletalMesh_Door USkeletalMeshComponent
---@field Lights USceneComponent
---@field StaticMesh_Frame UStaticMeshComponent
---@field BPC_DoorLockdown UBPC_DoorLockdown_C
---@field Collisions USceneComponent
---@field Timeline_1_NewTrack_0_39F708744DC88622A5C9BF9EFC310D04 float
---@field Timeline_1__Direction_39F708744DC88622A5C9BF9EFC310D04 ETimelineDirection::Type
---@field Timeline_1 UTimelineComponent
---@field DoorDynamicMaterial0 UMaterialInstanceDynamic
---@field DoorDynamicMaterial1 UMaterialInstanceDynamic
---@field MaterialColor FLinearColor
---@field Biome EBiome
---@field Emitters UAkComponent
---@field InitialDoorMaterials TArray<UMaterialInterface>
---@field InitialFrameMaterials TArray<UMaterialInterface>
---@field OpenSoundVariation FString
ABP_AlienForestDoorBase_C = {}

function ABP_AlienForestDoorBase_C:AnimNotify_SFXClunk2() end
function ABP_AlienForestDoorBase_C:AnimNotify_SFXClunk2FirstOpen() end
function ABP_AlienForestDoorBase_C:AnimNotify_SFXStartFirstOpen() end
function ABP_AlienForestDoorBase_C:NudgeEmittersToBeOnPlayerSideOfDoor() end
---@param EnableTick boolean
function ABP_AlienForestDoorBase_C:AudioEnableEmitterTick(EnableTick) end
function ABP_AlienForestDoorBase_C:DebugDraw() end
function ABP_AlienForestDoorBase_C:AnimNotify_SFXStartOpen() end
function ABP_AlienForestDoorBase_C:AnimNotify_SFXStartClose() end
---@param Color FLinearColor
function ABP_AlienForestDoorBase_C:SetDoorColor(Color) end
---@param Color FLinearColor
function ABP_AlienForestDoorBase_C:SetLightColor(Color) end
function ABP_AlienForestDoorBase_C:UserConstructionScript() end
function ABP_AlienForestDoorBase_C:Timeline_1__FinishedFunc() end
function ABP_AlienForestDoorBase_C:Timeline_1__UpdateFunc() end
---@param Door ADoor
function ABP_AlienForestDoorBase_C:LockdownChanged(Door) end
function ABP_AlienForestDoorBase_C:SetupFirstOpen() end
function ABP_AlienForestDoorBase_C:SetupTraverseComplete() end
function ABP_AlienForestDoorBase_C:SetupOpen() end
---@param alpha float
function ABP_AlienForestDoorBase_C:OpenUpdate(alpha) end
function ABP_AlienForestDoorBase_C:OpenComplete() end
function ABP_AlienForestDoorBase_C:ReceiveBeginPlay() end
---@param OverlappedComponent UPrimitiveComponent
---@param OtherActor AActor
---@param OtherComp UPrimitiveComponent
---@param OtherBodyIndex int32
---@param bFromSweep boolean
---@param SweepResult FHitResult
function ABP_AlienForestDoorBase_C:BndEvt__BigOverlap_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(OverlappedComponent, OtherActor, OtherComp, OtherBodyIndex, bFromSweep, SweepResult) end
---@param OverlappedComponent UPrimitiveComponent
---@param OtherActor AActor
---@param OtherComp UPrimitiveComponent
---@param OtherBodyIndex int32
function ABP_AlienForestDoorBase_C:BndEvt__BigOverlap_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(OverlappedComponent, OtherActor, OtherComp, OtherBodyIndex) end
---@param OverlappedComponent UPrimitiveComponent
---@param OtherActor AActor
---@param OtherComp UPrimitiveComponent
---@param OtherBodyIndex int32
---@param bFromSweep boolean
---@param SweepResult FHitResult
function ABP_AlienForestDoorBase_C:BndEvt__Trigger_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature(OverlappedComponent, OtherActor, OtherComp, OtherBodyIndex, bFromSweep, SweepResult) end
---@param OverlappedComponent UPrimitiveComponent
---@param OtherActor AActor
---@param OtherComp UPrimitiveComponent
---@param OtherBodyIndex int32
function ABP_AlienForestDoorBase_C:BndEvt__SkeletalMesh_Door_K2Node_ComponentBoundEvent_3_ComponentEndOverlapSignature__DelegateSignature(OverlappedComponent, OtherActor, OtherComp, OtherBodyIndex) end
function ABP_AlienForestDoorBase_C:BndEvt__BPC_AreaScannable_K2Node_ComponentBoundEvent_4_OnBeginAreaScan__DelegateSignature() end
function ABP_AlienForestDoorBase_C:BndEvt__BPC_AreaScannable_K2Node_ComponentBoundEvent_5_OnEndAreaScan__DelegateSignature() end
---@param Door ADoor
function ABP_AlienForestDoorBase_C:OnDoorOpen(Door) end
---@param EndPlayReason EEndPlayReason::Type
function ABP_AlienForestDoorBase_C:ReceiveEndPlay(EndPlayReason) end
function ABP_AlienForestDoorBase_C:HandleRespawned() end
function ABP_AlienForestDoorBase_C:BindEvents() end
---@param Biome EBiome
---@param NewBiomeState EBiomeState
function ABP_AlienForestDoorBase_C:OnBiomeStateChanged(Biome, NewBiomeState) end
---@param EntryPoint int32
function ABP_AlienForestDoorBase_C:ExecuteUbergraph_BP_AlienForestDoorBase(EntryPoint) end


