---@meta

---@class ABP_Cinematic_PerspectiveTransition_C : ABP_CinematicSequence_C
---@field UberGraphFrame FPointerToUberGraphFrame
---@field BPC_PerspectiveTransitionControl UBPC_PerspectiveTransitionControl_C
---@field BPC_CinematicProps UBPC_CinematicProps_C
---@field BPC_HideRemotePlayer UBPC_HideRemotePlayer_C
---@field BPC_GlitchPlayer UBPC_GlitchPlayer_C
---@field SkipBillboard UBillboardComponent
---@field SkipMarker USceneComponent
---@field BPC_CinematicCharacterControl UBPC_CinematicCharacterControl_C
---@field SpawnBillboard UBillboardComponent
---@field StreamTransition UBPC_StreamLevelTransitionHandler_C
---@field FirstPersonPlayerMarker USceneComponent
---@field Timeline_CameraModifiers_Alpha_7A80AE034740D77DFAAB93BA14E2832B float
---@field Timeline_CameraModifiers__Direction_7A80AE034740D77DFAAB93BA14E2832B ETimelineDirection::Type
---@field Timeline_CameraModifiers UTimelineComponent
---@field TransitionType Enum_PerspectiveTransitions::Type
---@field OnGoInside FBP_Cinematic_PerspectiveTransition_COnGoInside
---@field OnOpenDoor FBP_Cinematic_PerspectiveTransition_COnOpenDoor
---@field OnLighting FBP_Cinematic_PerspectiveTransition_COnLighting
---@field EnableCinematicCamera boolean
---@field ShowTorso boolean
---@field ThirdPersonTriggered boolean
---@field MontageToPlay_ThirdPerson UAnimMontage
---@field MontageToPlay_FirstPerson UAnimMontage
---@field MontageToPlay_FirstPersonShadow UAnimMontage
---@field PlayerClassToSpawn TSubclassOf<ABP_FirstPersonPlayerCharacter_C>
---@field HouseOutTag FName
---@field Props TArray<FS_CinematicProp>
---@field MontageStartPos float
---@field MontageStartSection FName
---@field isHouseSequence boolean
---@field OutroBound boolean
---@field StrictFPMode boolean
---@field isDummySequence boolean
---@field IsHouseExit boolean
---@field HouseExitCoutdownDelay float
---@field HouseExitCoutdownDuration float
---@field IsHouseEnter boolean
---@field Intermediate boolean
---@field DisableThirdPersonCollision boolean
---@field DisableFirstPersonCollision boolean
---@field Audio_1p_3P_isBlending boolean
---@field AppliedCameraModAlpha float
---@field HasDisabledDynamicEnvironment boolean
ABP_Cinematic_PerspectiveTransition_C = {}

---@param Character ACharacter
---@param Info FString
function ABP_Cinematic_PerspectiveTransition_C:PrintCharacterLocation(Character, Info) end
---@param BindingName FName
---@param Character ACharacter
---@param Result FCinematicSequenceBinding
function ABP_Cinematic_PerspectiveTransition_C:CreateCharacterBinding(BindingName, Character, Result) end
---@param Bindings TArray<FCinematicSequenceBinding>
function ABP_Cinematic_PerspectiveTransition_C:GatherSequenceBindings(Bindings) end
---@param Character ACharacter
function ABP_Cinematic_PerspectiveTransition_C:PlaceCharacterToCinematic(Character) end
function ABP_Cinematic_PerspectiveTransition_C:InitializeFullFPMode() end
---@param Result boolean
function ABP_Cinematic_PerspectiveTransition_C:ShouldPossessFPOnSpawn(Result) end
function ABP_Cinematic_PerspectiveTransition_C:SwitchToThirdPersonVisible() end
---@param Character ACharacter
---@param Location FVector
---@param Rotation FRotator
function ABP_Cinematic_PerspectiveTransition_C:PlaceCharacter(Character, Location, Rotation) end
function ABP_Cinematic_PerspectiveTransition_C:FirstToThirdInitializeCinematicCamera() end
function ABP_Cinematic_PerspectiveTransition_C:ApplyViewActorToControlRotation() end
---@param Enabled boolean
function ABP_Cinematic_PerspectiveTransition_C:HeadlessMode(Enabled) end
---@param Result APlayerController
function ABP_Cinematic_PerspectiveTransition_C:GetTransitionPlayerController(Result) end
---@param Result APawn
function ABP_Cinematic_PerspectiveTransition_C:GetCameraBlendOutPawn(Result) end
---@param Result ABP_StreamLevelTransition_C
function ABP_Cinematic_PerspectiveTransition_C:GetStreamLevelTransition(Result) end
---@param visible boolean
function ABP_Cinematic_PerspectiveTransition_C:SetThirdPersonVisibility(visible) end
---@param Result APlayerCharacter
function ABP_Cinematic_PerspectiveTransition_C:GetThirdPersonCharacter(Result) end
---@param Enabled boolean
---@param KeepWorld boolean
---@param ReturnAnimation boolean
function ABP_Cinematic_PerspectiveTransition_C:StrictCinematicFPViewMode(Enabled, KeepWorld, ReturnAnimation) end
---@param Location FVector
---@param Rotation FRotator
function ABP_Cinematic_PerspectiveTransition_C:GetFPSpawnTransform(Location, Rotation) end
---@param Character ABP_FirstPersonPlayerCharacter_C
function ABP_Cinematic_PerspectiveTransition_C:GetFirstPersonCharacter(Character) end
function ABP_Cinematic_PerspectiveTransition_C:Timeline_CameraModifiers__FinishedFunc() end
function ABP_Cinematic_PerspectiveTransition_C:Timeline_CameraModifiers__UpdateFunc() end
---@param NotifyName FName
function ABP_Cinematic_PerspectiveTransition_C:OnNotifyEnd_0BA78FE7482BFDACDFDD5AB7915BC322(NotifyName) end
---@param NotifyName FName
function ABP_Cinematic_PerspectiveTransition_C:OnNotifyBegin_0BA78FE7482BFDACDFDD5AB7915BC322(NotifyName) end
---@param NotifyName FName
function ABP_Cinematic_PerspectiveTransition_C:OnInterrupted_0BA78FE7482BFDACDFDD5AB7915BC322(NotifyName) end
---@param NotifyName FName
function ABP_Cinematic_PerspectiveTransition_C:OnBlendOut_0BA78FE7482BFDACDFDD5AB7915BC322(NotifyName) end
---@param NotifyName FName
function ABP_Cinematic_PerspectiveTransition_C:OnCompleted_0BA78FE7482BFDACDFDD5AB7915BC322(NotifyName) end
---@param Immediate boolean
function ABP_Cinematic_PerspectiveTransition_C:CameraModifiersOff(Immediate) end
function ABP_Cinematic_PerspectiveTransition_C:CameraModifiersOn() end
function ABP_Cinematic_PerspectiveTransition_C:DynamicEnvironmentOff() end
function ABP_Cinematic_PerspectiveTransition_C:DynamicEnvironmentOn() end
---@param Enabled boolean
function ABP_Cinematic_PerspectiveTransition_C:SetPlayerFlashlightEnabled(Enabled) end
---@param Enabled boolean
function ABP_Cinematic_PerspectiveTransition_C:SetHUDEnabled(Enabled) end
---@param Time float
function ABP_Cinematic_PerspectiveTransition_C:SetCameraModifierTimelineTime(Time) end
---@param UseFirstPersonCharacterCamera boolean
---@param ViewBlendDuration float
function ABP_Cinematic_PerspectiveTransition_C:TriggerFirstPerson(UseFirstPersonCharacterCamera, ViewBlendDuration) end
function ABP_Cinematic_PerspectiveTransition_C:ReceiveStopCinematic() end
function ABP_Cinematic_PerspectiveTransition_C:SetupSequence() end
function ABP_Cinematic_PerspectiveTransition_C:PlaySequence() end
---@param Handler UBPC_StreamLevelTransitionHandler_C
function ABP_Cinematic_PerspectiveTransition_C:BndEvt__BPC_StreamLevelTransitionHandler_K2Node_ComponentBoundEvent_0_OnTransitionStart__DelegateSignature(Handler) end
---@param Handler UBPC_StreamLevelTransitionHandler_C
function ABP_Cinematic_PerspectiveTransition_C:BndEvt__BPC_StreamLevelTransitionHandler_K2Node_ComponentBoundEvent_0_OnTransitionLoad__DelegateSignature(Handler) end
function ABP_Cinematic_PerspectiveTransition_C:TransitionBackToGame() end
function ABP_Cinematic_PerspectiveTransition_C:TriggerThirdPerson() end
function ABP_Cinematic_PerspectiveTransition_C:InitializeThirdToFirst() end
function ABP_Cinematic_PerspectiveTransition_C:InitializeFirstToThird() end
function ABP_Cinematic_PerspectiveTransition_C:CleanUpFirstPerson() end
---@param TransitionParams FViewTargetTransitionParams
function ABP_Cinematic_PerspectiveTransition_C:NoCameraBlendOut(TransitionParams) end
function ABP_Cinematic_PerspectiveTransition_C:BndEvt__StreamTransition_K2Node_ComponentBoundEvent_1_OnTransitionSwitch__DelegateSignature() end
function ABP_Cinematic_PerspectiveTransition_C:BndEvt__StreamTransition_K2Node_ComponentBoundEvent_3_OnTransitionComplete__DelegateSignature() end
function ABP_Cinematic_PerspectiveTransition_C:InitializeOutroCinematic() end
---@param Cinematic ACinematicActor
---@param bImmediate boolean
function ABP_Cinematic_PerspectiveTransition_C:OutroCinematicCompleted(Cinematic, bImmediate) end
function ABP_Cinematic_PerspectiveTransition_C:StopFirstToThird() end
function ABP_Cinematic_PerspectiveTransition_C:InitializeLinkThirdToFirst() end
function ABP_Cinematic_PerspectiveTransition_C:TriggerFirstPersonNoCamera() end
function ABP_Cinematic_PerspectiveTransition_C:TriggerThirdPersonInternal() end
function ABP_Cinematic_PerspectiveTransition_C:InitializeLinkFirstToThird() end
function ABP_Cinematic_PerspectiveTransition_C:InitializeTransition() end
function ABP_Cinematic_PerspectiveTransition_C:StopThirdToFirst() end
function ABP_Cinematic_PerspectiveTransition_C:PreSequence() end
function ABP_Cinematic_PerspectiveTransition_C:ReceiveRunCinematic() end
function ABP_Cinematic_PerspectiveTransition_C:StopLinkThirdToFirst() end
function ABP_Cinematic_PerspectiveTransition_C:StopLinkFirstToThird() end
---@param SkipGateName FName
function ABP_Cinematic_PerspectiveTransition_C:ReceiveSkipCinematic(SkipGateName) end
function ABP_Cinematic_PerspectiveTransition_C:SkipFirstToThird() end
function ABP_Cinematic_PerspectiveTransition_C:SkipLinkThirdToFirst() end
function ABP_Cinematic_PerspectiveTransition_C:SkipLinkFirstToThird() end
function ABP_Cinematic_PerspectiveTransition_C:SkipThirdToFirst() end
function ABP_Cinematic_PerspectiveTransition_C:TransitionSkip() end
function ABP_Cinematic_PerspectiveTransition_C:PlayMontages() end
function ABP_Cinematic_PerspectiveTransition_C:StopMontages() end
function ABP_Cinematic_PerspectiveTransition_C:ReceiveBeginPlay() end
function ABP_Cinematic_PerspectiveTransition_C:InitializePerpectiveTransition() end
function ABP_Cinematic_PerspectiveTransition_C:PlayCamera() end
function ABP_Cinematic_PerspectiveTransition_C:ReceiveStartCinematic() end
function ABP_Cinematic_PerspectiveTransition_C:HouseCountdownExpired() end
function ABP_Cinematic_PerspectiveTransition_C:SwitchToFirstPerson() end
function ABP_Cinematic_PerspectiveTransition_C:CameraBlendOutOnce() end
---@param EndPlayReason EEndPlayReason::Type
function ABP_Cinematic_PerspectiveTransition_C:ReceiveEndPlay(EndPlayReason) end
function ABP_Cinematic_PerspectiveTransition_C:StrictCinematicFPViewBlendOut() end
---@param EntryPoint int32
function ABP_Cinematic_PerspectiveTransition_C:ExecuteUbergraph_BP_Cinematic_PerspectiveTransition(EntryPoint) end
function ABP_Cinematic_PerspectiveTransition_C:OnLighting__DelegateSignature() end
function ABP_Cinematic_PerspectiveTransition_C:OnOpenDoor__DelegateSignature() end
function ABP_Cinematic_PerspectiveTransition_C:OnGoInside__DelegateSignature() end


