---@meta

---@class ABP_Checkpoint_C : AHMQActor
---@field UberGraphFrame FPointerToUberGraphFrame
---@field BPC_InteractConditionNetRole UBPC_InteractConditionNetRole_C
---@field BPC_InteractConditionClarity UBPC_InteractConditionClarity_C
---@field NGP_OpeningFog0 UNGParticleComponent
---@field NGP_OpeningFog13 UNGParticleComponent
---@field NGP_OpeningFog12 UNGParticleComponent
---@field NGP_OpeningFog11 UNGParticleComponent
---@field NGP_OpeningFog10 UNGParticleComponent
---@field NGP_OpeningFog9 UNGParticleComponent
---@field NGP_OpeningFog8 UNGParticleComponent
---@field NGP_OpeningFog7 UNGParticleComponent
---@field NGP_OpeningFog6 UNGParticleComponent
---@field NGP_OpeningFog5 UNGParticleComponent
---@field NGP_OpeningFog4 UNGParticleComponent
---@field NGP_OpeningFog3 UNGParticleComponent
---@field NGP_OpeningFog2 UNGParticleComponent
---@field NGP_OpeningFog1 UNGParticleComponent
---@field BPC_CollectibleVisuals UBPC_CollectibleVisuals_C
---@field V3LookAtSource UV3LookAtSourceComponent
---@field AkGameObjectBack UAkGameObject
---@field AkGameObjectFront UAkGameObject
---@field Audio_Idle_Front UManagedAkComponent_C
---@field Audio_Idle_Back UManagedAkComponent_C
---@field BPC_CinematicSelfBinding UBPC_CinematicSelfBinding_C
---@field HMQActorActivator UHMQActorActivatorComponent
---@field NGP_Fog UNGParticleComponent
---@field MinimapObject UMinimapObject
---@field ChildActor_CinematicRevive UChildActorComponent
---@field ExtraLifeObject UExtraLifeObjectComponent
---@field ChildActor_CinematicActivate UChildActorComponent
---@field BPC_DiscoverableMachine UBPC_DiscoverableMachine_C
---@field DespawnableActor UDespawnableActorComponent
---@field MaterialManipulator UMaterialManipulatorComponent
---@field HUDLabel UHUDLabel
---@field HUDDetails UHUDDetailsComponent
---@field SkeletalMesh USkeletalMeshComponent
---@field TeleportRoot USceneComponent
---@field Box_Trigger UBoxComponent
---@field Interactable UInteractableComponent
---@field SM_OperationsMachine UStaticMeshComponent
---@field Root USceneComponent
---@field Consumed boolean
---@field CheckpointOpen boolean
---@field CheckpointGuid FGuid
---@field IsPlaying boolean
---@field ActivateClarityCost float
---@field NewVar_0 UManagedAkComponent_C
---@field NewVar_1 UAkGameObject
---@field ScanCameraSourceLocalLoc FVector
---@field Access_Denied_Sound UAkAudioEvent
---@field SetCheckpointForAllPlayers boolean
---@field PlayersThatHaveHadCheckpointActive TArray<TSoftObjectPtr<ACharacter>>
ABP_Checkpoint_C = {}

---@param PlayerController APlayerController
---@param Override boolean
---@param visible boolean
function ABP_Checkpoint_C:GetLabelPriceVisibilityOverride(PlayerController, Override, visible) end
---@param MeshRelativeTransform FTransform
function ABP_Checkpoint_C:GetScanHologramMeshTransform(MeshRelativeTransform) end
---@param HologramMesh UMeshComponent
function ABP_Checkpoint_C:GetScanHologramMesh(HologramMesh) end
---@param OutCameraData FScanCameraData
---@param Success boolean
function ABP_Checkpoint_C:FillScanCameraData(OutCameraData, Success) end
---@param Character ATouristCharacter
function ABP_Checkpoint_C:AddCheckpointToPlayer(Character) end
function ABP_Checkpoint_C:BuildState() end
---@param Result boolean
function ABP_Checkpoint_C:CanActivateWithClarity(Result) end
function ABP_Checkpoint_C:OnRep_CheckpointGuid() end
function ABP_Checkpoint_C:ConsumeCheckpoint() end
function ABP_Checkpoint_C:CloseCheckpoint() end
function ABP_Checkpoint_C:OpenCheckpoint() end
function ABP_Checkpoint_C:ResetState() end
function ABP_Checkpoint_C:UpdateState() end
function ABP_Checkpoint_C:UserConstructionScript() end
function ABP_Checkpoint_C:ScanHologramStarted() end
---@param ScanPercentage float
function ABP_Checkpoint_C:ScanHologramStopped(ScanPercentage) end
function ABP_Checkpoint_C:ReceiveBeginPlay() end
---@param InteractingController AController
function ABP_Checkpoint_C:BndEvt__Interactable_K2Node_ComponentBoundEvent_1_OnInteractSignature__DelegateSignature(InteractingController) end
---@param InteractingController AController
function ABP_Checkpoint_C:BndEvt__Interactable_K2Node_ComponentBoundEvent_2_OnGetInteractArgsSignature__DelegateSignature(InteractingController) end
---@param Serializer TScriptInterface<IDespawnableActorSerializer>
function ABP_Checkpoint_C:BndEvt__DespawnableActor_K2Node_ComponentBoundEvent_0_SerializeState__DelegateSignature(Serializer) end
function ABP_Checkpoint_C:TriggerCheckpoint() end
---@param Activate boolean
---@param InPlayerController APlayerController
function ABP_Checkpoint_C:StartCinematic(Activate, InPlayerController) end
---@param ExtraLifeObject UExtraLifeObjectComponent
function ABP_Checkpoint_C:BndEvt__ExtraLifeObject_K2Node_ComponentBoundEvent_3_ExtraLifeObjectSignature__DelegateSignature(ExtraLifeObject) end
---@param ExtraLifeObject UExtraLifeObjectComponent
function ABP_Checkpoint_C:BndEvt__ExtraLifeObject_K2Node_ComponentBoundEvent_4_ExtraLifeObjectSignature__DelegateSignature(ExtraLifeObject) end
---@param Cinematic ACinematicActor
---@param bImmediate boolean
function ABP_Checkpoint_C:CinematicFinished(Cinematic, bImmediate) end
function ABP_Checkpoint_C:AnimNotify_DoorsOpening() end
function ABP_Checkpoint_C:AnimNotify_DoorsClosing() end
function ABP_Checkpoint_C:AnimNotify_DoorsOpen() end
function ABP_Checkpoint_C:AnimNotify_DoorsClosed() end
---@param InteractingController AController
function ABP_Checkpoint_C:BndEvt__Interactable_K2Node_ComponentBoundEvent_5_OnInteractSignature__DelegateSignature(InteractingController) end
---@param Controller AController
function ABP_Checkpoint_C:Interacted(Controller) end
---@param EndPlayReason EEndPlayReason::Type
function ABP_Checkpoint_C:ReceiveEndPlay(EndPlayReason) end
function ABP_Checkpoint_C:AnimNotify_DoorSmokeOpening() end
---@param InteractingController AController
function ABP_Checkpoint_C:BndEvt__Interactable_K2Node_ComponentBoundEvent_6_OnInteractFailureSignature__DelegateSignature(InteractingController) end
---@param value FString
function ABP_Checkpoint_C:ReceiveGenericSignal(value) end
---@param Cinematic ACinematicActor
function ABP_Checkpoint_C:CinematicEitherStart(Cinematic) end
---@param Cinematic ACinematicActor
---@param bImmediate boolean
function ABP_Checkpoint_C:CinematicEitherComplete(Cinematic, bImmediate) end
---@param CinematicActor ACinematicActor
function ABP_Checkpoint_C:CinematicComplete(CinematicActor) end
---@param CinematicActor ACinematicActor
function ABP_Checkpoint_C:UpdateStats(CinematicActor) end
---@param EntryPoint int32
function ABP_Checkpoint_C:ExecuteUbergraph_BP_Checkpoint(EntryPoint) end


