---@meta

---@class ABP_FirstPersonPlayerCharacter_C : AFirstPersonPlayerCharacter
---@field UberGraphFrame FPointerToUberGraphFrame
---@field SayAttributes USayAttributesComponent
---@field MirrorAsset USkeletalMeshComponent
---@field ChildActor_VisualCapsule UChildActorComponent
---@field BPC_PlayerCharacterAudio UBPC_PlayerCharacterAudio_C
---@field Camera UCameraComponent
---@field CameraMovement USceneComponent
---@field CameraOffset USceneComponent
---@field ReflectionTracker UReflectionTrackerComponent
---@field ShadowAsset USkeletalMeshComponent
---@field Sounds UAkComponent
---@field FootStep1 UFootStepComponent
---@field RadialForce URadialForceComponent
---@field BallKicker UStaticMeshComponent
---@field Overlapper UStaticMeshComponent
---@field AnimationCamera UCameraComponent
---@field PropAttachment USceneComponent
---@field Timeline_0_NewTrack_0_B2EBF2DA447BF342E981F3B3F2F6893E float
---@field Timeline_0__Direction_B2EBF2DA447BF342E981F3B3F2F6893E ETimelineDirection::Type
---@field Timeline_0 UTimelineComponent
---@field TowerBlurEnd_Alpha_89AA48324632797E70678EB3A15A6FBD float
---@field TowerBlurEnd__Direction_89AA48324632797E70678EB3A15A6FBD ETimelineDirection::Type
---@field TowerBlurEnd UTimelineComponent
---@field TowerBlurStart_Alpha_22E4212B42C372D23934ACBDDA0727EF float
---@field TowerBlurStart__Direction_22E4212B42C372D23934ACBDDA0727EF ETimelineDirection::Type
---@field TowerBlurStart UTimelineComponent
---@field ZerOutControlRotationTimeline_Alpha_D375F77F4C7617FBF2564CA46735069C float
---@field ZerOutControlRotationTimeline__Direction_D375F77F4C7617FBF2564CA46735069C ETimelineDirection::Type
---@field ZerOutControlRotationTimeline UTimelineComponent
---@field RestoreMeshLocationTimeline_Alpha_516144544DE117D4E4F87D8551E834BB float
---@field RestoreMeshLocationTimeline__Direction_516144544DE117D4E4F87D8551E834BB ETimelineDirection::Type
---@field RestoreMeshLocationTimeline UTimelineComponent
---@field WakeupBlurShortEnd_Alpha_B47C1E4B43C2503E35DE9084361F2355 float
---@field WakeupBlurShortEnd__Direction_B47C1E4B43C2503E35DE9084361F2355 ETimelineDirection::Type
---@field WakeupBlurShortEnd UTimelineComponent
---@field WakeupBlurShort_Alpha_22BAA3CF48C66BA50B34CFBF5F2B7BD7 float
---@field WakeupBlurShort__Direction_22BAA3CF48C66BA50B34CFBF5F2B7BD7 ETimelineDirection::Type
---@field WakeupBlurShort UTimelineComponent
---@field BlurInOutTimeline_EaseInOut_35501A86483E8467D59135808E04ACC6 float
---@field BlurInOutTimeline__Direction_35501A86483E8467D59135808E04ACC6 ETimelineDirection::Type
---@field BlurInOutTimeline UTimelineComponent
---@field EaseInOutAperture_EaseInOut_BAB28437411844EBB497F3AB2B77AEB9 float
---@field EaseInOutAperture__Direction_BAB28437411844EBB497F3AB2B77AEB9 ETimelineDirection::Type
---@field EaseInOutAperture UTimelineComponent
---@field EaseInOutFocal_EaseInOut_DAFB946D491BE5BCA4BC899A495CA102 float
---@field EaseInOutFocal__Direction_DAFB946D491BE5BCA4BC899A495CA102 ETimelineDirection::Type
---@field EaseInOutFocal UTimelineComponent
---@field WakeupBlurEndTimeline_Alpha_ECBE328E40AABA69D3A9E7B1CA22A3A0 float
---@field WakeupBlurEndTimeline__Direction_ECBE328E40AABA69D3A9E7B1CA22A3A0 ETimelineDirection::Type
---@field WakeupBlurEndTimeline UTimelineComponent
---@field WakeupBlurTimeline_Alpha_6414FAC845611AEE23521A8A10FC6A3A float
---@field WakeupBlurTimeline__Direction_6414FAC845611AEE23521A8A10FC6A3A ETimelineDirection::Type
---@field WakeupBlurTimeline UTimelineComponent
---@field FadeWhiteTimeline_Alpha_8B4D637A4907C17615C38B8DE639D12D float
---@field FadeWhiteTimeline__Direction_8B4D637A4907C17615C38B8DE639D12D ETimelineDirection::Type
---@field FadeWhiteTimeline UTimelineComponent
---@field BlurEndTimeline_Alpha_C8BF843E46F25F2F04761FAE3449AF86 float
---@field BlurEndTimeline__Direction_C8BF843E46F25F2F04761FAE3449AF86 ETimelineDirection::Type
---@field BlurEndTimeline UTimelineComponent
---@field BlurTimeline_Alpha_3C0A53E54200E82DA24CBC9F1803EFF7 float
---@field BlurTimeline__Direction_3C0A53E54200E82DA24CBC9F1803EFF7 ETimelineDirection::Type
---@field BlurTimeline UTimelineComponent
---@field ReflectionTimeline_Acc_6D54D11142CB02D8E086A5B87291595A float
---@field ReflectionTimeline__Direction_6D54D11142CB02D8E086A5B87291595A ETimelineDirection::Type
---@field ReflectionTimeline UTimelineComponent
---@field ReturnControlRotationTimeline_NewTrack_0_628CB1434409B22AE3D397B68BB6EB33 float
---@field ReturnControlRotationTimeline__Direction_628CB1434409B22AE3D397B68BB6EB33 ETimelineDirection::Type
---@field ReturnControlRotationTimeline UTimelineComponent
---@field BlurVisionTimeline_NewTrack_0_A98EFC88489027FFBF4245B4386722DF float
---@field BlurVisionTimeline__Direction_A98EFC88489027FFBF4245B4386722DF ETimelineDirection::Type
---@field BlurVisionTimeline UTimelineComponent
---@field ReAttachGameplayCameraTimeline_Alpha_6436C8A6483768F987D0E6A3DC26CFF5 float
---@field ReAttachGameplayCameraTimeline__Direction_6436C8A6483768F987D0E6A3DC26CFF5 ETimelineDirection::Type
---@field ReAttachGameplayCameraTimeline UTimelineComponent
---@field Zoom_NewTrack_0_AF6611D74F30DB43983F1FBD16B504E4 float
---@field Zoom__Direction_AF6611D74F30DB43983F1FBD16B504E4 ETimelineDirection::Type
---@field Zoom UTimelineComponent
---@field EnvBlendTimeline_NewTrack_0_FEE99DD54ABCF26ED48FDBAF313970B0 float
---@field EnvBlendTimeline__Direction_FEE99DD54ABCF26ED48FDBAF313970B0 ETimelineDirection::Type
---@field EnvBlendTimeline UTimelineComponent
---@field BaseLookUpRate float
---@field BaseTurnRate float
---@field DisableMovement boolean
---@field InputDeadzoneInner float
---@field InputDeadzoneOuter float
---@field InputScale float
---@field CustomHeadBob boolean
---@field TurnRate float
---@field MovingToLocation boolean
---@field DisableHelmetSway boolean
---@field InterpSpeed float
---@field CameraUp boolean
---@field LookUpModifier float
---@field DirectionalLight ADirectionalLight
---@field DirectionalLightIntensity float
---@field Fog AExponentialHeightFog
---@field FogDensity float
---@field PostProcessBlendWeight float
---@field SkyLight ASkyLight
---@field SkylightIntensity float
---@field ReflectionForwardAcc float
---@field ReflectionStrafeAcc float
---@field AllowCameraSway boolean
---@field FM_DirectionalLight ADirectionalLight
---@field FM_DirectionalLightIntensity float
---@field HelmetFadeInDuration float
---@field PostProcessComp UPostProcessComponent
---@field StopMirrorRotation boolean
---@field CapsuleHalfHeight float
---@field StairTrackActive boolean
---@field StairTrackActiveGoingUp boolean
---@field InteractedObject AActor
---@field BaseFOV float
---@field BackwardsAcc float
---@field DisableLooking boolean
---@field RestrictedPitchMin float
---@field RestrictedPitchMax float
---@field RestrictedYawMin float
---@field RestrictedYawMax float
---@field UnrestrictedPitchMin float
---@field UnrestrictedPitchMax float
---@field IsRestricted boolean
---@field InitialRotationBeforeRestriction FRotator
---@field BaseTurnRate_Strained float
---@field BaseTurnRate_Normal float
---@field CameraRight boolean
---@field LookRightModifier float
---@field TMP_exitintro FBP_FirstPersonPlayerCharacter_CTMP_exitintro
---@field MainSkeletalMesh USkeletalMesh
---@field HeadlessSkeletalMesh USkeletalMesh
---@field PostProcess_Bloom float
---@field PostProcess_Vignette float
---@field SpeedMultiplier float
---@field ZoomLevel float
---@field HeadlessMode boolean
---@field DebugSpeedMultiplier float
---@field BaseWalkSpeed float
---@field CameraMovementCurrent FVector
---@field CameraMovementTarget FVector
---@field ReAttachCameraStartLocation FVector
---@field ReAttachCameraStartRotation FRotator
---@field ArmsVisibleMode boolean
---@field CameraLocationCurrent FVector
---@field CameraLocationTarget FVector
---@field CameraLocationFirst boolean
---@field CameraInterpModeEnabled boolean
---@field DefaultCameraOffset FVector
---@field RemoveCameraShake boolean
---@field hasHeldItem boolean
---@field HeldItem AActor
---@field isPlayerAlive boolean
---@field LocalFPActiveevent UAkAudioEvent
---@field LocalFPInactiveEvent UAkAudioEvent
---@field AnimationVelocity FVector
---@field ActiveInputForward float
---@field ActiveInputRight float
---@field DefaultPostProc FPostProcessSettings
---@field OnFadeOutWhiteComplete FBP_FirstPersonPlayerCharacter_COnFadeOutWhiteComplete
---@field OnFadeOutBlackComplete FBP_FirstPersonPlayerCharacter_COnFadeOutBlackComplete
---@field OnCutToWhiteComplete FBP_FirstPersonPlayerCharacter_COnCutToWhiteComplete
---@field OnCutToBlackComplete FBP_FirstPersonPlayerCharacter_COnCutToBlackComplete
---@field CanZoom boolean
---@field ZoomManuallyDisabled boolean
---@field ObjectEnabled boolean
---@field CurrentMediaPlayer UWBP_MediaPlayer_C
---@field StartingAperture float
---@field StartingFocal float
---@field ZoomActive boolean
---@field DefaultMeshLocation FVector
---@field CurrentMeshLocation FVector
---@field ReattachStartControlRotation FRotator
---@field RestoreViewMode boolean
ABP_FirstPersonPlayerCharacter_C = {}

function ABP_FirstPersonPlayerCharacter_C:UpdateHelmet() end
---@param FirstPersonCamera UCameraComponent
function ABP_FirstPersonPlayerCharacter_C:GetFirstPersonCamera(FirstPersonCamera) end
---@param Media UBP_MediaData_C
---@param alpha float
---@param Result UWBP_MediaPlayer_C
function ABP_FirstPersonPlayerCharacter_C:PlayMediaWithAlphaNEW(Media, alpha, Result) end
---@param Media UBP_MediaData_C
---@param Result UWBP_MediaPlayer_C
function ABP_FirstPersonPlayerCharacter_C:PlayMediaNEW(Media, Result) end
---@param Result ABP_FirstPersonPlayerView_C
function ABP_FirstPersonPlayerCharacter_C:GetViewActorNEW(Result) end
---@param Result UCameraComponent
function ABP_FirstPersonPlayerCharacter_C:GetAnimationCamera(Result) end
---@param Result AActor
function ABP_FirstPersonPlayerCharacter_C:GetInteractedObject(Result) end
---@param Result boolean
function ABP_FirstPersonPlayerCharacter_C:IsMovingToLocation(Result) end
---@param ShowTextBox boolean
function ABP_FirstPersonPlayerCharacter_C:AllowContinuousShowTextBox(ShowTextBox) end
---@param Result boolean
function ABP_FirstPersonPlayerCharacter_C:IsAtGameplayCamera(Result) end
---@param NewEnabled boolean
---@param KeepWorld boolean
---@param ReturnAnimation boolean
function ABP_FirstPersonPlayerCharacter_C:StrictCinematicMode(NewEnabled, KeepWorld, ReturnAnimation) end
function ABP_FirstPersonPlayerCharacter_C:TickZoom() end
function ABP_FirstPersonPlayerCharacter_C:Audio_UpdateHealthState() end
function ABP_FirstPersonPlayerCharacter_C:InitializeMirrorAsset() end
---@param MediaData UBP_MediaData_C
function ABP_FirstPersonPlayerCharacter_C:OpenMedia(MediaData) end
function ABP_FirstPersonPlayerCharacter_C:SecureMediaPlayer() end
---@param Result boolean
function ABP_FirstPersonPlayerCharacter_C:IsMediaPlaying(Result) end
---@param DeltaSeconds float
function ABP_FirstPersonPlayerCharacter_C:TickCameraShake(DeltaSeconds) end
---@param NewVelocity FVector
function ABP_FirstPersonPlayerCharacter_C:SetAnimationVelocity(NewVelocity) end
---@param Result FVector
function ABP_FirstPersonPlayerCharacter_C:GetAnimationVelocity(Result) end
---@param Result boolean
function ABP_FirstPersonPlayerCharacter_C:IsMeshVisibleInPlayMode(Result) end
---@param NewEnabled boolean
ABP_FirstPersonPlayerCharacter_C['Set Play Mode Enabled'] = function(NewEnabled) end
function ABP_FirstPersonPlayerCharacter_C:UpdateMeshMode() end
---@param Result boolean
function ABP_FirstPersonPlayerCharacter_C:IsZoomAllowed(Result) end
---@return UCameraComponent
function ABP_FirstPersonPlayerCharacter_C:GetPlayerCamera() end
---@param Enabled boolean
function ABP_FirstPersonPlayerCharacter_C:SetCameraInterpModeEnabled(Enabled) end
---@param Active boolean
function ABP_FirstPersonPlayerCharacter_C:SetArmsVisibleMode(Active) end
---@param Result boolean
function ABP_FirstPersonPlayerCharacter_C:IsUsingGameplayCamera(Result) end
---@param Result boolean
function ABP_FirstPersonPlayerCharacter_C:TryContinuousEnd(Result) end
---@param Result boolean
function ABP_FirstPersonPlayerCharacter_C:TryContinuousContinue(Result) end
---@param Result boolean
function ABP_FirstPersonPlayerCharacter_C:IsFreeCamera(Result) end
---@param NewCameraMovement FVector
function ABP_FirstPersonPlayerCharacter_C:SetCameraMovement(NewCameraMovement) end
---@param DeltaSeconds float
function ABP_FirstPersonPlayerCharacter_C:TickCameraMovement(DeltaSeconds) end
---@param KeepWorld boolean
---@param ReturnAnimation boolean
function ABP_FirstPersonPlayerCharacter_C:ReAttachGameplayCamera(KeepWorld, ReturnAnimation) end
---@param Enabled boolean
function ABP_FirstPersonPlayerCharacter_C:SetUseControllerRotation(Enabled) end
---@param Active boolean
function ABP_FirstPersonPlayerCharacter_C:SetHeadlessMode(Active) end
function ABP_FirstPersonPlayerCharacter_C:PlaySound_WalkStop() end
---@param toggle boolean
function ABP_FirstPersonPlayerCharacter_C:UseHeadlessAsset(toggle) end
function ABP_FirstPersonPlayerCharacter_C:RestrictedCamera_Exit() end
---@param PitchMin float
---@param PitchMax float
---@param YawMin float
---@param YawMax float
function ABP_FirstPersonPlayerCharacter_C:RestrictedCamera_Enter(PitchMin, PitchMax, YawMin, YawMax) end
---@param Result boolean
function ABP_FirstPersonPlayerCharacter_C:IsLookingDisabledInternal(Result) end
---@param DeltaSeconds float
---@param Result float
function ABP_FirstPersonPlayerCharacter_C:TickLocomotionModifier(DeltaSeconds, Result) end
---@param Result boolean
function ABP_FirstPersonPlayerCharacter_C:IsMovementDisabledInternal(Result) end
---@param alpha float
function ABP_FirstPersonPlayerCharacter_C:SetMediaAlpha(alpha) end
---@param MediaData UBP_MediaData_C
---@param alpha float
---@param Result UWBP_MediaPlayer_C
function ABP_FirstPersonPlayerCharacter_C:PlayMediaWithAlpha(MediaData, alpha, Result) end
---@param MediaData UBP_MediaData_C
---@param MediaPlayer UWBP_MediaPlayer_C
function ABP_FirstPersonPlayerCharacter_C:PlayMedia(MediaData, MediaPlayer) end
---@param Result AEnvironmentWorld
function ABP_FirstPersonPlayerCharacter_C:GetEnvWorld(Result) end
---@param Tag FName
---@param Result AActor
function ABP_FirstPersonPlayerCharacter_C:GetEnvActor(Tag, Result) end
---@param NewEnabled boolean
---@param ReturnAnimation boolean
---@param SnapToTarget boolean
function ABP_FirstPersonPlayerCharacter_C:SetCinematicCameraEnabled(NewEnabled, ReturnAnimation, SnapToTarget) end
---@param Result ABP_FirstPersonPlayerView_C
function ABP_FirstPersonPlayerCharacter_C:GetViewActor(Result) end
function ABP_FirstPersonPlayerCharacter_C:UserConstructionScript() end
function ABP_FirstPersonPlayerCharacter_C:BlurEndTimeline__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:BlurEndTimeline__UpdateFunc() end
function ABP_FirstPersonPlayerCharacter_C:FadeWhiteTimeline__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:FadeWhiteTimeline__UpdateFunc() end
function ABP_FirstPersonPlayerCharacter_C:BlurVisionTimeline__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:BlurVisionTimeline__UpdateFunc() end
function ABP_FirstPersonPlayerCharacter_C:WakeupBlurTimeline__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:WakeupBlurTimeline__UpdateFunc() end
function ABP_FirstPersonPlayerCharacter_C:WakeupBlurEndTimeline__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:WakeupBlurEndTimeline__UpdateFunc() end
function ABP_FirstPersonPlayerCharacter_C:EaseInOutAperture__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:EaseInOutAperture__UpdateFunc() end
function ABP_FirstPersonPlayerCharacter_C:EaseInOutFocal__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:EaseInOutFocal__UpdateFunc() end
function ABP_FirstPersonPlayerCharacter_C:BlurInOutTimeline__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:BlurInOutTimeline__UpdateFunc() end
function ABP_FirstPersonPlayerCharacter_C:WakeupBlurShort__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:WakeupBlurShort__UpdateFunc() end
function ABP_FirstPersonPlayerCharacter_C:WakeupBlurShortEnd__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:WakeupBlurShortEnd__UpdateFunc() end
function ABP_FirstPersonPlayerCharacter_C:TowerBlurStart__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:TowerBlurStart__UpdateFunc() end
function ABP_FirstPersonPlayerCharacter_C:TowerBlurEnd__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:TowerBlurEnd__UpdateFunc() end
function ABP_FirstPersonPlayerCharacter_C:Timeline_0__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:Timeline_0__UpdateFunc() end
function ABP_FirstPersonPlayerCharacter_C:Zoom__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:Zoom__UpdateFunc() end
function ABP_FirstPersonPlayerCharacter_C:BlurTimeline__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:BlurTimeline__UpdateFunc() end
function ABP_FirstPersonPlayerCharacter_C:EnvBlendTimeline__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:EnvBlendTimeline__UpdateFunc() end
function ABP_FirstPersonPlayerCharacter_C:ReflectionTimeline__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:ReflectionTimeline__UpdateFunc() end
function ABP_FirstPersonPlayerCharacter_C:ReAttachGameplayCameraTimeline__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:ReAttachGameplayCameraTimeline__UpdateFunc() end
function ABP_FirstPersonPlayerCharacter_C:ReturnControlRotationTimeline__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:ReturnControlRotationTimeline__UpdateFunc() end
function ABP_FirstPersonPlayerCharacter_C:RestoreMeshLocationTimeline__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:RestoreMeshLocationTimeline__UpdateFunc() end
function ABP_FirstPersonPlayerCharacter_C:ZerOutControlRotationTimeline__FinishedFunc() end
function ABP_FirstPersonPlayerCharacter_C:ZerOutControlRotationTimeline__UpdateFunc() end
---@param Key FKey
function ABP_FirstPersonPlayerCharacter_C:InpActEvt_Zoom_K2Node_InputActionEvent_5(Key) end
---@param Key FKey
function ABP_FirstPersonPlayerCharacter_C:InpActEvt_Zoom_K2Node_InputActionEvent_4(Key) end
---@param Key FKey
function ABP_FirstPersonPlayerCharacter_C:InpActEvt_Interact_K2Node_InputActionEvent_3(Key) end
---@param Key FKey
function ABP_FirstPersonPlayerCharacter_C:InpActEvt_CloseMenu_K2Node_InputActionEvent_2(Key) end
---@param Key FKey
function ABP_FirstPersonPlayerCharacter_C:InpActEvt_FirstPersonSpeedUp_K2Node_InputActionEvent_1(Key) end
---@param Key FKey
function ABP_FirstPersonPlayerCharacter_C:InpActEvt_MenuToggleReadView_K2Node_InputActionEvent_0(Key) end
---@param WrittenAchievementName FName
---@param WrittenProgress float
---@param WrittenUserTag int32
function ABP_FirstPersonPlayerCharacter_C:OnFailure_ED1E29E1467F70E34DEFEBA5988040B0(WrittenAchievementName, WrittenProgress, WrittenUserTag) end
---@param WrittenAchievementName FName
---@param WrittenProgress float
---@param WrittenUserTag int32
function ABP_FirstPersonPlayerCharacter_C:OnSuccess_ED1E29E1467F70E34DEFEBA5988040B0(WrittenAchievementName, WrittenProgress, WrittenUserTag) end
---@param WrittenAchievementName FName
---@param WrittenProgress float
---@param WrittenUserTag int32
function ABP_FirstPersonPlayerCharacter_C:OnFailure_45FA4166473D43E03A26EDA8822B3F16(WrittenAchievementName, WrittenProgress, WrittenUserTag) end
---@param WrittenAchievementName FName
---@param WrittenProgress float
---@param WrittenUserTag int32
function ABP_FirstPersonPlayerCharacter_C:OnSuccess_45FA4166473D43E03A26EDA8822B3F16(WrittenAchievementName, WrittenProgress, WrittenUserTag) end
function ABP_FirstPersonPlayerCharacter_C:ScreenEffect_SimpleFadeFromWhite() end
function ABP_FirstPersonPlayerCharacter_C:ScreenEffect_SimpleFadeToWhite() end
function ABP_FirstPersonPlayerCharacter_C:ScreenEffect_FadeOutWhite() end
function ABP_FirstPersonPlayerCharacter_C:ScreenEffect_FadeInWhite() end
function ABP_FirstPersonPlayerCharacter_C:Internal_CutFromWhite() end
function ABP_FirstPersonPlayerCharacter_C:Internal_CutToWhite() end
function ABP_FirstPersonPlayerCharacter_C:ScreenEffect_CutFromBlack() end
function ABP_FirstPersonPlayerCharacter_C:ScreenEffect_CutToBlack() end
function ABP_FirstPersonPlayerCharacter_C:BlurVision() end
---@param duration float
function ABP_FirstPersonPlayerCharacter_C:ScreenEffect_FadeFromBlack(duration) end
---@param duration float
function ABP_FirstPersonPlayerCharacter_C:ScreenEffect_FadeToBlack(duration) end
function ABP_FirstPersonPlayerCharacter_C:WrapContinuousShowTextBox() end
---@param NewEnabled boolean
function ABP_FirstPersonPlayerCharacter_C:FPSetInteractEnabled(NewEnabled) end
---@param LanguageCode FName
function ABP_FirstPersonPlayerCharacter_C:ChangeLanguage(LanguageCode) end
function ABP_FirstPersonPlayerCharacter_C:ContinueMainInteractive() end
---@param AssignedNumber int32
function ABP_FirstPersonPlayerCharacter_C:AnimNotify(AssignedNumber) end
---@param Component UActorComponent
function ABP_FirstPersonPlayerCharacter_C:Overlap(Component) end
---@param Component UActorComponent
function ABP_FirstPersonPlayerCharacter_C:Interact(Component) end
---@param NotifyInt int32
function ABP_FirstPersonPlayerCharacter_C:NotifyLevel(NotifyInt) end
function ABP_FirstPersonPlayerCharacter_C:ScreenEffect_WakeupBlur() end
---@param TransitionInt int32
function ABP_FirstPersonPlayerCharacter_C:ToggleTransition(TransitionInt) end
function ABP_FirstPersonPlayerCharacter_C:StartDOF() end
---@param ApertureValue float
---@param TimeToLerp float
function ABP_FirstPersonPlayerCharacter_C:ApertureLerp(ApertureValue, TimeToLerp) end
---@param FocalValue float
---@param TimeToLerp float
function ABP_FirstPersonPlayerCharacter_C:FocalLerp(FocalValue, TimeToLerp) end
function ABP_FirstPersonPlayerCharacter_C:EndDOF() end
---@param Time float
function ABP_FirstPersonPlayerCharacter_C:BlurInOut(Time) end
function ABP_FirstPersonPlayerCharacter_C:ScreenEffect_WakeupBlurShort() end
function ABP_FirstPersonPlayerCharacter_C:ScreenEffect_WakeupBlurTower() end
function ABP_FirstPersonPlayerCharacter_C:ConstraintSizeForPC() end
---@param AxisValue float
function ABP_FirstPersonPlayerCharacter_C:InpAxisEvt_MoveForward_K2Node_InputAxisEvent_181(AxisValue) end
---@param AxisValue float
function ABP_FirstPersonPlayerCharacter_C:InpAxisEvt_MoveRight_K2Node_InputAxisEvent_192(AxisValue) end
---@param AxisValue float
function ABP_FirstPersonPlayerCharacter_C:InpAxisEvt_TurnRate_K2Node_InputAxisEvent_34(AxisValue) end
---@param AxisValue float
function ABP_FirstPersonPlayerCharacter_C:InpAxisEvt_LookUpRate_K2Node_InputAxisEvent_62(AxisValue) end
function ABP_FirstPersonPlayerCharacter_C:TurnRateCheck() end
function ABP_FirstPersonPlayerCharacter_C:ScreenEffect_BlurVision() end
function ABP_FirstPersonPlayerCharacter_C:UseHeldItem() end
function ABP_FirstPersonPlayerCharacter_C:ZoomEnd() end
function ABP_FirstPersonPlayerCharacter_C:MenuToggleReadView() end
---@param AxisValue float
function ABP_FirstPersonPlayerCharacter_C:InpAxisEvt_MouseX_K2Node_InputAxisEvent_1(AxisValue) end
---@param AxisValue float
function ABP_FirstPersonPlayerCharacter_C:InpAxisEvt_MouseY_K2Node_InputAxisEvent_3(AxisValue) end
---@param TrophyName FName
---@param Progress float
function ABP_FirstPersonPlayerCharacter_C:UnlockTrophy(TrophyName, Progress) end
function ABP_FirstPersonPlayerCharacter_C:BlendOutEnvWorld() end
function ABP_FirstPersonPlayerCharacter_C:BlendInEnvWorld() end
function ABP_FirstPersonPlayerCharacter_C:SetTransitionDirectionalLight() end
---@param DeltaSeconds float
function ABP_FirstPersonPlayerCharacter_C:ReceiveTick(DeltaSeconds) end
---@param toggle boolean
---@param Actor AActor
---@param Component UStaticMeshComponent
function ABP_FirstPersonPlayerCharacter_C:DoFTracking(toggle, Actor, Component) end
function ABP_FirstPersonPlayerCharacter_C:ReceiveBeginPlay() end
---@param On boolean
function ABP_FirstPersonPlayerCharacter_C:ToggleMirrorLook(On) end
---@param bNewVisible boolean
function ABP_FirstPersonPlayerCharacter_C:SetVisibility(bNewVisible) end
function ABP_FirstPersonPlayerCharacter_C:ReAttachGameplayCameraAnimation() end
function ABP_FirstPersonPlayerCharacter_C:ReturnViewToCenter() end
function ABP_FirstPersonPlayerCharacter_C:ReturnViewToCenter_Fast() end
---@param duration float
function ABP_FirstPersonPlayerCharacter_C:ReturnControlRotationToCenter(duration) end
function ABP_FirstPersonPlayerCharacter_C:ReceiveBeginPossessed() end
function ABP_FirstPersonPlayerCharacter_C:ReceiveEndPossessed() end
function ABP_FirstPersonPlayerCharacter_C:BP_ActivateFirstPerson() end
function ABP_FirstPersonPlayerCharacter_C:BP_DeactivateFirstPerson() end
---@param TrackerComp UReflectionTrackerComponent
---@param ReflectionComp UHMQReflectionComponent
function ABP_FirstPersonPlayerCharacter_C:BndEvt__ReflectionTracker_K2Node_ComponentBoundEvent_0_ReflectionTrackerExitSignature__DelegateSignature(TrackerComp, ReflectionComp) end
---@param TrackerComp UReflectionTrackerComponent
---@param ReflectionComp UHMQReflectionComponent
---@param bFirst boolean
function ABP_FirstPersonPlayerCharacter_C:BndEvt__ReflectionTracker_K2Node_ComponentBoundEvent_1_ReflectionTrackerEnterSignature__DelegateSignature(TrackerComp, ReflectionComp, bFirst) end
function ABP_FirstPersonPlayerCharacter_C:EnableWorldInteraction() end
---@param CurrentController AController
function ABP_FirstPersonPlayerCharacter_C:ReceiveRestarted(CurrentController) end
function ABP_FirstPersonPlayerCharacter_C:EventOnPlayerDeath() end
function ABP_FirstPersonPlayerCharacter_C:OnBeginPossessed() end
function ABP_FirstPersonPlayerCharacter_C:OnEndPossessed() end
---@param NewEnabled boolean
function ABP_FirstPersonPlayerCharacter_C:SetBallKickerEnabled(NewEnabled) end
---@param NewMovingToLocation boolean
function ABP_FirstPersonPlayerCharacter_C:SetMovingToLocation(NewMovingToLocation) end
---@param NewInteractedObject AActor
function ABP_FirstPersonPlayerCharacter_C:SetInteractedObject(NewInteractedObject) end
---@param NewActive boolean
function ABP_FirstPersonPlayerCharacter_C:SetArmsVisibleModeNEW(NewActive) end
---@param NewActive boolean
function ABP_FirstPersonPlayerCharacter_C:SetHeadlessModeNEW(NewActive) end
---@param NewEnabled boolean
function ABP_FirstPersonPlayerCharacter_C:SetPlayModeEnabledNEW(NewEnabled) end
---@param toggle boolean
---@param Actor AActor
---@param Component UStaticMeshComponent
function ABP_FirstPersonPlayerCharacter_C:DepthOfFieldTracking(toggle, Actor, Component) end
function ABP_FirstPersonPlayerCharacter_C:RestrictedCameraExitNEW() end
---@param PitchMin float
---@param PitchMax float
---@param YawMin float
---@param YawMax float
function ABP_FirstPersonPlayerCharacter_C:RestrictedCameraEnterNEW(PitchMin, PitchMax, YawMin, YawMax) end
---@param NewValue float
function ABP_FirstPersonPlayerCharacter_C:SetSpeedMultiplier(NewValue) end
---@param NewEnabled boolean
function ABP_FirstPersonPlayerCharacter_C:SetZoomEnabled(NewEnabled) end
---@param NewVelocity FVector
function ABP_FirstPersonPlayerCharacter_C:SetAnimationVelocityNEW(NewVelocity) end
---@param KeepWorld boolean
---@param ReturnAnimation boolean
function ABP_FirstPersonPlayerCharacter_C:ReAttachGameplayCameraNEW(KeepWorld, ReturnAnimation) end
---@param duration float
function ABP_FirstPersonPlayerCharacter_C:RestoreMeshLocation(duration) end
---@param duration float
function ABP_FirstPersonPlayerCharacter_C:RestoreMeshLocationNEW(duration) end
function ABP_FirstPersonPlayerCharacter_C:DevResetControlRotation() end
function ABP_FirstPersonPlayerCharacter_C:ZeroControlRotationRoll() end
---@param alpha float
function ABP_FirstPersonPlayerCharacter_C:SetMediaAlphaNEW(alpha) end
---@param value FString
function ABP_FirstPersonPlayerCharacter_C:ReceiveGenericSignal(value) end
---@param bNewEnabled boolean
function ABP_FirstPersonPlayerCharacter_C:ReceiveSetPlayModeActive(bNewEnabled) end
function ABP_FirstPersonPlayerCharacter_C:RestoreViewInteractionMode() end
function ABP_FirstPersonPlayerCharacter_C:ClearPendingViewInteractionMode() end
function ABP_FirstPersonPlayerCharacter_C:UpdateZoomLevel() end
function ABP_FirstPersonPlayerCharacter_C:BP_HUDMenuOpened() end
---@param EntryPoint int32
function ABP_FirstPersonPlayerCharacter_C:ExecuteUbergraph_BP_FirstPersonPlayerCharacter(EntryPoint) end
function ABP_FirstPersonPlayerCharacter_C:OnCutToBlackComplete__DelegateSignature() end
function ABP_FirstPersonPlayerCharacter_C:OnCutToWhiteComplete__DelegateSignature() end
function ABP_FirstPersonPlayerCharacter_C:OnFadeOutBlackComplete__DelegateSignature() end
function ABP_FirstPersonPlayerCharacter_C:OnFadeOutWhiteComplete__DelegateSignature() end
function ABP_FirstPersonPlayerCharacter_C:TMP_exitintro__DelegateSignature() end


