---@meta

---@class ABP_RabbitHoleEntrance_C : AHMQActor
---@field UberGraphFrame FPointerToUberGraphFrame
---@field RabbitHoleFog UChildActorComponent
---@field BP_DropVolume UChildActorComponent
---@field HMQActorActivator UHMQActorActivatorComponent
---@field DespawnableActor UDespawnableActorComponent
---@field Cube3 UStaticMeshComponent
---@field Wall_Houdini_BP7 UChildActorComponent
---@field Wall_Houdini_BP6 UChildActorComponent
---@field Wall_Houdini_BP5 UChildActorComponent
---@field Wall_Houdini_BP4 UChildActorComponent
---@field EffectMarker USceneComponent
---@field LevelGenStreamingFocus ULevelGenStreamingFocus
---@field Arrow_Forward UArrowComponent
---@field Wall_Houdini_BP3 UChildActorComponent
---@field Wall_Houdini_BP2 UChildActorComponent
---@field Wall_Houdini_BP1 UChildActorComponent
---@field Wall_Houdini_BP UChildActorComponent
---@field StaticMesh9 UStaticMeshComponent
---@field StaticMesh8 UStaticMeshComponent
---@field FrontWall_Houdini_BP UChildActorComponent
---@field Audio_FloorEmitter UAkComponent
---@field NGParticle UNGParticleComponent
---@field AttractionMarker USceneComponent
---@field ReturnMarker USceneComponent
---@field Floor_Houdini_BP UChildActorComponent
---@field BPC_Secret UBPC_Secret_C
---@field BPC_RabbitHoleSelector UBPC_RabbitHoleSelector_C
---@field Box1 UBoxComponent
---@field Root USceneComponent
---@field Cube2 UStaticMeshComponent
---@field Cube1 UStaticMeshComponent
---@field Cube UStaticMeshComponent
---@field StaticMesh21 UStaticMeshComponent
---@field StaticMesh20 UStaticMeshComponent
---@field StaticMesh19 UStaticMeshComponent
---@field StaticMesh18 UStaticMeshComponent
---@field StaticMesh17 UStaticMeshComponent
---@field StaticMesh16 UStaticMeshComponent
---@field StaticMesh15 UStaticMeshComponent
---@field StaticMesh10 UStaticMeshComponent
---@field StaticMesh4 UStaticMeshComponent
---@field StaticMesh1 UStaticMeshComponent
---@field Box_Activate UBoxComponent
---@field StaticMesh_WeirdAttractor UStaticMeshComponent
---@field StaticMesh6 UStaticMeshComponent
---@field StaticMesh5 UStaticMeshComponent
---@field SM_DarkForestTreeGiant_Roots_A1 UStaticMeshComponent
---@field PointLight UPointLightComponent
---@field StaticMesh3 UStaticMeshComponent
---@field StaticMesh2 UStaticMeshComponent
---@field StaticMesh UStaticMeshComponent
---@field SM_DarkForestTreeGiant_Roots_A UStaticMeshComponent
---@field Statue UStaticMeshComponent
---@field Camera UCameraComponent
---@field Box UBoxComponent
---@field Scene USceneComponent
---@field CurrentlyTeleportingPlayerCharacter APlayerCharacter
---@field SelectedTarget ABP_RabbitholeTarget_C
---@field Complete boolean
---@field debug boolean
---@field MoneyDelay float
---@field FadeDuration float
---@field FloorVersion boolean
---@field BasicMeshes TArray<UStaticMeshComponent>
---@field HoudiniMeshes TArray<UChildActorComponent>
---@field StartNGPLeaves ABP_RabbitholeLeaves_C
---@field Disabled boolean
---@field LureActive boolean
---@field Prepared boolean
---@field DebugTarget TSoftObjectPtr<ABP_RabbitholeTarget_C>
---@field bFloorbroken boolean
---@field SelectedTargetHoleGUID FGuid
---@field GEHandles TArray<FTouristGameplayEffectHandle>
---@field CriticalTransitionName FName
ABP_RabbitHoleEntrance_C = {}

function ABP_RabbitHoleEntrance_C:HandleSusRes() end
function ABP_RabbitHoleEntrance_C:ReleaseChosen() end
---@param PlayerCharacter APlayerCharacter
---@param PlayerController APlayerController
function ABP_RabbitHoleEntrance_C:TeleportPlayerBackToReturnMarker(PlayerCharacter, PlayerController) end
function ABP_RabbitHoleEntrance_C:UpdateFloorVersion_Internal() end
function ABP_RabbitHoleEntrance_C:DestroyLeaves() end
function ABP_RabbitHoleEntrance_C:InitialiseRabbithole() end
function ABP_RabbitHoleEntrance_C:UpdateDebugCollisions_Internal() end
function ABP_RabbitHoleEntrance_C:SpawnLeaves() end
function ABP_RabbitHoleEntrance_C:UpdateRabbitholeVisuals_Internal() end
function ABP_RabbitHoleEntrance_C:HandleRabbitholeCompleted() end
---@param Result ABP_RabbitholeTarget_C
function ABP_RabbitHoleEntrance_C:TryGetRabbitholeTarget(Result) end
function ABP_RabbitHoleEntrance_C:DisableRabbitHole() end
function ABP_RabbitHoleEntrance_C:HideLure() end
---@param Player APlayerCharacter
function ABP_RabbitHoleEntrance_C:PreparePlayer(Player) end
---@param PlayerCharacter APlayerCharacter
function ABP_RabbitHoleEntrance_C:TeleportPlayerToTarget(PlayerCharacter) end
function ABP_RabbitHoleEntrance_C:BreakFloor() end
function ABP_RabbitHoleEntrance_C:UserConstructionScript() end
function ABP_RabbitHoleEntrance_C:ReceiveBeginPlay() end
---@param OverlappedComponent UPrimitiveComponent
---@param OtherActor AActor
---@param OtherComp UPrimitiveComponent
---@param OtherBodyIndex int32
---@param bFromSweep boolean
---@param SweepResult FHitResult
function ABP_RabbitHoleEntrance_C:BndEvt__Box_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature(OverlappedComponent, OtherActor, OtherComp, OtherBodyIndex, bFromSweep, SweepResult) end
function ABP_RabbitHoleEntrance_C:PrepareRabbitHole() end
---@param OverlappedComponent UPrimitiveComponent
---@param OtherActor AActor
---@param OtherComp UPrimitiveComponent
---@param OtherBodyIndex int32
---@param bFromSweep boolean
---@param SweepResult FHitResult
function ABP_RabbitHoleEntrance_C:BndEvt__Activate_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature(OverlappedComponent, OtherActor, OtherComp, OtherBodyIndex, bFromSweep, SweepResult) end
---@param OverlappingActor AActor
function ABP_RabbitHoleEntrance_C:Multicast_TransitionTarget(OverlappingActor) end
---@param PlayerCharacter APlayerCharacter
function ABP_RabbitHoleEntrance_C:StartPlayerTransitionToRabbitholeTarget(PlayerCharacter) end
function ABP_RabbitHoleEntrance_C:AllowNewPlayerEntry() end
function ABP_RabbitHoleEntrance_C:FixFloor() end
---@param OverlappedComponent UPrimitiveComponent
---@param OtherActor AActor
---@param OtherComp UPrimitiveComponent
---@param OtherBodyIndex int32
---@param bFromSweep boolean
---@param SweepResult FHitResult
function ABP_RabbitHoleEntrance_C:BndEvt__Box1_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(OverlappedComponent, OtherActor, OtherComp, OtherBodyIndex, bFromSweep, SweepResult) end
---@param OtherActor AActor
function ABP_RabbitHoleEntrance_C:OverlapTransition(OtherActor) end
---@param RabbitHole ABP_RabbitholeTarget_C
function ABP_RabbitHoleEntrance_C:RabbitHoleCompleted(RabbitHole) end
---@param Serializer TScriptInterface<IDespawnableActorSerializer>
function ABP_RabbitHoleEntrance_C:BndEvt__DespawnableActor_K2Node_ComponentBoundEvent_4_SerializeState__DelegateSignature(Serializer) end
---@param Actor AActor
function ABP_RabbitHoleEntrance_C:BndEvt__DespawnableActor_K2Node_ComponentBoundEvent_5_DespawnableActorRespawned__DelegateSignature(Actor) end
function ABP_RabbitHoleEntrance_C:DoPlayerFallCameraFade() end
---@param OtherPlayerCharacter APlayerCharacter
function ABP_RabbitHoleEntrance_C:Multicast_DoPlayerFallCameraUnFade(OtherPlayerCharacter) end
function ABP_RabbitHoleEntrance_C:DeactivateStreamer() end
function ABP_RabbitHoleEntrance_C:ActivateStreamer() end
---@param EndPlayReason EEndPlayReason::Type
function ABP_RabbitHoleEntrance_C:ReceiveEndPlay(EndPlayReason) end
---@param Target ABP_RabbitholeTarget_C
function ABP_RabbitHoleEntrance_C:SetSelectedTarget(Target) end
---@param Enable boolean
function ABP_RabbitHoleEntrance_C:HandleCinematicMode(Enable) end
---@param value FString
function ABP_RabbitHoleEntrance_C:ReceiveGenericSignal(value) end
function ABP_RabbitHoleEntrance_C:PopGameplayEffects() end
---@param EntryPoint int32
function ABP_RabbitHoleEntrance_C:ExecuteUbergraph_BP_RabbitHoleEntrance(EntryPoint) end


