---@meta

---@class ABP_StreamLevelTransition_C : AHMQActor
---@field UberGraphFrame FPointerToUberGraphFrame
---@field HMQTrigger UHMQTriggerComponent
---@field Box UBoxComponent
---@field Billboard UBillboardComponent
---@field Root USceneComponent
---@field TransitionEnabled boolean
---@field TransitionOnce boolean
---@field StreamLevel FSoftObjectPath
---@field StreamLevelLocation FVector
---@field StreamLevelTargetPoint ATargetPoint
---@field InitiallyVisible boolean
---@field HideOnComplete boolean
---@field UnloadOnComplete boolean
---@field TeleportPlayerOnStart boolean
---@field TeleportTag FName
---@field TriggerableTag FName
---@field TargetActor AActor
---@field TargetPlayerController APlayerController
---@field ReturnTransform FTransform
---@field TransitionCompleted boolean
---@field LevelLoaded boolean
---@field BoxExtent FVector
---@field StreamingTimer float
---@field OnTransitionComplete FBP_StreamLevelTransition_COnTransitionComplete
---@field Interactable ABP_Interactable_C
---@field OriginalTargetActor AActor
---@field DestroyTargetActor boolean
---@field Handler AActor
---@field HandlerComp UBPC_StreamLevelTransitionHandler_C
---@field ReturnMarker AActor
---@field ReturnTriggerable AActor
---@field StreamLevelPath FString
---@field LoadLevelTimerHandle FTimerHandle
---@field ReturnTriggerableOriginalActor boolean
---@field StreamingCounter int32
---@field StreamingStartTime float
---@field LevelUnloadEnabled boolean
---@field CompletePersistentFlag FName
---@field OnTransitionStart FBP_StreamLevelTransition_COnTransitionStart
---@field State E_StreamLevelTransitionState::Type
---@field ExternalTrigger ABP_PlayerTrigger_C
---@field UnloadTimer float
---@field CompleteTransitionPrepared boolean
ABP_StreamLevelTransition_C = {}

---@param Result boolean
function ABP_StreamLevelTransition_C:IsTriggerableDisabled(Result) end
---@param Result FString
function ABP_StreamLevelTransition_C:GetSpecialLevelBlockerName(Result) end
---@param Result UBPC_StreamLevelTransitionHandler_C
function ABP_StreamLevelTransition_C:GetHandler(Result) end
---@param Result boolean
function ABP_StreamLevelTransition_C:HasOverlappingPlayers(Result) end
function ABP_StreamLevelTransition_C:UpdateInteractableState() end
---@param NewState E_StreamLevelTransitionState::Type
function ABP_StreamLevelTransition_C:SetState(NewState) end
---@param DeltaSeconds float
function ABP_StreamLevelTransition_C:TickState(DeltaSeconds) end
---@param Result E_StreamLevelTransitionState::Type
function ABP_StreamLevelTransition_C:GetState(Result) end
---@param NewInteractable ABP_Interactable_C
function ABP_StreamLevelTransition_C:SetInteractable(NewInteractable) end
---@param DeltaSeconds float
function ABP_StreamLevelTransition_C:TickLoadingLevel(DeltaSeconds) end
---@param NewEnabled boolean
function ABP_StreamLevelTransition_C:SetUnloadStreamingLevelEnabled(NewEnabled) end
---@param Result boolean
function ABP_StreamLevelTransition_C:IsStreamingLevelLoaded(Result) end
function ABP_StreamLevelTransition_C:DestroyTargetActorInternal() end
---@param Location FVector
---@param Rotation FRotator
---@param Result boolean
function ABP_StreamLevelTransition_C:GetStreamLevelTransform(Location, Rotation, Result) end
---@param Actor AActor
---@param Transform FTransform
---@param Marker AActor
function ABP_StreamLevelTransition_C:SetupActorTransform(Actor, Transform, Marker) end
function ABP_StreamLevelTransition_C:ReturnActor() end
function ABP_StreamLevelTransition_C:RecordReturnTransform() end
---@param NewTargetActor AActor
---@param DestroyWhenComplete boolean
function ABP_StreamLevelTransition_C:SetTargetActor(NewTargetActor, DestroyWhenComplete) end
---@param Result AActor
function ABP_StreamLevelTransition_C:GetTargetActor(Result) end
---@param Result APlayerController
function ABP_StreamLevelTransition_C:GetTargetPlayerController(Result) end
---@param NewEnabled boolean
function ABP_StreamLevelTransition_C:SetGenMapElementsEnabled(NewEnabled) end
function ABP_StreamLevelTransition_C:UserConstructionScript() end
---@param Actor AActor
function ABP_StreamLevelTransition_C:ExitTrigger(Actor) end
---@param PlayerController APlayerController
---@param Actor AActor
function ABP_StreamLevelTransition_C:EnterTrigger(PlayerController, Actor) end
function ABP_StreamLevelTransition_C:ReceiveBeginPlay() end
function ABP_StreamLevelTransition_C:CompleteTransition() end
---@param Triggerable AActor
function ABP_StreamLevelTransition_C:ProcessTransition(Triggerable) end
---@param DeltaSeconds float
function ABP_StreamLevelTransition_C:ReceiveTick(DeltaSeconds) end
---@param Marker AActor
function ABP_StreamLevelTransition_C:TeleportPlayer(Marker) end
---@param NewBusy boolean
function ABP_StreamLevelTransition_C:SetInteractionBusy(NewBusy) end
function ABP_StreamLevelTransition_C:InitializeTransition() end
function ABP_StreamLevelTransition_C:InitializeTransitionComplete() end
function ABP_StreamLevelTransition_C:ShowStreamLevel() end
function ABP_StreamLevelTransition_C:ShowStreamLevelComplete() end
function ABP_StreamLevelTransition_C:PreTransition() end
function ABP_StreamLevelTransition_C:TriggerTransition() end
function ABP_StreamLevelTransition_C:ProcessTeleportPlayer() end
function ABP_StreamLevelTransition_C:HandleTransitionSwitch() end
function ABP_StreamLevelTransition_C:HandleTransitionComplete() end
function ABP_StreamLevelTransition_C:HandlerTransitionInitializeComplete() end
function ABP_StreamLevelTransition_C:StartReturnTriggerable() end
---@param Cinematic ACinematicActor
function ABP_StreamLevelTransition_C:ReturnCinematicStop(Cinematic) end
function ABP_StreamLevelTransition_C:LoadStreamingLevel() end
---@param Location FVector
---@param Rotation FRotator
function ABP_StreamLevelTransition_C:StartLoadStreamLevel(Location, Rotation) end
function ABP_StreamLevelTransition_C:StartUnloadStreamLevel() end
---@param EndPlayReason EEndPlayReason::Type
function ABP_StreamLevelTransition_C:ReceiveEndPlay(EndPlayReason) end
function ABP_StreamLevelTransition_C:BeginTransition() end
function ABP_StreamLevelTransition_C:PrepareCompleteTransition() end
---@param EntryPoint int32
function ABP_StreamLevelTransition_C:ExecuteUbergraph_BP_StreamLevelTransition(EntryPoint) end
---@param Transition ABP_StreamLevelTransition_C
function ABP_StreamLevelTransition_C:OnTransitionStart__DelegateSignature(Transition) end
---@param Transition ABP_StreamLevelTransition_C
function ABP_StreamLevelTransition_C:OnTransitionComplete__DelegateSignature(Transition) end


