---@meta

---@class UWBP_GraphicsSettings_C : USysSettingsTab
---@field UberGraphFrame FPointerToUberGraphFrame
---@field DetailsWindowAppearing UWidgetAnimation
---@field Intro UWidgetAnimation
---@field CanvasPanel_0 UCanvasPanel
---@field EnvironmentHeader UWBP_HeaderPreview_C
---@field FXButton UWBP_SettingsTabBtn_C
---@field FXSettingsScrollBox UScrollBox
---@field Generalheader UWBP_HeaderPreview_C
---@field PostProcessingHeader UWBP_HeaderPreview_C
---@field SettingAmbientOcclusion UWBP_SettingBase_C
---@field SettingAntiAliasingQuality UWBP_SettingBase_C
---@field SettingBloom UWBP_SettingBase_C
---@field SettingBrightness UWBP_SettingBase_C
---@field SettingContrast UWBP_SettingBase_C
---@field SettingDLSS UWBP_SettingBase_C
---@field SettingDLSSFrameGen UWBP_SettingBase_C
---@field SettingDLSSSharpness UWBP_SettingBase_C
---@field SettingDOF UWBP_SettingBase_C
---@field SettingEmissiveIntensity UWBP_SettingBase_C
---@field SettingFilmGrain UWBP_SettingBase_C
---@field SettingFog UWBP_SettingBase_C
---@field SettingFOVModifier UWBP_SettingBase_C
---@field SettingFSR UWBP_SettingBase_C
---@field SettingGraphicsPreset UWBP_SettingRow_C
---@field SettingHDR UWBP_SettingBase_C
---@field SettingLighting UWBP_SettingBase_C
---@field SettingLOD UWBP_SettingBase_C
---@field SettingMaxFPS UWBP_SettingBase_C
---@field SettingMinimumResolution UWBP_SettingBase_C
---@field SettingNIS UWBP_SettingBase_C
---@field SettingParticleQuality UWBP_SettingBase_C
---@field SettingRaytraceReflections UWBP_SettingBase_C
---@field SettingRayTraceShadows UWBP_SettingBase_C
---@field SettingReflex UWBP_SettingBase_C
---@field SettingResolutionQuality UWBP_SettingBase_C
---@field SettingScreenOptimisations UWBP_SettingBase_C
---@field SettingScreenSpaceReflections UWBP_SettingBase_C
---@field SettingSDR UWBP_SettingBase_C
---@field SettingShadowQuality UWBP_SettingBase_C
---@field SettingTextureQuality UWBP_SettingBase_C
---@field SettingVRSMode UWBP_SettingBase_C
---@field SettingVSyncEnabled UWBP_SettingBase_C
---@field SettingXeSS UWBP_SettingBase_C
---@field ShadowHeader UWBP_HeaderPreview_C
---@field ValueAmbientOcclusion UWBP_SettingSpinner_C
---@field ValueAntiAliasingQuality UWBP_SettingSpinner_C
---@field ValueBloom UWBP_SettingSpinner_C
---@field ValueBrightness UWBP_SettingSlider_C
---@field ValueContrast UWBP_SettingSlider_C
---@field ValueDLSS UWBP_SettingSpinner_C
---@field ValueDLSSFrameGen UWBP_SettingSpinner_C
---@field ValueDLSSSharpness UWBP_SettingSlider_C
---@field ValueDOF UWBP_SettingSpinner_C
---@field ValueEmissiveIntensity UWBP_SettingSlider_C
---@field ValueFilmGrain UWBP_SettingSlider_C
---@field ValueFog UWBP_SettingSpinner_C
---@field ValueFOVModifier UWBP_SettingSlider_C
---@field ValueFSR UWBP_SettingSpinner_C
---@field ValueGraphicsPreset UWBP_SettingMultibuttonRow_C
---@field ValueHDR UWBP_SettingSpinner_C
---@field ValueLighting UWBP_SettingSpinner_C
---@field ValueLOD UWBP_SettingSpinner_C
---@field ValueMaxFPS UWBP_SettingSlider_C
---@field ValueMinimumResolution UWBP_SettingSlider_C
---@field ValueNIS UWBP_SettingSpinner_C
---@field ValueParticleQuality UWBP_SettingSpinner_C
---@field ValueRayTracedReflections UWBP_SettingSpinner_C
---@field ValueRayTraceShadows UWBP_SettingSpinner_C
---@field ValueReflex UWBP_SettingSpinner_C
---@field ValueResolutionScaling UWBP_SettingSlider_C
---@field ValueScreenOptimisations UWBP_SettingSpinner_C
---@field ValueScreenSpaceReflections UWBP_SettingSpinner_C
---@field ValueSDR UWBP_SettingSlider_C
---@field ValueShadowQuality UWBP_SettingSpinner_C
---@field ValueTextureQuality UWBP_SettingSpinner_C
---@field ValueVRSMode UWBP_SettingSpinner_C
---@field ValueVSyncEnabled UWBP_SettingSpinner_C
---@field ValueXeSS UWBP_SettingSpinner_C
---@field OnInputAction_SystemMenu FWBP_GraphicsSettings_COnInputAction_SystemMenu
---@field ['Base Turquoise'] UBP_WidgetStyle_C
---@field CachedParentSysSettings UWBP_SystemSettings_3Panel_C
---@field MainHud UWBP_HUDBase_C
---@field PreviewHud UWBP_HUDBase_C
---@field UIElementsLoaded boolean
---@field Key FKey
---@field DefaultVideoColorblind TArray<int32>
---@field DefaultVideoFX TArray<int32>
---@field CollectibleImages TArray<UTexture2D>
---@field QualityPresetArray TArray<EQualityPreset>
---@field VRSModeArray TArray<EVRSMode>
---@field JustChangedDisplaySetting boolean
---@field LastFocusedWidget UWBP_SettingBase_C
---@field LastFocusedTab UWBP_SettingsTabBtn_C
---@field FocusKeeper FWBP_GraphicsSettings_CFocusKeeper
---@field FocusKeeperTab FWBP_GraphicsSettings_CFocusKeeperTab
---@field DLSSArray TArray<EDLSSMode>
---@field FocusKeeperHeader FWBP_GraphicsSettings_CFocusKeeperHeader
---@field MinGamma float
---@field MaxGamma float
---@field ['Med Gamma'] float
---@field MaxSDR float
---@field CachedGraphicsPreset FGraphicsPreset
---@field GraphicsPreviews UBPDA_GraphicsPreview_C
---@field CachedSettingsWidget UWBP_SettingBase_C
---@field IsBootSettings boolean
---@field FPSValueText FText
---@field FSRArray TArray<EFSRMode>
---@field NISArray TArray<ENISMode>
---@field Curve_EmissiveIntennsity UCurveFloat
---@field NewTextForUpload TArray<FText>
---@field DynamicResolutionText FText
---@field ResolutionScalingText FText
---@field XeSSArray TArray<EXeSSMode>
---@field ReflexArray TArray<EReflexMode>
UWBP_GraphicsSettings_C = {}

---@param DLSSGOn boolean
function UWBP_GraphicsSettings_C:DLSSGLockFPSAndVSync(DLSSGOn) end
---@return boolean
function UWBP_GraphicsSettings_C:IsNVIDIAFrameGenAndReflexSupported() end
function UWBP_GraphicsSettings_C:HideAllScreenOptimizationSettings() end
---@param Settings TArray<UWBP_SettingBase_C>
---@param visible boolean
function UWBP_GraphicsSettings_C:SetSettingsVisible(Settings, visible) end
---@param IsMemorySufficientForRayTracing boolean
UWBP_GraphicsSettings_C['Has Required Memory For Ray Tracing'] = function(IsMemorySufficientForRayTracing) end
---@param Show boolean
function UWBP_GraphicsSettings_C:ShowRayTracingMemoryWarning(Show) end
function UWBP_GraphicsSettings_C:UpdateFOVModifierVisuals() end
function UWBP_GraphicsSettings_C:FilterOptions() end
---@param DLSS_Sharpness float
function UWBP_GraphicsSettings_C:SetDlssSharpnessSlider(DLSS_Sharpness) end
function UWBP_GraphicsSettings_C:ToggleResolutionScalingType() end
function UWBP_GraphicsSettings_C:ChangeToCustom() end
---@param FPS_Out float
UWBP_GraphicsSettings_C['Read FPS Slider'] = function(FPS_Out) end
---@param FPS_In float
UWBP_GraphicsSettings_C['Set FPS Slider'] = function(FPS_In) end
UWBP_GraphicsSettings_C['Restore Defaults FX'] = function() end
function UWBP_GraphicsSettings_C:LoadQualitySettings() end
---@param WBP_HUDBase UWBP_HUDBase_C
function UWBP_GraphicsSettings_C:GetPreviewHud(WBP_HUDBase) end
---@param MainHud UWBP_HUDBase_C
function UWBP_GraphicsSettings_C:GetMainHud(MainHud) end
---@param Widget UPanelWidget
function UWBP_GraphicsSettings_C:UpdateSettingsColor(Widget) end
function UWBP_GraphicsSettings_C:LoadSettings() end
---@param Loaded UObject
function UWBP_GraphicsSettings_C:OnLoaded_9A39BE2E40CDC14615DE539674DB2114(Loaded) end
---@param DeltaSeconds float
---@param bForeground boolean
function UWBP_GraphicsSettings_C:ReceiveTickScreen(DeltaSeconds, bForeground) end
function UWBP_GraphicsSettings_C:Construct() end
function UWBP_GraphicsSettings_C:RestoreToDefault() end
function UWBP_GraphicsSettings_C:BndEvt__ValueAntiAliasingQuality_K2Node_ComponentBoundEvent_14_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueShadowQuality_K2Node_ComponentBoundEvent_25_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueTextureQuality_K2Node_ComponentBoundEvent_26_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueResolutionScaling_K2Node_ComponentBoundEvent_27_OnValueChanged__DelegateSignature() end
---@param NewScreenName FName
function UWBP_GraphicsSettings_C:ReceiveExitScreen(NewScreenName) end
function UWBP_GraphicsSettings_C:BndEvt__ValueVSyncEnabled_K2Node_ComponentBoundEvent_17_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueFPS_K2Node_ComponentBoundEvent_22_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:InputAction_SystemMenu() end
function UWBP_GraphicsSettings_C:BndEvt__ValueLOD_K2Node_ComponentBoundEvent_24_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueFog_K2Node_ComponentBoundEvent_30_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueReflections_K2Node_ComponentBoundEvent_31_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueLighting_K2Node_ComponentBoundEvent_33_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueAmbientOcclusion_K2Node_ComponentBoundEvent_34_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueDOF_K2Node_ComponentBoundEvent_35_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueContrast_K2Node_ComponentBoundEvent_36_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueDLSS_K2Node_ComponentBoundEvent_37_OnValueChanged__DelegateSignature() end
---@param OldScreenName FName
---@param bFirst boolean
function UWBP_GraphicsSettings_C:ReceiveEnterScreen(OldScreenName, bFirst) end
---@param IsDesignTime boolean
function UWBP_GraphicsSettings_C:PreConstruct(IsDesignTime) end
function UWBP_GraphicsSettings_C:BndEvt__ValueDynamicResoluion_1_K2Node_ComponentBoundEvent_26_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueTouristEffectQuality_K2Node_ComponentBoundEvent_27_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueAllGraphics_K2Node_ComponentBoundEvent_28_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:NavigateToPreset() end
---@param SettingWidget UWBP_SettingBase_C
function UWBP_GraphicsSettings_C:BP_FocusKeeper(SettingWidget) end
function UWBP_GraphicsSettings_C:StartBenchmark() end
function UWBP_GraphicsSettings_C:BP_FocusKeeperHeader() end
function UWBP_GraphicsSettings_C:OverridePreviewType() end
function UWBP_GraphicsSettings_C:UpdateGraphicOptions() end
function UWBP_GraphicsSettings_C:BndEvt__ValueBloom_K2Node_ComponentBoundEvent_2_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueBrightness_K2Node_ComponentBoundEvent_5_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueSDR_K2Node_ComponentBoundEvent_6_OnValueChanged__DelegateSignature() end
---@param Setting_Widget UWBP_SettingBase_C
function UWBP_GraphicsSettings_C:UpdateGraphicsPreview(Setting_Widget) end
function UWBP_GraphicsSettings_C:PreviewControls() end
function UWBP_GraphicsSettings_C:BndEvt__ValueFSR_K2Node_ComponentBoundEvent_4_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueResolutionScalingType_K2Node_ComponentBoundEvent_8_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueDLSSSharpness_K2Node_ComponentBoundEvent_10_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueNIS_K2Node_ComponentBoundEvent_9_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueFilmGrain_K2Node_ComponentBoundEvent_11_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueHDR_K2Node_ComponentBoundEvent_12_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueBloomIntensity_K2Node_ComponentBoundEvent_13_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueMinimumResolution_K2Node_ComponentBoundEvent_14_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueFOVModifier_K2Node_ComponentBoundEvent_16_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueRayTracedShadows_K2Node_ComponentBoundEvent_15_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueScreenSpaceReflections_K2Node_ComponentBoundEvent_18_OnValueChanged__DelegateSignature() end
---@param Enabled boolean
function UWBP_GraphicsSettings_C:SetRaytraceShadowsEnabledValue(Enabled) end
---@param Enabled boolean
function UWBP_GraphicsSettings_C:SetRaytracedReflectionsEnabledValue(Enabled) end
function UWBP_GraphicsSettings_C:BndEvt__ValueXeSS_K2Node_ComponentBoundEvent_0_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:OnRayTracingSettingEnabled() end
function UWBP_GraphicsSettings_C:BndEvt__ValueDLSSFrameGen_K2Node_ComponentBoundEvent_20_OnValueChanged__DelegateSignature() end
function UWBP_GraphicsSettings_C:BndEvt__ValueReflex_K2Node_ComponentBoundEvent_3_OnValueChanged__DelegateSignature() end
---@param IsEnabled boolean
function UWBP_GraphicsSettings_C:OnDLSSFrameGenEnabled(IsEnabled) end
---@param EntryPoint int32
function UWBP_GraphicsSettings_C:ExecuteUbergraph_WBP_GraphicsSettings(EntryPoint) end
function UWBP_GraphicsSettings_C:FocusKeeperHeader__DelegateSignature() end
---@param SettingTab UWBP_SettingsTabBtn_C
function UWBP_GraphicsSettings_C:FocusKeeperTab__DelegateSignature(SettingTab) end
---@param SettingWidget UWBP_SettingBase_C
function UWBP_GraphicsSettings_C:FocusKeeper__DelegateSignature(SettingWidget) end
function UWBP_GraphicsSettings_C:OnInputAction_SystemMenu__DelegateSignature() end


