---@meta

---@class UWBP_ChallengePost_C : USocialChallengeGameOverWidget
---@field UberGraphFrame FPointerToUberGraphFrame
---@field LoadingFadeChange UWidgetAnimation
---@field TotalScoreLabelFadeIn UWidgetAnimation
---@field ObjectivesHeaderAnim UWidgetAnimation
---@field SkillHeaderAnim UWidgetAnimation
---@field ExplorerHeaderAnim UWidgetAnimation
---@field CombatHeaderAnim UWidgetAnimation
---@field Intro_1 UWidgetAnimation
---@field LeaderboardAnim UWidgetAnimation
---@field ScoreToRankAnim UWidgetAnimation
---@field Backdrop UImage
---@field Challenge_1 UVerticalBox
---@field ChallengeContentOverlay UOverlay
---@field ChallengeStats_Border UBorder
---@field CombatBorder UBorder
---@field CombatGrid UGridPanel
---@field CombatHeaderOverlay UOverlay
---@field ConnectionOverlay UOverlay
---@field DateTextBox UHMQRichTextBlock
---@field ExplorerBorder_1 UBorder
---@field ExplorerGrid UGridPanel
---@field ExplorerHeaderOverlay UOverlay
---@field FullBackImage UImage
---@field FullBackImage_2 UImage
---@field HeaderBackingImg UImage
---@field HeaderBackingImg_1 UImage
---@field HeaderBackingImg_2 UImage
---@field HeaderBorder UBorder
---@field HeaderBorder_CromBlue UBorder
---@field HeaderBorder_CromRed UBorder
---@field HeadingTextBox UHMQRichTextBlock
---@field HeadingTextBox_CromBlue UHMQRichTextBlock
---@field HeadingTextBox_CromRed UHMQRichTextBlock
---@field HeadingTextBox_White UHMQRichTextBlock
---@field Image_140 UImage
---@field MainOverlay UOverlay
---@field ObjectiveBorder UBorder
---@field ObjectiveGrid UGridPanel
---@field ObjectivesHeaderOverlay UOverlay
---@field Overlay_0 UOverlay
---@field PlayerCompletionTimeText UHMQRichTextBlock
---@field RankBacking UImage
---@field RankBacking_2 UImage
---@field RankScoreBorder UBorder
---@field RankTextBox UHMQRichTextBlock
---@field RankVerticalBox UVerticalBox
---@field RetainerBox_0 URetainerBox
---@field RichText_ChallengeRankHeader UHMQRichTextBlock
---@field RichText_ChallengeRankHeader_CromBlue UHMQRichTextBlock
---@field RichText_ChallengeRankHeader_CromRed UHMQRichTextBlock
---@field RichText_ChallengeRankHeader_White UHMQRichTextBlock
---@field RichText_ChallengeScoreHeader UHMQRichTextBlock
---@field RichText_ChallengeScoreHeader_CromBlue UHMQRichTextBlock
---@field RichText_ChallengeScoreHeader_CromRed UHMQRichTextBlock
---@field RichText_ChallengeScoreHeader_White UHMQRichTextBlock
---@field RichText_ChallengeStats UHMQRichTextBlock
---@field RichText_ChallengeStats_2 UHMQRichTextBlock
---@field RichText_ChallengeStats_4 UHMQRichTextBlock
---@field RichText_ChallengeStats_CromBlue UHMQRichTextBlock
---@field RichText_ChallengeStats_CromRed UHMQRichTextBlock
---@field RichText_ChallengeStats_White UHMQRichTextBlock
---@field RichText_Combat UHMQRichTextBlock
---@field RichText_Combat_CromBlue UHMQRichTextBlock
---@field RichText_Combat_CromRed UHMQRichTextBlock
---@field RichText_Combat_White UHMQRichTextBlock
---@field RichText_ConnectionStatus UHMQRichTextBlock
---@field RichText_ConnectionStatus_Lost UHMQRichTextBlock
---@field RichText_ConnectionStatus_Lost_2 UHMQRichTextBlock
---@field RichText_Explorer UHMQRichTextBlock
---@field RichText_Explorer_CromBlue UHMQRichTextBlock
---@field RichText_Explorer_CromRed UHMQRichTextBlock
---@field RichText_Explorer_White UHMQRichTextBlock
---@field RichText_Objectives UHMQRichTextBlock
---@field RichText_Objectives_CromBlue UHMQRichTextBlock
---@field RichText_Objectives_CromRed UHMQRichTextBlock
---@field RichText_Objectives_White UHMQRichTextBlock
---@field RichText_Skill UHMQRichTextBlock
---@field RichText_Skill_CromBlue UHMQRichTextBlock
---@field RichText_Skill_CromRed UHMQRichTextBlock
---@field RichText_Skill_White UHMQRichTextBlock
---@field RichText_SubmitScore UHMQRichTextBlock
---@field SizeBox_PC USizeBox
---@field SkillBorder UBorder
---@field SkillGrid UGridPanel
---@field SkillHeaderOverlay UOverlay
---@field SubmitScoreOverlay UOverlay
---@field Tabs UWBP_MenuTabs_C
---@field TimeCompleteTextBox UHMQRichTextBlock
---@field TimeCompleteTextBox_CromBlue UHMQRichTextBlock
---@field TimeCompleteTextBox_CromRed UHMQRichTextBlock
---@field TimeCompleteTextBox_White UHMQRichTextBlock
---@field TimeRemainingHoursTextBox UHMQRichTextBlock
---@field TimeRemainingHoursTextBox_1 UHMQRichTextBlock
---@field TimeRemainingMinuetsTextBox UHMQRichTextBlock
---@field TimeRemainingMinuetsTextBox_1 UHMQRichTextBlock
---@field TimeRemainingSecondsTextBox UHMQRichTextBlock
---@field TimeRemainingSecondsTextBox_1 UHMQRichTextBlock
---@field TotalPlayers UHMQRichTextBlock
---@field WBP_AstraLogoLoading UWBP_AstraLogoLoading_C
---@field WBP_BorderHeadingText UWBP_BorderHeadingText_C
---@field WBP_BorderHeadingText_1 UWBP_BorderHeadingText_C
---@field WBP_BorderHeadingText_2 UWBP_BorderHeadingText_C
---@field WBP_BorderHeadingText_9 UWBP_BorderHeadingText_C
---@field WBP_BorderHeadingText_10 UWBP_BorderHeadingText_C
---@field WBP_BorderHeadingText_11 UWBP_BorderHeadingText_C
---@field WBP_BorderHeadingText_13 UWBP_BorderHeadingText_C
---@field WBP_BorderTopHeading UWBP_BorderTopHeading_C
---@field WBP_BorderTopHeading_1 UWBP_BorderTopHeading_C
---@field WBP_BorderTopHeading_2 UWBP_BorderTopHeading_C
---@field WBP_BorderTopHeading_3 UWBP_BorderTopHeading_C
---@field WBP_BorderTopHeading_4 UWBP_BorderTopHeading_C
---@field WBP_BorderTopHeading_5 UWBP_BorderTopHeading_C
---@field WBP_BorderTopHeading_6 UWBP_BorderTopHeading_C
---@field WBP_BrushImage UWBP_BrushImage_C
---@field WBP_ChallengeMenuOverlay UWBP_ChallengeMenuOverlay_C
---@field WBP_ChallengePost_RankBar UWBP_ChallengePost_RankBar_C
---@field WBP_ChallengePost_ScoreBar UWBP_ChallengePost_ScoreBar_C
---@field WBP_ChallengePost_TotalScore UWBP_ChallengePost_TotalScore_C
---@field WBP_ChallengeTierIcon UWBP_ChallengeTierIcon_C
---@field WBP_DailyChallengeScores_1 UWBP_ChallengeLeaderboard_C
---@field WBP_HorizontalLinePlain_White_18 UWBP_HorizontalLinePlain_White_C
---@field WBP_HorizontalLinePlain_White_19 UWBP_HorizontalLinePlain_White_C
---@field WBP_PromptBar UWBP_PromptBar_C
---@field WBP_PromptBarItem_GoOnline UWBP_PromptBarItem_C
---@field WBP_PromptBarItem_Return UWBP_PromptBarItem_C
---@field WBP_PromptBarItem_ReturnToGame_2 UWBP_PromptBarItem_C
---@field WBP_PromptBarItem_ReturnToGame_5 UWBP_PromptBarItem_C
---@field WBP_PromptBarItem_SubmitScore_1 UWBP_PromptBarItem_C
---@field WBP_SkipProgress UWBP_SkipProgress_C
---@field WBP_UltraWide_BG UWBP_UltraWide_BG_C
---@field WBP_VerticalLinePlain UWBP_VerticalLinePlain_C
---@field RankSetup boolean
---@field CombatReward int32
---@field CombatDeduction int32
---@field ExplorerReward int32
---@field ExplorerDeduction int32
---@field SkillReward int32
---@field SkillDeduction int32
---@field ObjectivesReward int32
---@field ObjectivesDeduction int32
---@field FadeInDelay float
---@field PlayerRank int64
---@field ChallangeDetailsFinished FWBP_ChallengePost_CChallangeDetailsFinished
---@field ReturnVal int32
---@field ScoresSetup boolean
---@field ScoreGroupDelay float
---@field BonusWidgetList TArray<UWBP_ChallengePostReward_C>
---@field CurrentBonusGroupIndex int32
---@field GlitchEffectTimerSecs float
---@field GlitchEffectEnabled boolean
---@field CurrentHeaderIndex int32
---@field HeaderArray TArray<UWidgetAnimation>
---@field IsTotalScoreLabelFadeIn boolean
---@field CurrentScore int32
---@field CurrentScoreGroupIndex int32
---@field connected boolean
---@field Started boolean
---@field ScoreSubmitPending boolean
---@field ScoreSubmitted boolean
---@field InRankView boolean
---@field ScoreComplete boolean
---@field CanReturn boolean
---@field CachedSocialChallengeManager USocialChallengeManager
---@field CachedActiveChallengeGameMode USocialChallengeGameMode
---@field GlitchColourChangeArray TArray<UBP_ChallengePostTextGlitch_C>
---@field TotalRankings int32
---@field Audio_PositiveIsChanging boolean
---@field Audio_NegativeIsChanging boolean
---@field Audio_PositiveTextIsFadingIn boolean
---@field Audio_NegativeTextIsFadingIn boolean
---@field Audio_ScoreBarUpdateCount float
---@field IsExiting boolean
---@field FadeColor FLinearColor
---@field LocalisationArray TArray<FString>
---@field ChallengeId int64
---@field TimeCompleteFormat FText
---@field EnableAstraLoading boolean
---@field Audio_MenuDestroyed UAkAudioEvent
---@field Audio_StopPositiveSoundSpam boolean
---@field TotalScore int32
---@field CanSkip boolean
---@field SkipDown boolean
---@field Skipping boolean
---@field SkipTime float
---@field SkipDelta float
UWBP_ChallengePost_C = {}

function UWBP_ChallengePost_C:SequenceEvent__ENTRYPOINTWBP_ChallengePost_3() end
function UWBP_ChallengePost_C:SequenceEvent__ENTRYPOINTWBP_ChallengePost_2() end
function UWBP_ChallengePost_C:SequenceEvent__ENTRYPOINTWBP_ChallengePost_1() end
function UWBP_ChallengePost_C:SequenceEvent__ENTRYPOINTWBP_ChallengePost_0() end
---@param IsWindows boolean
function UWBP_ChallengePost_C:SetLayoutSize(IsWindows) end
---@param MyGeometry FGeometry
---@param InKeyEvent FKeyEvent
---@return FEventReply
function UWBP_ChallengePost_C:OnKeyDown(MyGeometry, InKeyEvent) end
---@param DeltaTime float
function UWBP_ChallengePost_C:UpdateSkippProgress(DeltaTime) end
function UWBP_ChallengePost_C:ScoreBarDone() end
function UWBP_ChallengePost_C:Skip() end
function UWBP_ChallengePost_C:AudioScoreBarNoChangeNegative() end
function UWBP_ChallengePost_C:AudioScoreBarNoChangePositive() end
---@param MyGeometry FGeometry
---@param InKeyEvent FKeyEvent
---@return FEventReply
function UWBP_ChallengePost_C:OnKeyUp(MyGeometry, InKeyEvent) end
UWBP_ChallengePost_C['Audio Score Bar Change Negative Stop'] = function() end
function UWBP_ChallengePost_C:AudioScoreBarChangeNegativeStart() end
function UWBP_ChallengePost_C:AudioScoreBarChangePositiveStop() end
function UWBP_ChallengePost_C:AudioScoreBarChangePositiveStart() end
function UWBP_ChallengePost_C:AudioScoreBarEnd() end
function UWBP_ChallengePost_C:AudioScoreBarBegin() end
function UWBP_ChallengePost_C:AudioScoreItemTextFadeStopNegative() end
function UWBP_ChallengePost_C:AudioScoreItemTextFadeStopPositive() end
function UWBP_ChallengePost_C:AudioScoreItemTextFadeStartPositive() end
function UWBP_ChallengePost_C:AudioScoreItemTextFadeStartNegative() end
UWBP_ChallengePost_C['Audio Leaderboard Appear'] = function() end
function UWBP_ChallengePost_C:AudioRankBarStart() end
function UWBP_ChallengePost_C:AudioGroupTitleFadeIn() end
function UWBP_ChallengePost_C:AudioMainScreenStarted() end
---@param Primary UHMQRichTextBlock
---@param white UHMQRichTextBlock
---@param Blue UHMQRichTextBlock
---@param red UHMQRichTextBlock
UWBP_ChallengePost_C['Add Glitch Effect Group'] = function(Primary, white, Blue, red) end
function UWBP_ChallengePost_C:SetupGlitchEffect() end
---@param ReferencesOk boolean
function UWBP_ChallengePost_C:CachedReferencesOk(ReferencesOk) end
function UWBP_ChallengePost_C:SetupCachedReferences() end
---@param visible boolean
---@param ForceAllowExit boolean
UWBP_ChallengePost_C['Set Submit Score Retry Message'] = function(visible, ForceAllowExit) end
---@param StringArray TArray<FString>
---@param StringIndex int32
---@param RichTextBox UHMQRichTextBlock
---@param RichTextBox2 UHMQRichTextBlock
function UWBP_ChallengePost_C:SetTextFromArrayElement(StringArray, StringIndex, RichTextBox, RichTextBox2) end
---@param Enabled boolean
function UWBP_ChallengePost_C:SetCanReturn(Enabled) end
function UWBP_ChallengePost_C:SetupAndStart() end
function UWBP_ChallengePost_C:SwitchToRankView() end
function UWBP_ChallengePost_C:SubmitScoreIfNotSubmitted() end
function UWBP_ChallengePost_C:ShowAndStart() end
---@param IsConnected boolean
function UWBP_ChallengePost_C:CheckForServerConnection(IsConnected) end
function UWBP_ChallengePost_C:SetupHeaderAnimArray() end
function UWBP_ChallengePost_C:BonusNegativeFadeInFinished() end
function UWBP_ChallengePost_C:BonusFadeInFinished() end
function UWBP_ChallengePost_C:BonusNegativeAnimationFinishedCallback() end
function UWBP_ChallengePost_C:BonusAnimationFinishedCallback() end
---@param MaxNumberPlayers int64
function UWBP_ChallengePost_C:SetMaxRankText(MaxNumberPlayers) end
UWBP_ChallengePost_C['Setup Icon'] = function() end
---@param ItemIndex int32
---@param value int32
---@param NegetiveBonus boolean
---@param ClampedValue int32
function UWBP_ChallengePost_C:AddToGroupTotal(ItemIndex, value, NegetiveBonus, ClampedValue) end
function UWBP_ChallengePost_C:SetupRank() end
---@param Success boolean
function UWBP_ChallengePost_C:SetupScores(Success) end
function UWBP_ChallengePost_C:Setup() end
function UWBP_ChallengePost_C:SetupTimes() end
function UWBP_ChallengePost_C:SetupHeadings() end
---@param ItemIndex int32
---@param GridWidget UGridPanel
function UWBP_ChallengePost_C:GetBonusGroupContainer(ItemIndex, GridWidget) end
function UWBP_ChallengePost_C:SetupStats() end
function UWBP_ChallengePost_C:SetLabels() end
---@param AddPlusOrMinus boolean
---@param PlussOrMinus boolean
---@param Integer int64
---@param TextBox UHMQRichTextBlock
function UWBP_ChallengePost_C:SetValueText(AddPlusOrMinus, PlussOrMinus, Integer, TextBox) end
function UWBP_ChallengePost_C:HeaderAnimTrigger() end
function UWBP_ChallengePost_C:Construct() end
function UWBP_ChallengePost_C:ScoreBarComplete() end
function UWBP_ChallengePost_C:RankFadeAnimationFinished() end
function UWBP_ChallengePost_C:RankAnimationFinsihed() end
function UWBP_ChallengePost_C:LeaderboardFadeInFinished() end
---@param Rank int32
function UWBP_ChallengePost_C:RankBarRankUpdatedEvent(Rank) end
---@param Score int32
function UWBP_ChallengePost_C:ScoreBarScoreUpdated(Score) end
function UWBP_ChallengePost_C:IntroAnimFinishedEvent() end
function UWBP_ChallengePost_C:OnConnectedEvent() end
function UWBP_ChallengePost_C:OnDisconnectedEvent() end
---@param Manager USocialChallengeManager
---@param ID int64
---@param Rank int64
function UWBP_ChallengePost_C:ScoreSubmittedEvent(Manager, ID, Rank) end
---@param MyGeometry FGeometry
---@param InDeltaTime float
function UWBP_ChallengePost_C:Tick(MyGeometry, InDeltaTime) end
function UWBP_ChallengePost_C:Destruct() end
function UWBP_ChallengePost_C:EndGameOverProcess() end
---@param Manager USocialChallengeManager
---@param ID int64
function UWBP_ChallengePost_C:ScoreSubmittedFailedEvent(Manager, ID) end
---@param TotalRankings int64
function UWBP_ChallengePost_C:OnTotalRankRetrieved(TotalRankings) end
function UWBP_ChallengePost_C:OnConnectionFinished() end
---@param Biome EBiome
---@param NewBiomeState EBiomeState
function UWBP_ChallengePost_C:OnBiomeStateChanged(Biome, NewBiomeState) end
function UWBP_ChallengePost_C:LoadingFinished() end
function UWBP_ChallengePost_C:ReceiveDestroyScreen() end
---@param IsDesignTime boolean
function UWBP_ChallengePost_C:PreConstruct(IsDesignTime) end
---@param OldScreenName FName
---@param bFirst boolean
function UWBP_ChallengePost_C:ReceiveEnterScreen(OldScreenName, bFirst) end
---@param NewScreenName FName
function UWBP_ChallengePost_C:ReceiveExitScreen(NewScreenName) end
function UWBP_ChallengePost_C:BndEvt__WBP_PromptBarItem_Return_K2Node_ComponentBoundEvent_0_PromptPressed__DelegateSignature() end
function UWBP_ChallengePost_C:BackOut() end
function UWBP_ChallengePost_C:BndEvt__WBP_PromptBarItem_SubmitScore_1_K2Node_ComponentBoundEvent_1_PromptPressed__DelegateSignature() end
function UWBP_ChallengePost_C:BndEvt__WBP_PromptBarItem_ReturnToGame_5_K2Node_ComponentBoundEvent_2_PromptPressed__DelegateSignature() end
function UWBP_ChallengePost_C:SubmitScorePressed() end
function UWBP_ChallengePost_C:ReconnectPressed() end
function UWBP_ChallengePost_C:BndEvt__WBP_PromptBarItem_GoOnline_K2Node_ComponentBoundEvent_3_PromptPressed__DelegateSignature() end
function UWBP_ChallengePost_C:BndEvt__WBP_PromptBarItem_ReturnToGame_2_K2Node_ComponentBoundEvent_4_PromptPressed__DelegateSignature() end
function UWBP_ChallengePost_C:BndEvt__WBP_SkipProgress_K2Node_ComponentBoundEvent_5_Clicked__DelegateSignature() end
function UWBP_ChallengePost_C:BndEvt__WBP_SkipProgress_K2Node_ComponentBoundEvent_6_Unclicked__DelegateSignature() end
---@param EntryPoint int32
function UWBP_ChallengePost_C:ExecuteUbergraph_WBP_ChallengePost(EntryPoint) end
function UWBP_ChallengePost_C:ChallangeDetailsFinished__DelegateSignature() end


