---@meta

---@class UWBP_GameLanguageSettings_C : USysSettingsTab
---@field UberGraphFrame FPointerToUberGraphFrame
---@field Arabic UWBP_SettingBase_C
---@field ArabicTick UWBP_SettingButtonTick_C
---@field CanvasPanel_0 UCanvasPanel
---@field ChineseSimplified UWBP_SettingBase_C
---@field ChineseSimplifiedTick UWBP_SettingButtonTick_C
---@field ChineseTraditional UWBP_SettingBase_C
---@field ChineseTraditionalTick UWBP_SettingButtonTick_C
---@field Danish UWBP_SettingBase_C
---@field DanishTick UWBP_SettingButtonTick_C
---@field Dutch UWBP_SettingBase_C
---@field DutchTick UWBP_SettingButtonTick_C
---@field EnglishTick UWBP_SettingButtonTick_C
---@field EnglishTickUK UWBP_SettingButtonTick_C
---@field EnglishUK UWBP_SettingBase_C
---@field EnglishUS UWBP_SettingBase_C
---@field Finnish UWBP_SettingBase_C
---@field FinnishTick UWBP_SettingButtonTick_C
---@field French UWBP_SettingBase_C
---@field FrenchTick UWBP_SettingButtonTick_C
---@field German UWBP_SettingBase_C
---@field GermanTick UWBP_SettingButtonTick_C
---@field Indonesian UWBP_SettingBase_C
---@field IndonesianTick UWBP_SettingButtonTick_C
---@field Italian UWBP_SettingBase_C
---@field ItalianTick UWBP_SettingButtonTick_C
---@field Japanese UWBP_SettingBase_C
---@field JapaneseTick UWBP_SettingButtonTick_C
---@field Korean UWBP_SettingBase_C
---@field KoreanTick UWBP_SettingButtonTick_C
---@field LanguageButton UWBP_SettingsTabBtn_C
---@field LanguagesScrollBox UScrollBox
---@field Norwegian UWBP_SettingBase_C
---@field NorwegianTick UWBP_SettingButtonTick_C
---@field Polish UWBP_SettingBase_C
---@field PolishTick UWBP_SettingButtonTick_C
---@field Portuguese UWBP_SettingBase_C
---@field PortugueseBR UWBP_SettingBase_C
---@field PortugueseBRTick UWBP_SettingButtonTick_C
---@field PortugueseTick UWBP_SettingButtonTick_C
---@field Russian UWBP_SettingBase_C
---@field RussianTick UWBP_SettingButtonTick_C
---@field Spanish UWBP_SettingBase_C
---@field SpanishLatin UWBP_SettingBase_C
---@field SpanishLatinTick UWBP_SettingButtonTick_C
---@field SpanishTick UWBP_SettingButtonTick_C
---@field Swedish UWBP_SettingBase_C
---@field SwedishTick UWBP_SettingButtonTick_C
---@field Thai UWBP_SettingBase_C
---@field ThaiTick UWBP_SettingButtonTick_C
---@field Vietnamese UWBP_SettingBase_C
---@field VietnameseTick UWBP_SettingButtonTick_C
---@field CurrentTick UWBP_SettingButtonTick_C
---@field CachedParentSysSettings UWBP_SystemSettings_3Panel_C
---@field StyleDataTable UDataTable
---@field FocusKeeper FWBP_GameLanguageSettings_CFocusKeeper
---@field TempTextForGameLanguage FText
UWBP_GameLanguageSettings_C = {}

function UWBP_GameLanguageSettings_C:Construct() end
function UWBP_GameLanguageSettings_C:BndEvt__EnglishTick_K2Node_ComponentBoundEvent_0_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:BndEvt__FrenchTick_K2Node_ComponentBoundEvent_1_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:BndEvt__GermanTick_K2Node_ComponentBoundEvent_2_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:BndEvt__ItalianTick_K2Node_ComponentBoundEvent_3_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:BndEvt__SpanishTick_K2Node_ComponentBoundEvent_4_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:BndEvt__PortugueseTick_K2Node_ComponentBoundEvent_5_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:BndEvt__DanishTick_K2Node_ComponentBoundEvent_6_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:BndEvt__NorwegianTick_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:BndEvt__SwedishTick_K2Node_ComponentBoundEvent_8_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:BndEvt__FinnishTick_K2Node_ComponentBoundEvent_9_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:BndEvt__PolishTick_K2Node_ComponentBoundEvent_10_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:BndEvt__RussianTick_K2Node_ComponentBoundEvent_11_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:BndEvt__ArabicTick_K2Node_ComponentBoundEvent_12_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:BndEvt__PortugueseBRTick_K2Node_ComponentBoundEvent_13_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:BndEvt__SpanishLatinTick_K2Node_ComponentBoundEvent_14_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:BndEvt__JapaneseTick_K2Node_ComponentBoundEvent_16_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:BndEvt__KoreanTick_K2Node_ComponentBoundEvent_17_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:BndEvt__ChineseSimplifiedTick_K2Node_ComponentBoundEvent_18_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:BndEvt__ChineseTraditionalTick_K2Node_ComponentBoundEvent_19_OnValueChanged__DelegateSignature() end
---@param NewTick UWBP_SettingButtonTick_C
function UWBP_GameLanguageSettings_C:SwapTick(NewTick) end
function UWBP_GameLanguageSettings_C:BndEvt__DutchTick_K2Node_ComponentBoundEvent_20_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:OverrideText() end
function UWBP_GameLanguageSettings_C:ApplyChangesWarning() end
function UWBP_GameLanguageSettings_C:BndEvt__EnglishTickUK_K2Node_ComponentBoundEvent_24_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:SelectCulture() end
---@param CurrentTick UWBP_SettingButtonTick_C
function UWBP_GameLanguageSettings_C:DefaultTick(CurrentTick) end
---@param SettingWidget UWBP_SettingBase_C
function UWBP_GameLanguageSettings_C:FocusGained(SettingWidget) end
---@param IsDesignTime boolean
function UWBP_GameLanguageSettings_C:PreConstruct(IsDesignTime) end
function UWBP_GameLanguageSettings_C:BndEvt__ThaiTick_K2Node_ComponentBoundEvent_15_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:BndEvt__VietnameseTick_K2Node_ComponentBoundEvent_21_OnValueChanged__DelegateSignature() end
function UWBP_GameLanguageSettings_C:BndEvt__IndonesianTick_K2Node_ComponentBoundEvent_22_OnValueChanged__DelegateSignature() end
---@param EntryPoint int32
function UWBP_GameLanguageSettings_C:ExecuteUbergraph_WBP_GameLanguageSettings(EntryPoint) end
---@param SettingWidget UWBP_SettingBase_C
function UWBP_GameLanguageSettings_C:FocusKeeper__DelegateSignature(SettingWidget) end


