---@meta

---@class UWBP_VideoSettings_C : USysSettingsTab
---@field UberGraphFrame FPointerToUberGraphFrame
---@field DetailsWindowAppearing UWidgetAnimation
---@field Intro UWidgetAnimation
---@field BrightnessButton UWBP_SettingButtonLead_C
---@field CanvasPanel_0 UCanvasPanel
---@field ColourBlindModeButton UWBP_SettingsTabBtn_C
---@field ColourBlindModeSettingsScrollBox UScrollBox
---@field CustomiseHUDButton UWBP_SettingsTabBtn_C
---@field DisplayButton UWBP_SettingsTabBtn_C
---@field DisplaySettingsScrollBox UScrollBox
---@field FXButton UWBP_SettingsTabBtn_C
---@field FXSettingsScrollBox UScrollBox
---@field HUDSafeZoneButton UWBP_SettingButtonLead_C
---@field HUDScaleSettingsScrollBox UScrollBox
---@field PerformanceButton UWBP_SettingsTabBtn_C
---@field PerformanceScrollBox UScrollBox
---@field SettingAltFireIndicator UWBP_SettingBase_C
---@field SettingAspectRatioScreen UWBP_SettingBase_C
---@field SettingBloom UWBP_SettingBase_C
---@field SettingBrightness UWBP_SettingBase_C
---@field SettingCinematicUltrawideSupport UWBP_SettingBase_C
---@field SettingCollectiblesPallet UWBP_SettingBase_C
---@field SettingColourBlind UWBP_SettingBase_C
---@field SettingColourBlindStrength UWBP_SettingBase_C
---@field SettingColourUI UWBP_SettingBase_C
---@field SettingCrosshairScale UWBP_SettingBase_C
---@field SettingCrosshairThickness UWBP_SettingBase_C
---@field SettingDisplayModeScreen UWBP_SettingBase_C
---@field SettingDisplayMonitorScreen UWBP_SettingBase_C
---@field SettingDynamicHUD UWBP_SettingBase_C
---@field SettingHideAdrenalineBar UWBP_SettingBase_C
---@field SettingHideAltFire UWBP_SettingBase_C
---@field SettingHideBossHealth UWBP_SettingBase_C
---@field SettingHideCollectibles UWBP_SettingBase_C
---@field SettingHideConsumable UWBP_SettingBase_C
---@field SettingHideCoop UWBP_SettingBase_C
---@field SettingHideEnemyHealth UWBP_SettingBase_C
---@field SettingHideHealthbar UWBP_SettingBase_C
---@field SettingHideMinimap UWBP_SettingBase_C
---@field SettingHideProficiency UWBP_SettingBase_C
---@field SettingHideSessionTime UWBP_SettingBase_C
---@field SettingHideWeaponTrait UWBP_SettingBase_C
---@field SettingHUDPerformanceSupport UWBP_SettingBase_C
---@field SettingHUDSafeZoneScreen UWBP_SettingBase_C
---@field SettingHUDUltrawideSupport UWBP_SettingBase_C
---@field Settingmotionblur UWBP_SettingBase_C
---@field SettingScreenResolutionScreen UWBP_SettingBase_C
---@field SettingUIContrast UWBP_SettingBase_C
---@field SettingUIFVX UWBP_SettingBase_C
---@field SettingUIFVXPC UWBP_SettingBase_C
---@field SettingUIUltrawideSupport UWBP_SettingBase_C
---@field SettingWindowsCPUUse UWBP_SettingBase_C
---@field SettingWindowsFontSize UWBP_SettingBase_C
---@field SettingWindowsFPS UWBP_SettingBase_C
---@field SettingWindowsGPUSpeed UWBP_SettingBase_C
---@field SettingWindowsGPUTemp UWBP_SettingBase_C
---@field SettingWindowsGPUUse UWBP_SettingBase_C
---@field SettingWindowsLatency UWBP_SettingBase_C
---@field SettingWindowsVRAMUSe UWBP_SettingBase_C
---@field ValueAltFireIndicator UWBP_SettingSpinner_C
---@field ValueAspectRatio UWBP_SettingSpinner_C
---@field ValueBloom UWBP_SettingSpinner_C
---@field ValueCinematicUltrawideSupport UWBP_SettingSpinner_C
---@field ValueCollectiblesPallet UWBP_SettingSpinner_C
---@field ValueColourBlind UWBP_SettingSpinner_C
---@field ValueColourBlindStrength UWBP_SettingSlider_C
---@field ValueColourUI UWBP_SettingSpinner_C
---@field valueCrosshairScale UWBP_SettingSpinner_C
---@field ValueCrosshairThickness UWBP_SettingSpinner_C
---@field ValueDisplayMode UWBP_SettingSpinner_C
---@field ValueDisplayMonitor UWBP_SettingSpinner_C
---@field ValueDynamicHUD UWBP_SettingSpinner_C
---@field ValueHideAdrenalineBar UWBP_SettingSpinner_C
---@field ValueHideAltFire UWBP_SettingSpinner_C
---@field ValueHideBossHealth UWBP_SettingSpinner_C
---@field ValueHideCollectibles UWBP_SettingSpinner_C
---@field ValueHideConsumable UWBP_SettingSpinner_C
---@field ValueHideCoop UWBP_SettingSpinner_C
---@field ValueHideEnemyHealth UWBP_SettingSpinner_C
---@field ValueHideHealthbar UWBP_SettingSpinner_C
---@field ValueHideMinimap UWBP_SettingSpinner_C
---@field ValueHideProficiency UWBP_SettingSpinner_C
---@field ValueHideSessionTime UWBP_SettingSpinner_C
---@field ValueHideWeaponTrait UWBP_SettingSpinner_C
---@field ValueHUDPerformanceSupport UWBP_SettingSpinner_C
---@field ValueHUDUltrawideSupport UWBP_SettingSpinner_C
---@field Valuemotionblur UWBP_SettingSpinner_C
---@field ValueScreenResolution UWBP_SettingSpinner_C
---@field ValueUIContrast UWBP_SettingSlider_C
---@field ValueUIUltrawideSupport UWBP_SettingSpinner_C
---@field ValueUIVFX UWBP_SettingSpinner_C
---@field ValueUIVFXPC UWBP_SettingSpinner_C
---@field ValueWindowsCPUUse UWBP_SettingSpinner_C
---@field ValueWindowsFontSize UWBP_SettingSpinner_C
---@field ValueWindowsFPS UWBP_SettingSpinner_C
---@field ValueWindowsGPUSpeed UWBP_SettingSpinner_C
---@field ValueWindowsGPUTemp UWBP_SettingSpinner_C
---@field ValueWindowsGPUUse UWBP_SettingSpinner_C
---@field ValueWindowsLatency UWBP_SettingSpinner_C
---@field ValueWindowsVRAMUse UWBP_SettingSpinner_C
---@field WBP_HeaderPreview UWBP_HeaderPreview_C
---@field WBP_HeaderPreview_1 UWBP_HeaderPreview_C
---@field WBP_HeaderPreview_2 UWBP_HeaderPreview_C
---@field WBP_HeaderPreview_UlltraWide UWBP_HeaderPreview_C
---@field OnInputAction_SystemMenu FWBP_VideoSettings_COnInputAction_SystemMenu
---@field ['Base Turquoise'] UBP_WidgetStyle_C
---@field CachedParentSysSettings UWBP_SystemSettings_3Panel_C
---@field MainHud UWBP_HUDBase_C
---@field PreviewHud UWBP_HUDBase_C
---@field UIElementsLoaded boolean
---@field DefaultVideoColorblind TArray<int32>
---@field DefaultVideoFX TArray<int32>
---@field CollectibleImages TArray<UTexture2D>
---@field LastFocusedWidget UWBP_SettingBase_C
---@field LastFocusedTab UWBP_SettingsTabBtn_C
---@field FocusKeeper FWBP_VideoSettings_CFocusKeeper
---@field FocusKeeperTab FWBP_VideoSettings_CFocusKeeperTab
---@field ScreenSettingsLastVisibility boolean
---@field FocusKeeperHeader FWBP_VideoSettings_CFocusKeeperHeader
---@field WindowedModeDefault ETouristWindowedMode
---@field bWindowsPerformanceLoading boolean
---@field HUDClass TSubclassOf<AHUD>
---@field ApplyingVideoSettings FWBP_VideoSettings_CApplyingVideoSettings
---@field UpdatingScreenValues boolean
---@field DisplayIDs TArray<FString>
UWBP_VideoSettings_C = {}

---@param resolution FIntPoint
function UWBP_VideoSettings_C:ReadSpinnerResolution(resolution) end
---@param AspectRatioIndex int32
function UWBP_VideoSettings_C:ReadSpinnerAspectRatio(AspectRatioIndex) end
---@param DisplayModeIndex int32
---@param WindowedMode ETouristWindowedMode
function UWBP_VideoSettings_C:ReadSpinnerDisplayMode(DisplayModeIndex, WindowedMode) end
---@param MonitorID FString
function UWBP_VideoSettings_C:ReadSpinnerMonitorId(MonitorID) end
---@param ChangesToSave boolean
UWBP_VideoSettings_C['Is There Any Display Change'] = function(ChangesToSave) end
---@param FromBackup boolean
function UWBP_VideoSettings_C:SaveScreenSettings(FromBackup) end
---@param FromBackup boolean
function UWBP_VideoSettings_C:RequestApplyScreenSettings(FromBackup) end
function UWBP_VideoSettings_C:UpdateDisplaySettingsVisibility() end
---@param GetSaveGameData boolean
function UWBP_VideoSettings_C:UpdateResolutionValues(GetSaveGameData) end
---@param GetSaveGameData boolean
function UWBP_VideoSettings_C:UpdateAspectRatioValues(GetSaveGameData) end
---@param GetSaveGameData boolean
function UWBP_VideoSettings_C:UpdateDisplayModeValues(GetSaveGameData) end
---@param GetSaveGameData boolean
function UWBP_VideoSettings_C:UpdateDisplayMonitorValues(GetSaveGameData) end
---@param ScreenSetting EScreenSettings::Type
---@param GetSaveGameData boolean
UWBP_VideoSettings_C['Update Screen Settings Values'] = function(ScreenSetting, GetSaveGameData) end
function UWBP_VideoSettings_C:ApplyColourBlindSettings() end
---@param index int32
function UWBP_VideoSettings_C:GetCurrentHUDPerformanceIndex(index) end
---@param HUD_Enum_Index EUltrawideHUDSettings
function UWBP_VideoSettings_C:GetCurrentHUDPerformanceEnum(HUD_Enum_Index) end
---@param index int32
function UWBP_VideoSettings_C:GetCurrentHUDUltrawideIndex(index) end
function UWBP_VideoSettings_C:UpdateUltrawideOptions() end
---@param HUD_Enum_Index EUltrawideHUDSettings
function UWBP_VideoSettings_C:GetCurrentHUDUltrawideEnum(HUD_Enum_Index) end
function UWBP_VideoSettings_C:RestoreVideoSettings() end
function UWBP_VideoSettings_C:RestoreDefaultsPerformance() end
function UWBP_VideoSettings_C:RestoreDefaultsScreen() end
function UWBP_VideoSettings_C:RestoreDefaultsFX() end
function UWBP_VideoSettings_C:RestoreDefaultsHud() end
function UWBP_VideoSettings_C:BuildDefaultSettingsValue() end
---@param PreviewHud UWBP_HUDBase_C
function UWBP_VideoSettings_C:GetPreviewHud(PreviewHud) end
---@param MainHud UWBP_HUDBase_C
function UWBP_VideoSettings_C:GetMainHud(MainHud) end
---@param Widget UPanelWidget
function UWBP_VideoSettings_C:UpdateSettingsColor(Widget) end
function UWBP_VideoSettings_C:SaveSettings() end
function UWBP_VideoSettings_C:LoadSettings() end
---@param NewScreenName FName
function UWBP_VideoSettings_C:ReceiveExitScreen(NewScreenName) end
---@param DeltaSeconds float
---@param bForeground boolean
function UWBP_VideoSettings_C:ReceiveTickScreen(DeltaSeconds, bForeground) end
function UWBP_VideoSettings_C:BndEvt__ValueColourUI_K2Node_ComponentBoundEvent_5_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueColourUI_1_K2Node_ComponentBoundEvent_3_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueHideConsumable_K2Node_ComponentBoundEvent_8_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueHideHealthbar_K2Node_ComponentBoundEvent_9_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueHideProficiency_K2Node_ComponentBoundEvent_10_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueHideAltFire_K2Node_ComponentBoundEvent_13_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueHideAdrenalineBar_K2Node_ComponentBoundEvent_15_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueHideCollectibles_K2Node_ComponentBoundEvent_16_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__Valuemotionblur_K2Node_ComponentBoundEvent_19_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueUIVFX_K2Node_ComponentBoundEvent_20_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__WBP_SettingSpinner_Subtitles_K2Node_ComponentBoundEvent_11_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueColourBlindStrength_K2Node_ComponentBoundEvent_0_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueDynamicHUD_K2Node_ComponentBoundEvent_21_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueCollectiblesPallet_K2Node_ComponentBoundEvent_23_OnValueChanged__DelegateSignature() end
---@param SettingPreviewType PreviewPanelType
function UWBP_VideoSettings_C:BndEvt__SettingDynamicHUD_K2Node_ComponentBoundEvent_2_FocusReceived__DelegateSignature(SettingPreviewType) end
function UWBP_VideoSettings_C:RestoreToDefault() end
function UWBP_VideoSettings_C:BndEvt__valueCrosshairScale_K2Node_ComponentBoundEvent_4_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueCrosshairThickness_K2Node_ComponentBoundEvent_6_OnValueChanged__DelegateSignature() end
---@param SettingPreviewType PreviewPanelType
function UWBP_VideoSettings_C:BndEvt__SettingCollectiblesPallet_K2Node_ComponentBoundEvent_7_FocusReceived__DelegateSignature(SettingPreviewType) end
function UWBP_VideoSettings_C:BndEvt__ValueHideSessionTime_K2Node_ComponentBoundEvent_12_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__HUDSafeZoneButton_K2Node_ComponentBoundEvent_25_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:ApplyChangesWarning() end
function UWBP_VideoSettings_C:BP_DiscardChanges() end
function UWBP_VideoSettings_C:BndEvt__ValueUIContrast_K2Node_ComponentBoundEvent_17_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueBloom_K2Node_ComponentBoundEvent_1_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__BrightnessButton_K2Node_ComponentBoundEvent_18_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueUIVFX_K2Node_ComponentBoundEvent_22_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BP_ApplyChanges() end
function UWBP_VideoSettings_C:BndEvt__ValueUltrawideSupport_K2Node_ComponentBoundEvent_26_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueWindowsFPS_K2Node_ComponentBoundEvent_28_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueWindowsCPUUse_K2Node_ComponentBoundEvent_29_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueWindowsCPUTemp_K2Node_ComponentBoundEvent_30_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueWindowsGPUUse_K2Node_ComponentBoundEvent_31_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueWindowsGPUTemp_K2Node_ComponentBoundEvent_32_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueWindowsGPUSpeed_K2Node_ComponentBoundEvent_33_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueWindowsVRAMUse_K2Node_ComponentBoundEvent_34_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueCinematicUltrawideSupport_K2Node_ComponentBoundEvent_27_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BP_ExitApplyingVideo() end
function UWBP_VideoSettings_C:BP_OnExitRestoreVideoScreen() end
function UWBP_VideoSettings_C:BndEvt__ValueHUDUltrawideSupport_K2Node_ComponentBoundEvent_35_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueWindowsFontSize_K2Node_ComponentBoundEvent_24_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueAltFireIndicator_K2Node_ComponentBoundEvent_38_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueHideBossHealth_K2Node_ComponentBoundEvent_39_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueHideEnemyHealth_K2Node_ComponentBoundEvent_40_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueHUDUltrawideSupport_1_K2Node_ComponentBoundEvent_16_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueAspectRatio_K2Node_ComponentBoundEvent_14_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueDisplayMode_K2Node_ComponentBoundEvent_36_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueDisplayMonitor_K2Node_ComponentBoundEvent_24_OnValueChanged__DelegateSignature() end
---@param SettingWidget UWBP_SettingBase_C
function UWBP_VideoSettings_C:BP_FocusKeeper(SettingWidget) end
---@param SettingTab UWBP_SettingsTabBtn_C
function UWBP_VideoSettings_C:BP_FocusKepper(SettingTab) end
function UWBP_VideoSettings_C:BP_FocusKeeperHeader() end
---@param IsDesignTime boolean
function UWBP_VideoSettings_C:PreConstruct(IsDesignTime) end
---@param OldScreenName FName
---@param bFirst boolean
function UWBP_VideoSettings_C:ReceiveEnterScreen(OldScreenName, bFirst) end
function UWBP_VideoSettings_C:Construct() end
function UWBP_VideoSettings_C:InputAction_SystemMenu() end
function UWBP_VideoSettings_C:RearrangeMonitorOptions() end
function UWBP_VideoSettings_C:BndEvt__ValueWindowsLatency_K2Node_ComponentBoundEvent_14_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueHideWeaponTrait_K2Node_ComponentBoundEvent_36_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:BndEvt__ValueHideCoop_K2Node_ComponentBoundEvent_37_OnValueChanged__DelegateSignature() end
function UWBP_VideoSettings_C:ControllerSettingsChanged() end
---@param EntryPoint int32
function UWBP_VideoSettings_C:ExecuteUbergraph_WBP_VideoSettings(EntryPoint) end
function UWBP_VideoSettings_C:ApplyingVideoSettings__DelegateSignature() end
function UWBP_VideoSettings_C:FocusKeeperHeader__DelegateSignature() end
---@param SettingTab UWBP_SettingsTabBtn_C
function UWBP_VideoSettings_C:FocusKeeperTab__DelegateSignature(SettingTab) end
---@param SettingWidget UWBP_SettingBase_C
function UWBP_VideoSettings_C:FocusKeeper__DelegateSignature(SettingWidget) end
function UWBP_VideoSettings_C:OnInputAction_SystemMenu__DelegateSignature() end


