---@meta

---@class UWBP_TimelessTower_Summary_C : USocialChallengeGameOverWidget
---@field UberGraphFrame FPointerToUberGraphFrame
---@field TotalScoreLabelFadeIn UWidgetAnimation
---@field ObjectivesHeaderAnim UWidgetAnimation
---@field SkillHeaderAnim UWidgetAnimation
---@field ExplorerHeaderAnim UWidgetAnimation
---@field CombatHeaderAnim UWidgetAnimation
---@field Intro_1 UWidgetAnimation
---@field LeaderboardAnim UWidgetAnimation
---@field ScoreToRankAnim UWidgetAnimation
---@field Best_ImageImageGlow UImage
---@field Challenge_1 UVerticalBox
---@field ChallengeContentOverlay UOverlay
---@field ChallengeStats_Border UBorder
---@field CombatBorder UBorder
---@field CombatGrid UGridPanel
---@field CombatHeaderOverlay UOverlay
---@field ExplorerBorder_1 UBorder
---@field ExplorerGrid UGridPanel
---@field ExplorerHeaderOverlay UOverlay
---@field FullBackImage_2 UImage
---@field MainOverlay UOverlay
---@field Multiplayer_Rates_Average UHMQRichTextBlock
---@field Multiplayer_Rates_Final UHMQRichTextBlock
---@field Multiplayer_Rates_Highest UHMQRichTextBlock
---@field NoDataOverlay UOverlay
---@field ObjectiveBorder UBorder
---@field ObjectiveGrid UGridPanel
---@field ObjectivesHeaderOverlay UOverlay
---@field Overlay_0 UOverlay
---@field RankBacking UImage
---@field RankBacking_1 UImage
---@field RankBacking_2 UImage
---@field RankBacking_3 UImage
---@field RankScoreBorder UBorder
---@field RankTextBox UHMQRichTextBlock
---@field RankTextBox_Label UHMQRichTextBlock
---@field RankVerticalBox UHorizontalBox
---@field RichText_ChallengeStats_4 UHMQRichTextBlock
---@field RichText_Combat UHMQRichTextBlock
---@field RichText_Combat_CromBlue UHMQRichTextBlock
---@field RichText_Combat_CromRed UHMQRichTextBlock
---@field RichText_Combat_White UHMQRichTextBlock
---@field RichText_ConnectionStatus UHMQRichTextBlock
---@field RichText_Explorer UHMQRichTextBlock
---@field RichText_Explorer_CromBlue UHMQRichTextBlock
---@field RichText_Explorer_CromRed UHMQRichTextBlock
---@field RichText_Explorer_White UHMQRichTextBlock
---@field RichText_Objectives UHMQRichTextBlock
---@field RichText_Objectives_CromBlue UHMQRichTextBlock
---@field RichText_Objectives_CromRed UHMQRichTextBlock
---@field RichText_Objectives_White UHMQRichTextBlock
---@field RichText_Skill UHMQRichTextBlock
---@field RichText_Skill_CromBlue UHMQRichTextBlock
---@field RichText_Skill_CromRed UHMQRichTextBlock
---@field RichText_Skill_White UHMQRichTextBlock
---@field RTB_PhaseLabel UHMQRichTextBlock
---@field RTB_PhaseLabel_Best_Sub UHMQRichTextBlock
---@field RTB_PhaseLabel_Spacer UHMQRichTextBlock
---@field RTB_PhaseLabel_ThisRun UHMQRichTextBlock
---@field RTB_PhaseNewBest UHMQRichTextBlock
---@field RTB_PhaseNumber_Best UHMQRichTextBlock
---@field RTB_PhaseNumber_ThisRun UHMQRichTextBlock
---@field RTB_RoomLabel_1 UHMQRichTextBlock
---@field RTB_RoomNumber_Best UHMQRichTextBlock
---@field RTB_RoomNumber_ThisRun UHMQRichTextBlock
---@field SkillBorder UBorder
---@field SkillGrid UGridPanel
---@field SkillHeaderOverlay UOverlay
---@field TotalPlayers UHMQRichTextBlock
---@field WBP_BorderHeadingText_10 UWBP_BorderHeadingText_C
---@field WBP_BorderHeadingText_11 UWBP_BorderHeadingText_C
---@field WBP_BorderHeadingText_13 UWBP_BorderHeadingText_C
---@field WBP_BorderTopHeading_3 UWBP_BorderTopHeading_C
---@field WBP_BorderTopHeading_4 UWBP_BorderTopHeading_C
---@field WBP_BorderTopHeading_5 UWBP_BorderTopHeading_C
---@field WBP_BorderTopHeading_6 UWBP_BorderTopHeading_C
---@field WBP_BrushImage UWBP_BrushImage_C
---@field WBP_ChallengePost_RankBar UWBP_ChallengePost_RankBar_C
---@field WBP_ChallengePost_ScoreBar UWBP_ChallengePost_ScoreBar_C
---@field WBP_HorizontalLinePlain_White_19 UWBP_HorizontalLinePlain_White_C
---@field WBP_PromptBar UWBP_PromptBar_C
---@field WBP_PromptBarItem_Return UWBP_PromptBarItem_C
---@field WBP_SkipProgress UWBP_SkipProgress_C
---@field WBP_TimelessTower_TotalScore UWBP_TimelessTower_TotalScore_C
---@field RankSetup boolean
---@field CombatReward int32
---@field CombatDeduction int32
---@field ExplorerReward int32
---@field ExplorerDeduction int32
---@field SkillReward int32
---@field SkillDeduction int32
---@field ObjectivesReward int32
---@field ObjectivesDeduction int32
---@field FadeInDelay float
---@field PlayerRank int64
---@field ChallangeDetailsFinished FWBP_TimelessTower_Summary_CChallangeDetailsFinished
---@field ReturnVal int32
---@field ScoresSetup boolean
---@field ScoreGroupDelay float
---@field BonusWidgetList TArray<UWBP_ChallengePostReward_C>
---@field CurrentBonusGroupIndex int32
---@field GlitchEffectTimerSecs float
---@field GlitchEffectEnabled boolean
---@field CurrentHeaderIndex int32
---@field HeaderArray TArray<UWidgetAnimation>
---@field IsTotalScoreLabelFadeIn boolean
---@field CurrentScore int32
---@field CurrentScoreGroupIndex int32
---@field connected boolean
---@field Started boolean
---@field ScoreSubmitPending boolean
---@field ScoreSubmitted boolean
---@field InRankView boolean
---@field ScoreComplete boolean
---@field CanReturn boolean
---@field CachedTTChallengeManager UTimelessTowerManager
---@field CachedActiveTTGameMode UTouristArcadePlayMode
---@field GlitchColourChangeArray TArray<UBP_ChallengePostTextGlitch_C>
---@field TotalRankings int64
---@field Audio_PositiveIsChanging boolean
---@field Audio_NegativeIsChanging boolean
---@field Audio_PositiveTextIsFadingIn boolean
---@field Audio_NegativeTextIsFadingIn boolean
---@field Audio_ScoreBarUpdateCount float
---@field IsExiting boolean
---@field FadeColor FLinearColor
---@field LocalisationArray TArray<FString>
---@field ChallengeId int64
---@field TimeCompleteFormat FText
---@field EnableAstraLoading boolean
---@field Audio_MenuDestroyed UAkAudioEvent
---@field Audio_StopPositiveSoundSpam boolean
---@field TotalScore int32
---@field CanSkip boolean
---@field SkipDown boolean
---@field Skipping boolean
---@field SkipTime float
---@field SkipDelta float
---@field NumberOfScoreColumns int32
---@field FirstBonusGroup boolean
---@field CombatText FText
---@field ExplorerText FText
---@field SkillText FText
---@field ObjectivesText FText
---@field SetupAndStarted boolean
---@field RankObtained boolean
---@field ScoreBarFinished FWBP_TimelessTower_Summary_CScoreBarFinished
UWBP_TimelessTower_Summary_C = {}

function UWBP_TimelessTower_Summary_C:SequenceEvent__ENTRYPOINTWBP_TimelessTower_Summary_3() end
function UWBP_TimelessTower_Summary_C:SequenceEvent__ENTRYPOINTWBP_TimelessTower_Summary_2() end
function UWBP_TimelessTower_Summary_C:SequenceEvent__ENTRYPOINTWBP_TimelessTower_Summary_1() end
function UWBP_TimelessTower_Summary_C:SequenceEvent__ENTRYPOINTWBP_TimelessTower_Summary_0() end
function UWBP_TimelessTower_Summary_C:TagSummaryText() end
---@param CurrentWidgetList TArray<UWBP_ChallengePostReward_C>
function UWBP_TimelessTower_Summary_C:CopyBonusListToCollection(CurrentWidgetList) end
function UWBP_TimelessTower_Summary_C:PlayAnim_Test() end
---@param DeltaTime float
function UWBP_TimelessTower_Summary_C:UpdateSkipProgress(DeltaTime) end
function UWBP_TimelessTower_Summary_C:ScoreBarDone() end
function UWBP_TimelessTower_Summary_C:Skip() end
function UWBP_TimelessTower_Summary_C:AudioScoreBarNoChangePositive() end
function UWBP_TimelessTower_Summary_C:AudioScoreBarChangePositiveStop() end
function UWBP_TimelessTower_Summary_C:AudioScoreBarChangePositiveStart() end
function UWBP_TimelessTower_Summary_C:AudioScoreBarEnd() end
function UWBP_TimelessTower_Summary_C:AudioScoreBarBegin() end
function UWBP_TimelessTower_Summary_C:AudioScoreItemTextFadeStopPositive() end
function UWBP_TimelessTower_Summary_C:AudioScoreItemTextFadeStartPositive() end
UWBP_TimelessTower_Summary_C['Audio Leaderboard Appear'] = function() end
function UWBP_TimelessTower_Summary_C:AudioRankBarStart() end
function UWBP_TimelessTower_Summary_C:AudioGroupTitleFadeIn() end
function UWBP_TimelessTower_Summary_C:AudioMainScreenStarted() end
---@param Primary UHMQRichTextBlock
---@param white UHMQRichTextBlock
---@param Blue UHMQRichTextBlock
---@param red UHMQRichTextBlock
UWBP_TimelessTower_Summary_C['Add Glitch Effect Group'] = function(Primary, white, Blue, red) end
function UWBP_TimelessTower_Summary_C:SetupGlitchEffect() end
---@param ReferencesOk boolean
function UWBP_TimelessTower_Summary_C:CachedReferencesOk(ReferencesOk) end
function UWBP_TimelessTower_Summary_C:SetupCachedReferences() end
---@param StringArray TArray<FString>
---@param StringIndex int32
---@param RichTextBox UHMQRichTextBlock
---@param RichTextBox2 UHMQRichTextBlock
function UWBP_TimelessTower_Summary_C:SetTextFromArrayElement(StringArray, StringIndex, RichTextBox, RichTextBox2) end
---@param Enabled boolean
function UWBP_TimelessTower_Summary_C:SetCanReturn(Enabled) end
function UWBP_TimelessTower_Summary_C:SetupAndStart() end
function UWBP_TimelessTower_Summary_C:SwitchToRankView() end
function UWBP_TimelessTower_Summary_C:ShowAndStart() end
function UWBP_TimelessTower_Summary_C:SetupHeaderAnimArray() end
function UWBP_TimelessTower_Summary_C:BonusFadeInFinished() end
function UWBP_TimelessTower_Summary_C:BonusAnimationFinishedCallback() end
---@param MaxNumberPlayers int64
function UWBP_TimelessTower_Summary_C:SetMaxRankText(MaxNumberPlayers) end
---@param ItemIndex int32
---@param value int32
---@param NegetiveBonus boolean
---@param ClampedValue int32
function UWBP_TimelessTower_Summary_C:AddToGroupTotal(ItemIndex, value, NegetiveBonus, ClampedValue) end
function UWBP_TimelessTower_Summary_C:SetupRank() end
---@param Success boolean
function UWBP_TimelessTower_Summary_C:Setup(Success) end
---@param ColumnIndex int32
---@param GridWidget UGridPanel
function UWBP_TimelessTower_Summary_C:GetBonusGroupContainer(ColumnIndex, GridWidget) end
function UWBP_TimelessTower_Summary_C:SetupStats() end
function UWBP_TimelessTower_Summary_C:SetLabels() end
---@param AddPlusOrMinus boolean
---@param PlussOrMinus boolean
---@param Integer int64
---@param TextBox UHMQRichTextBlock
function UWBP_TimelessTower_Summary_C:SetValueText(AddPlusOrMinus, PlussOrMinus, Integer, TextBox) end
function UWBP_TimelessTower_Summary_C:HeaderAnimTrigger() end
function UWBP_TimelessTower_Summary_C:Construct() end
function UWBP_TimelessTower_Summary_C:ScoreBarComplete() end
function UWBP_TimelessTower_Summary_C:RankFadeAnimationFinished() end
function UWBP_TimelessTower_Summary_C:RankAnimationFinsihed() end
function UWBP_TimelessTower_Summary_C:LeaderboardFadeInFinished() end
---@param Rank int32
function UWBP_TimelessTower_Summary_C:RankBarRankUpdatedEvent(Rank) end
---@param Score int32
function UWBP_TimelessTower_Summary_C:ScoreBarScoreUpdated(Score) end
function UWBP_TimelessTower_Summary_C:IntroAnimFinishedEvent() end
---@param MyGeometry FGeometry
---@param InDeltaTime float
function UWBP_TimelessTower_Summary_C:Tick(MyGeometry, InDeltaTime) end
function UWBP_TimelessTower_Summary_C:Destruct() end
function UWBP_TimelessTower_Summary_C:ReceiveDestroyScreen() end
---@param IsDesignTime boolean
function UWBP_TimelessTower_Summary_C:PreConstruct(IsDesignTime) end
---@param TotalRankings int64
function UWBP_TimelessTower_Summary_C:OnTotalRankRetrieved(TotalRankings) end
---@param CurrentRankings int64
function UWBP_TimelessTower_Summary_C:OnRankRetrieved(CurrentRankings) end
---@param Manager UTouristArcadeManager
function UWBP_TimelessTower_Summary_C:CustomEvent(Manager) end
---@param EntryPoint int32
function UWBP_TimelessTower_Summary_C:ExecuteUbergraph_WBP_TimelessTower_Summary(EntryPoint) end
function UWBP_TimelessTower_Summary_C:ScoreBarFinished__DelegateSignature() end
function UWBP_TimelessTower_Summary_C:ChallangeDetailsFinished__DelegateSignature() end


