---@meta

---@class UWBP_ChallengeEquipmentWeapon_C : UTouristWidgetBase
---@field UberGraphFrame FPointerToUberGraphFrame
---@field Anim_IntroGlow UWidgetAnimation
---@field Anim_IntroGlow_Altfire UWidgetAnimation
---@field Anim_GunNameFocus UWidgetAnimation
---@field Anim_Focus UWidgetAnimation
---@field Anim_AltFireFocus UWidgetAnimation
---@field AltFire_FocusHoveringButton UFocusHoveringButton
---@field BackgroundGrid UImage
---@field Border_AltFire UBorder
---@field Border_AltFireName UBorder
---@field BrushImage_GlowLevel UWBP_BrushImage_C
---@field BrushImage_GlowWeapon UWBP_BrushImage_C
---@field HorizontalLine_BelowAltFire UWBP_HorizontalLine_C
---@field HorizontalLine_BelowStats UWBP_HorizontalLine_C
---@field HorizontalLine_BelowTraits UWBP_HorizontalLine_C
---@field Image_AltFire UImage
---@field Image_AnimBlock UImage
---@field Image_AnimGlow UImage
---@field Image_Level UImage
---@field Image_Scanline_FocusHovering UFocusHoveringButton
---@field RichText_AltFire UHMQRichTextBlock
---@field RichText_DPS UHMQRichTextBlock
---@field RichText_InsideTitle UHMQRichTextBlock
---@field RichText_Level UHMQRichTextBlock
---@field RichText_TraitDesc UHMQRichTextBlock
---@field Text_AltFire UTextBlock
---@field VerticalBox_AltFire UVerticalBox
---@field VerticalBox_Content UVerticalBox
---@field VerticalBox_Stats UVerticalBox
---@field VerticalBox_Traits UVerticalBox
---@field VerticalLine_AltFire_1 UWBP_VerticalLine_C
---@field WBP_BrushImage UWBP_BrushImage_C
---@field WBP_BrushImage_1 UWBP_BrushImage_C
---@field WBP_CaptureImage2 UWBP_CaptureImage2_C
---@field WBP_HorizontalLine_2 UWBP_HorizontalLine_C
---@field WBP_HorizontalLine_3 UWBP_HorizontalLine_C
---@field WBP_HorizontalLine_4 UWBP_HorizontalLine_C
---@field WBP_HorizontalLine_5 UWBP_HorizontalLine_C
---@field WBP_HorizontalLine_96 UWBP_HorizontalLine_C
---@field WBP_HorizontalLine_126 UWBP_HorizontalLine_C
---@field WBP_MenuBox_MP UWBP_MenuBox_MP_C
---@field WBP_VerticalLine UWBP_VerticalLine_C
---@field WBP_VerticalLine_1 UWBP_VerticalLine_C
---@field WBP_VerticalLine_2 UWBP_VerticalLine_C
---@field WBP_VerticalLine_3 UWBP_VerticalLine_C
---@field WBP_VerticalLine_4 UWBP_VerticalLine_C
---@field WBP_VerticalLine_5 UWBP_VerticalLine_C
---@field WBP_VerticalLine_6 UWBP_VerticalLine_C
---@field WBP_VerticalLine_7 UWBP_VerticalLine_C
---@field WBP_VerticalLine_8 UWBP_VerticalLine_C
---@field WBP_VerticalLine_136 UWBP_VerticalLine_C
---@field WeaponName_FocusHovering UFocusHoveringButton
---@field TraitVisuals UBP_WeaponTraitVisuals_C
---@field TraitVisuals_SoftRef TSoftObjectPtr<UBP_WeaponTraitVisuals_C>
---@field WidgetStyle_AltFire UBP_WidgetStyle_C
---@field WidgetStyle_Focus UBP_WidgetStyle_C
---@field WidgetStyle_NoFocus UBP_WidgetStyle_C
---@field WidgetStyle_Level UBP_WidgetStyle_C
---@field FocusIndex int32
---@field Text_AltFireDesc FText
---@field HasAltFire boolean
---@field AltFireFocusPhase float
---@field FocusPhase float
---@field OnFocusEscape FWBP_ChallengeEquipmentWeapon_COnFocusEscape
---@field FocusWrapping boolean
---@field WeaponRotationSpeedOverride float
---@field WeaponRotation float
---@field CurrentWeaponObject APlayerGun
---@field WidgetStyle_Icon_Focus UBP_WidgetStyle_C
---@field LocalisationArray TArray<FString>
---@field Text_AltFireDeco FText
---@field GunDisplayDesc FText
---@field GunDisplayName FText
---@field OnMouseFocused FWBP_ChallengeEquipmentWeapon_COnMouseFocused
---@field FocusKeeper FWBP_ChallengeEquipmentWeapon_CFocusKeeper
---@field bIsHighlighted boolean
---@field bIsFocused boolean
UWBP_ChallengeEquipmentWeapon_C = {}

---@param WeaponRotationSpeedOverride float
function UWBP_ChallengeEquipmentWeapon_C:SetWeaponRotationSpeedOverride(WeaponRotationSpeedOverride) end
---@param Result boolean
function UWBP_ChallengeEquipmentWeapon_C:AcceptsFocus(Result) end
---@param phase float
function UWBP_ChallengeEquipmentWeapon_C:SetFocusPhase(phase) end
---@param phase float
function UWBP_ChallengeEquipmentWeapon_C:SetAltFireFocusPhase(phase) end
function UWBP_ChallengeEquipmentWeapon_C:Beep() end
---@param FocusIndex int32
function UWBP_ChallengeEquipmentWeapon_C:SetFocusIndex(FocusIndex) end
---@param MyGeometry FGeometry
---@param InKeyEvent FKeyEvent
---@return FEventReply
function UWBP_ChallengeEquipmentWeapon_C:OnKeyDown(MyGeometry, InKeyEvent) end
---@param MyGeometry FGeometry
---@param InFocusEvent FFocusEvent
---@return FEventReply
function UWBP_ChallengeEquipmentWeapon_C:OnFocusReceived(MyGeometry, InFocusEvent) end
---@param Loaded UObject
function UWBP_ChallengeEquipmentWeapon_C:OnLoaded_4ADCFD8F42BCBF7B2056F9BCC4A76EB0(Loaded) end
---@param IsDesignTime boolean
function UWBP_ChallengeEquipmentWeapon_C:PreConstruct(IsDesignTime) end
---@param InFocusEvent FFocusEvent
function UWBP_ChallengeEquipmentWeapon_C:OnFocusLost(InFocusEvent) end
function UWBP_ChallengeEquipmentWeapon_C:Construct() end
---@param Weapon APlayerGun
function UWBP_ChallengeEquipmentWeapon_C:Setup(Weapon) end
---@param MyGeometry FGeometry
---@param InDeltaTime float
function UWBP_ChallengeEquipmentWeapon_C:Tick(MyGeometry, InDeltaTime) end
---@param Widget UUserWidget
function UWBP_ChallengeEquipmentWeapon_C:OnTraitMouseFocused(Widget) end
function UWBP_ChallengeEquipmentWeapon_C:BndEvt__WeaponName_FocusHovering_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature() end
function UWBP_ChallengeEquipmentWeapon_C:StealFocus() end
function UWBP_ChallengeEquipmentWeapon_C:BndEvt__AltFire_FocusHoveringButton_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature() end
---@param EntryPoint int32
function UWBP_ChallengeEquipmentWeapon_C:ExecuteUbergraph_WBP_ChallengeEquipmentWeapon(EntryPoint) end
---@param FocusIndex int32
function UWBP_ChallengeEquipmentWeapon_C:FocusKeeper__DelegateSignature(FocusIndex) end
---@param Widget UUserWidget
function UWBP_ChallengeEquipmentWeapon_C:OnMouseFocused__DelegateSignature(Widget) end
---@param side EHorizontalAlignment
function UWBP_ChallengeEquipmentWeapon_C:OnFocusEscape__DelegateSignature(side) end


