---@meta

---@class UWBP_ControllerOverride2Panel_C : USysSettingsTab
---@field UberGraphFrame FPointerToUberGraphFrame
---@field CanvasPanel_0 UCanvasPanel
---@field CustomizeButton UWBP_SettingsTabBtn_C
---@field KeyMappingScrollBox UScrollBox
---@field LineBottom UWBP_HorizontalLinePlain_C
---@field SettingAim UWBP_SettingBase_C
---@field SettingAimUp UWBP_SettingBase_C
---@field SettingAltFire UWBP_SettingBase_C
---@field SettingAreaScan UWBP_SettingBase_C
---@field SettingBasePreset UWBP_SettingBase_C
---@field SettingConsume UWBP_SettingBase_C
---@field SettingDash UWBP_SettingBase_C
---@field SettingFire UWBP_SettingBase_C
---@field SettingFocusFire UWBP_SettingBase_C
---@field SettingGameMenu UWBP_SettingBase_C
---@field SettingInteract UWBP_SettingBase_C
---@field SettingJump UWBP_SettingBase_C
---@field SettingMelee UWBP_SettingBase_C
---@field SettingMove UWBP_SettingBase_C
---@field SettingMoveRight UWBP_SettingBase_C
---@field SettingPhotoMode UWBP_SettingBase_C
---@field SettingRotate UWBP_SettingBase_C
---@field SettingSprint UWBP_SettingBase_C
---@field SettingSwap UWBP_SettingBase_C
---@field SettingSwitchConsume UWBP_SettingBase_C
---@field SettingSwitchConsumeLeft UWBP_SettingBase_C
---@field SettingSwitchToggleExtendedHud UWBP_SettingBase_C
---@field SettingTriggers UWBP_SettingBase_C
---@field SettingWristComputer UWBP_SettingBase_C
---@field ValueAim UWBP_ControllerKeyMap_C
---@field ValueAimUp UWBP_ControllerKeyMap_C
---@field ValueAltFire UWBP_ControllerKeyMap_C
---@field ValueAreaScan UWBP_ControllerKeyMap_C
---@field ValueBase UWBP_SettingSpinner_C
---@field ValueConsumable UWBP_ControllerKeyMap_C
---@field ValueDash UWBP_ControllerKeyMap_C
---@field ValueFire UWBP_ControllerKeyMap_C
---@field ValueFocusFire UWBP_ControllerKeyMap_C
---@field ValueGameMenu UWBP_ControllerKeyMap_C
---@field ValueInteract UWBP_ControllerKeyMap_C
---@field ValueJump UWBP_ControllerKeyMap_C
---@field ValueMelee UWBP_ControllerKeyMap_C
---@field ValueMove UWBP_ControllerKeyMap_C
---@field ValueMoveRight UWBP_ControllerKeyMap_C
---@field ValuePhotoMode UWBP_ControllerKeyMap_C
---@field ValueRotate UWBP_SettingSpinner_C
---@field ValueSprint UWBP_ControllerKeyMap_C
---@field ValueSwap UWBP_SettingSpinner_C
---@field ValueSwitchConsumable UWBP_ControllerKeyMap_C
---@field ValueSwitchConsumeLeft UWBP_ControllerKeyMap_C
---@field ValueToggleExtendedHud UWBP_ControllerKeyMap_C
---@field ValueTrigger UWBP_SettingSpinner_C
---@field ValueWristComputer UWBP_ControllerKeyMap_C
---@field OnInputAction_SystemMenu FWBP_ControllerOverride2Panel_COnInputAction_SystemMenu
---@field WidgetStyle UBP_WidgetStyle_C
---@field NoKeySelected FKey
---@field WidgetStyle_2 UBP_WidgetStyle_C
---@field ControllerPresets UBP_ControllerPresets_C
---@field IsPreviewingControls boolean
---@field ChangesWarning boolean
---@field IsRestoringToDefault boolean
---@field LeftStickKeys TArray<FKey>
---@field RightStickKeys TArray<FKey>
---@field ActionToRebind1 FName
---@field ActionToRebind2 FName
---@field AxisScale float
---@field CachedParentSysSettings UWBP_SystemSettings_3Panel_C
---@field AltFireInTrigger FText
---@field AltFireNotInTrigger FText
---@field AKeyHasChanged boolean
---@field AllActions TArray<FName>
---@field NoneKey FKey
---@field InitialBase boolean
---@field InitialSwap boolean
---@field InitialRotate boolean
---@field LeftTrigger FKey
---@field RightTrigger FKey
---@field InitialTrigger boolean
---@field DefaultEmpty FText
---@field AllKeys TArray<FKey>
---@field IsKeyWithNoAction boolean
---@field ExitToGame boolean
---@field SettingsExitBackToGameSound UAkAudioEvent
---@field ActionToBeUnbinded FText
---@field KeyToBeUnbinded FKey
---@field FromRebindSettings boolean
---@field OriginalInputActions TArray<FHMQInputAction>
---@field OriginalInputAxes TArray<FHMQInputAxis>
---@field LastFocusedRebinding UWBP_SettingValueBase_C
---@field FocusKeeperRebinding FWBP_ControllerOverride2Panel_CFocusKeeperRebinding
---@field FocusKeeper FWBP_ControllerOverride2Panel_CFocusKeeper
---@field LastFocusedWidget UWBP_SettingBase_C
---@field SonyTriggersTitle FText
---@field XboxTriggersTitle FText
---@field SonyTriggersDescription FText
---@field XboxTriggersDescription FText
---@field SwitchTriggersTitle FText
---@field SwitchTriggersDescription FText
UWBP_ControllerOverride2Panel_C = {}

---@param Enable boolean
function UWBP_ControllerOverride2Panel_C:ChangeKeybindingVisibility(Enable) end
---@param UnboundKeyDisplay FKey
function UWBP_ControllerOverride2Panel_C:FindActionToBeUnbound(UnboundKeyDisplay) end
---@param ReboundName FName
function UWBP_ControllerOverride2Panel_C:FindReboundSetting(ReboundName) end
function UWBP_ControllerOverride2Panel_C:DisableReboundWarning() end
function UWBP_ControllerOverride2Panel_C:CheckIfChangesOccured() end
function UWBP_ControllerOverride2Panel_C:AssingAltFireKey() end
---@param InputName FName
---@param LocalText FText
function UWBP_ControllerOverride2Panel_C:GetLocalAxisName(InputName, LocalText) end
---@param InputName FName
---@param LocalText FText
function UWBP_ControllerOverride2Panel_C:GetLocalActionName(InputName, LocalText) end
function UWBP_ControllerOverride2Panel_C:KeyBound() end
---@return UWidget
function UWBP_ControllerOverride2Panel_C:CurrentSelectOption() end
function UWBP_ControllerOverride2Panel_C:ApplyAltFireChanges() end
function UWBP_ControllerOverride2Panel_C:RestoreAdaptiveTriggers() end
function UWBP_ControllerOverride2Panel_C:SwapTriggers() end
function UWBP_ControllerOverride2Panel_C:UpdatingListOnBasedPreset() end
function UWBP_ControllerOverride2Panel_C:RotateController() end
---@param Navigation EUINavigation
---@return UWidget
function UWBP_ControllerOverride2Panel_C:ControllerSettingNavigateUp(Navigation) end
function UWBP_ControllerOverride2Panel_C:BuildStickKeysArray() end
function UWBP_ControllerOverride2Panel_C:SwapSticks() end
function UWBP_ControllerOverride2Panel_C:SaveSettings() end
function UWBP_ControllerOverride2Panel_C:LoadMappings() end
function UWBP_ControllerOverride2Panel_C:LoadSettings() end
---@param IsDesignTime boolean
function UWBP_ControllerOverride2Panel_C:PreConstruct(IsDesignTime) end
function UWBP_ControllerOverride2Panel_C:InputAction_SystemMenu() end
function UWBP_ControllerOverride2Panel_C:BndEvt__ValueSwap_K2Node_ComponentBoundEvent_0_OnValueChanged__DelegateSignature() end
function UWBP_ControllerOverride2Panel_C:BndEvt__ValueRotate_K2Node_ComponentBoundEvent_1_OnValueChanged__DelegateSignature() end
function UWBP_ControllerOverride2Panel_C:Construct() end
function UWBP_ControllerOverride2Panel_C:BndEvt__ValueBase_K2Node_ComponentBoundEvent_2_OnValueChanged__DelegateSignature() end
function UWBP_ControllerOverride2Panel_C:BndEvt__ValueRotate_1_K2Node_ComponentBoundEvent_3_OnValueChanged__DelegateSignature() end
function UWBP_ControllerOverride2Panel_C:RestoreToDefault() end
function UWBP_ControllerOverride2Panel_C:PreviewControls() end
function UWBP_ControllerOverride2Panel_C:ApplyChangesWarning() end
---@param SettingPreviewType PreviewPanelType
function UWBP_ControllerOverride2Panel_C:BndEvt__SettingBasePreset_K2Node_ComponentBoundEvent_4_FocusReceived__DelegateSignature(SettingPreviewType) end
---@param SettingPreviewType PreviewPanelType
function UWBP_ControllerOverride2Panel_C:BndEvt__SettingSwap_K2Node_ComponentBoundEvent_5_FocusReceived__DelegateSignature(SettingPreviewType) end
---@param SettingPreviewType PreviewPanelType
function UWBP_ControllerOverride2Panel_C:BndEvt__SettingTriggers_K2Node_ComponentBoundEvent_6_FocusReceived__DelegateSignature(SettingPreviewType) end
---@param SettingPreviewType PreviewPanelType
function UWBP_ControllerOverride2Panel_C:BndEvt__SettingRotate_K2Node_ComponentBoundEvent_7_FocusReceived__DelegateSignature(SettingPreviewType) end
function UWBP_ControllerOverride2Panel_C:RestoreToDefaultsCanceled() end
function UWBP_ControllerOverride2Panel_C:ReadOriginalMappings() end
---@param Rebind_Setting UWBP_SettingValueBase_C
function UWBP_ControllerOverride2Panel_C:BP_FocusKeeperRebinding(Rebind_Setting) end
---@param SettingWidget UWBP_SettingBase_C
function UWBP_ControllerOverride2Panel_C:BP_FocusKeeper(SettingWidget) end
---@param Screen UHMQScreenWidget
---@param NewScreenName FName
function UWBP_ControllerOverride2Panel_C:RestoreToDefaultsClosed(Screen, NewScreenName) end
function UWBP_ControllerOverride2Panel_C:DefaultsRestored() end
function UWBP_ControllerOverride2Panel_C:ControllerSettingsChanged() end
---@param EntryPoint int32
function UWBP_ControllerOverride2Panel_C:ExecuteUbergraph_WBP_ControllerOverride2Panel(EntryPoint) end
---@param SettingWidget UWBP_SettingBase_C
function UWBP_ControllerOverride2Panel_C:FocusKeeper__DelegateSignature(SettingWidget) end
---@param RebindSetting UWBP_SettingValueBase_C
function UWBP_ControllerOverride2Panel_C:FocusKeeperRebinding__DelegateSignature(RebindSetting) end
function UWBP_ControllerOverride2Panel_C:OnInputAction_SystemMenu__DelegateSignature() end


