---@meta

---@class UWBP_BossHealth_C : UBossHealthWidget
---@field UberGraphFrame FPointerToUberGraphFrame
---@field HealthBar_1BarLeft UWidgetAnimation
---@field HealthBarDamage_2 UWidgetAnimation
---@field HealthBarDamage_1 UWidgetAnimation
---@field HealthBarDamage_Placeholder UWidgetAnimation
---@field HealthBarLoop_2 UWidgetAnimation
---@field HealthBarDeath UWidgetAnimation
---@field HealthBarDamage UWidgetAnimation
---@field HealthBarLoop UWidgetAnimation
---@field HealthBarAppear1 UWidgetAnimation
---@field AlienLanguage UHMQRichTextBlock
---@field Analyzing0 UHMQRichTextBlock
---@field Background UImage
---@field Background_Icon UImage
---@field Box UImage
---@field CanvasPanel_BossImage UCanvasPanel
---@field DecorationText_Boss UWBP_DecorationText_C
---@field HorizontalLine_Bottom UWBP_HorizontalLineHUD_C
---@field HorizontalLine_Bottom_1 UWBP_HorizontalLineHUD_C
---@field HorizontalLine_Top UWBP_HorizontalLineHUD_C
---@field HorizontalLine_Top_1 UWBP_HorizontalLineHUD_C
---@field Image_Boss UImage
---@field Image_HealthLine UImage
---@field LivesCounterBox UHorizontalBox
---@field Preview_BossLifeIndicator_1 UWBP_BossLifeIndicator_C
---@field Preview_BossLifeIndicator_2 UWBP_BossLifeIndicator_C
---@field RichText_BossName_1 UHMQRichTextBlock
---@field RootCanvas UCanvasPanel
---@field SmallLoadingText UHMQRichTextBlock
---@field SmallLoadingText2 UHMQRichTextBlock
---@field WBP_BrushImage_Redglitch UWBP_BrushImage_C
---@field WBP_HMQComplexProgressBar UWBP_HMQComplexProgressBar_C
---@field WBP_HorizontalLine_HealthBottom UWBP_HorizontalLineHUD_C
---@field WBP_VerticalLine_HealthLeft UWBP_VerticalLineHUD_C
---@field WBP_VerticalLine_HealthRight UWBP_VerticalLineHUD_C
---@field WBP_VerticalLine_Left UWBP_VerticalLineHUD_C
---@field WBP_VerticalLine_Left_1 UWBP_VerticalLineHUD_C
---@field WBP_VerticalLine_Right UWBP_VerticalLineHUD_C
---@field WBP_VerticalLine_Right_1 UWBP_VerticalLineHUD_C
---@field WBP_VerticalLineLeft UWBP_VerticalLineHUD_C
---@field WBP_VerticalLineLeft_1 UWBP_VerticalLineHUD_C
---@field WBP_VerticalLineRight UWBP_VerticalLineHUD_C
---@field WBP_VerticalLineRight_1 UWBP_VerticalLineHUD_C
---@field OnVisibilityChanged FWBP_BossHealth_COnVisibilityChanged
---@field WidgetStyle UBP_WidgetStyle_C
---@field CachedBoss AActor
---@field CachedLives TArray<UWBP_BossLifeIndicator_C>
---@field AnimState E_BossHealth_AnimationState::Type
---@field bDyingState boolean
---@field bActivationState boolean
---@field bDamagedState boolean
---@field LivesAnimDelay float
---@field EnsureHidden_Delay float
---@field bVisibilityEnsureTimerEnabled boolean
---@field DamagedAnimations TArray<UWidgetAnimation>
---@field IdleAnimations TArray<UWidgetAnimation>
UWBP_BossHealth_C = {}

function UWBP_BossHealth_C:SequenceEvent__ENTRYPOINTWBP_BossHealth_2() end
function UWBP_BossHealth_C:SequenceEvent__ENTRYPOINTWBP_BossHealth_1() end
function UWBP_BossHealth_C:SequenceEvent__ENTRYPOINTWBP_BossHealth_0() end
---@param Animation UWidgetAnimation
---@param IsPlaying boolean
function UWBP_BossHealth_C:IsAnimFromCurrentlyPlayingAnimGroup(Animation, IsPlaying) end
---@param IsPlaying boolean
function UWBP_BossHealth_C:IsOneIdleAnimationPlaying(IsPlaying) end
---@param IsPlaying boolean
function UWBP_BossHealth_C:IsOneDamagedAnimationPlaying(IsPlaying) end
function UWBP_BossHealth_C:ResetAnimationStates() end
---@param CurrentAnimation UWidgetAnimation
function UWBP_BossHealth_C:GetCurrentAnimation(CurrentAnimation) end
---@param IsDying boolean
---@param IsActivating boolean
---@param IsDamaged boolean
---@param OutAnimation UWidgetAnimation
---@param Cancels boolean
function UWBP_BossHealth_C:AnimationStateMachine(IsDying, IsActivating, IsDamaged, OutAnimation, Cancels) end
function UWBP_BossHealth_C:StopMostAnimations() end
function UWBP_BossHealth_C:SequenceEvent_0() end
function UWBP_BossHealth_C:SequenceEvent_1() end
function UWBP_BossHealth_C:SequenceEvent_2() end
---@param Boss AActor
function UWBP_BossHealth_C:ActivateWidget(Boss) end
---@param bBossDied boolean
function UWBP_BossHealth_C:DeactivateWidget(bBossDied) end
---@param HealthComponent UHealthComponent
function UWBP_BossHealth_C:HealthChanged(HealthComponent) end
---@param IsDesignTime boolean
function UWBP_BossHealth_C:PreConstruct(IsDesignTime) end
---@param DamagedActor AActor
---@param DamageEvent FTouristDamageEvent
function UWBP_BossHealth_C:DamageTaken(DamagedActor, DamageEvent) end
function UWBP_BossHealth_C:CompleteDeactivation() end
function UWBP_BossHealth_C:UpdateLivesCounter() end
function UWBP_BossHealth_C:InitializeLivesCounter() end
function UWBP_BossHealth_C:WidgetAnimationEvt_HealthBarAppear1_K2Node_WidgetAnimationEvent_0() end
function UWBP_BossHealth_C:WidgetAnimationEvt_HealthBarDamage_K2Node_WidgetAnimationEvent_1() end
function UWBP_BossHealth_C:WidgetAnimationEvt_HealthBarDamage_1_K2Node_WidgetAnimationEvent_2() end
function UWBP_BossHealth_C:WidgetAnimationEvt_HealthBarDamage_2_K2Node_WidgetAnimationEvent_3() end
function UWBP_BossHealth_C:UpdateAnimation() end
function UWBP_BossHealth_C:WidgetAnimationEvt_HealthBarDeath_K2Node_WidgetAnimationEvent_4() end
function UWBP_BossHealth_C:WidgetAnimationEvt_HealthBarLoop_K2Node_WidgetAnimationEvent_5() end
function UWBP_BossHealth_C:WidgetAnimationEvt_HealthBarLoop_2_K2Node_WidgetAnimationEvent_6() end
function UWBP_BossHealth_C:LivesInitializationAnimation() end
function UWBP_BossHealth_C:UnbindBossHealthEvents() end
function UWBP_BossHealth_C:OnLifeCountChanged() end
function UWBP_BossHealth_C:UpdateColor() end
function UWBP_BossHealth_C:FakeBossVisibility() end
---@param EntryPoint int32
function UWBP_BossHealth_C:ExecuteUbergraph_WBP_BossHealth(EntryPoint) end
---@param visible boolean
function UWBP_BossHealth_C:OnVisibilityChanged__DelegateSignature(visible) end


