---@meta

---@class UWBP_AudioSettings_C : USysSettingsTab
---@field UberGraphFrame FPointerToUberGraphFrame
---@field Intro UWidgetAnimation
---@field AdvancedButton UWBP_SettingsTabBtn_C
---@field AdvancedSettingsScrollBox UScrollBox
---@field AudioOutputSettingsScrollBox UScrollBox
---@field BassValue UWBP_SettingSliderAdvanced_C
---@field CanvasPanel_0 UCanvasPanel
---@field ControllerVolume UWBP_SettingBase_C
---@field ControllerVolumeValue UWBP_SettingSlider_C
---@field DialogueValue UWBP_SettingSliderAdvanced_C
---@field DynamicRangeSettingsScrollBox UScrollBox
---@field EnvironmentValue UWBP_SettingSliderAdvanced_C
---@field HeaderDynamicRange UWBP_HeaderPreview_C
---@field HeaderFocus UWBP_HeaderPreview_C
---@field HeaderRaytracing UWBP_HeaderPreview_C
---@field HeaderSpeakerTuning UWBP_HeaderPreview_C
---@field LanguageButton UWBP_SettingsTabBtn_C
---@field LanguageSettingsScrollBox UScrollBox
---@field MidnightModeValue UWBP_SettingSpinner_C
---@field MonoMixValue UWBP_SettingSpinner_C
---@field OutputSingleValue UWBP_SettingSingleValue_C
---@field PartyChatValue UWBP_SettingSliderAdvanced_C
---@field PlaybackVolumeValue UWBP_SettingSliderAdvanced_C
---@field SettingAudioLanguage UWBP_SettingBase_C
---@field SettingAudioOutput UWBP_SettingBase_C
---@field SettingAudioOutputScroll UWBP_SettingBase_C
---@field SettingAudioOutputScroll_PC UWBP_SettingBase_C
---@field SettingBackgroundOpacity UWBP_SettingBase_C
---@field SettingBass UWBP_SettingBase_C
---@field SettingDialogueFocus UWBP_SettingBase_C
---@field SettingDynamicRangeWIP UWBP_SettingBase_C
---@field SettingEffects UWBP_SettingBase_C
---@field SettingEnvironmentNoise UWBP_SettingBase_C
---@field SettingMasterVolume UWBP_SettingBase_C
---@field SettingMidnightMode UWBP_SettingBase_C
---@field SettingMonoMix UWBP_SettingBase_C
---@field SettingMusic UWBP_SettingBase_C
---@field SettingPartyChatFocus UWBP_SettingBase_C
---@field SettingPartyChatVolume UWBP_SettingBase_C
---@field SettingPlaybackVolume UWBP_SettingBase_C
---@field SettingRaytracedAudio UWBP_SettingBase_C
---@field SettingSpeakerColour UWBP_SettingBase_C
---@field SettingSpeakerName UWBP_SettingBase_C
---@field SettingSubtitleColour UWBP_SettingBase_C
---@field SettingSubtitles UWBP_SettingBase_C
---@field SettingSubtitleSize UWBP_SettingBase_C
---@field SettingSubtitlesMode UWBP_SettingBase_C
---@field SettingTreble UWBP_SettingBase_C
---@field SettingVoices UWBP_SettingBase_C
---@field TrebleValue UWBP_SettingSliderAdvanced_C
---@field ValueAudioLanguage UWBP_SettingSpinner_C
---@field ValueAudioOutput_Scroll UWBP_SettingSpinner_C
---@field ValueAudioOutput_Scroll_PC UWBP_SettingSpinner_C
---@field ValueBackgroundOpacity UWBP_SettingSlider_C
---@field ValueEffects UWBP_SettingSlider_C
---@field ValueMasterVolume UWBP_SettingSlider_C
---@field ValueMusic UWBP_SettingSlider_C
---@field ValueMusic_3 UWBP_SettingSlider_C
---@field ValuePartyChat UWBP_SettingSlider_C
---@field ValueRaytracedAudio UWBP_SettingSpinner_C
---@field ValueSpeakerColour UWBP_SettingSpinner_C
---@field ValueSpeakerName UWBP_SettingSpinner_C
---@field ValueSubtitles UWBP_SettingSpinner_C
---@field ValueSubtitlesColour UWBP_SettingSpinner_C
---@field ValueSubtitlesMode UWBP_SettingSpinner_C
---@field ValueSubtitlesSize UWBP_SettingSpinner_C
---@field ValueVoices UWBP_SettingSlider_C
---@field VolumeButton UWBP_SettingsTabBtn_C
---@field VolumeSettingsScrollBox UScrollBox
---@field WBP_HeaderPreview UWBP_HeaderPreview_C
---@field OnInputAction_SystemMenu FWBP_AudioSettings_COnInputAction_SystemMenu
---@field CachedParentSysSettings UWBP_SystemSettings_3Panel_C
---@field AudioOutputDescriptions TArray<FText>
---@field AudioValueText TArray<FText>
---@field ConditionValueText TArray<FText>
---@field LCOutputText TArray<FText>
---@field DynamicRangeValueText TArray<FText>
---@field ListeningConditionValue int32
---@field LCOutputValue int32
---@field LCPlaybackVolumeValue int32
---@field LCEnvironmentValue int32
---@field LCDynamicRangeValue int32
---@field DynamicRangeHeaderText TArray<FText>
---@field isMidnightMode boolean
---@field LCWarningText FText
---@field AudioOutputText TArray<FText>
---@field cahceAudioOutputSystem int32
---@field cacheAudioOutputSystemString FString
---@field DefaultAudioGeneral TArray<int32>
---@field DefaultAudioAdvanced TArray<int32>
---@field AudioValueEnviromentText TArray<FText>
---@field OutputAutoText FText
---@field isDRLimited boolean
---@field LCDynamicRangeValueOverride int32
---@field Style FString
---@field LastFocusedWidget UWBP_SettingBase_C
---@field FocusKeeper FWBP_AudioSettings_CFocusKeeper
---@field FocusKeeperTab FWBP_AudioSettings_CFocusKeeperTab
---@field LastFocusedTab UWBP_SettingsTabBtn_C
---@field LCOutputValueOverride int32
---@field ['Audio Output Auto Detect Text'] TArray<FText>
---@field AudioOutputAutoDetectIndex int32
---@field AudioOutputTextPC TArray<FText>
---@field ConditionValueTextPC TArray<FText>
---@field AudioOutputDescriptionsPC TArray<FText>
---@field IsPlatformPS5 boolean
---@field LCOutputTextPC TArray<FText>
---@field FocusKeeperHeader FWBP_AudioSettings_CFocusKeeperHeader
---@field TempTextForGraphicsSettings TArray<FText>
UWBP_AudioSettings_C = {}

---@param bAllowsSpeaker boolean
function UWBP_AudioSettings_C:OutputAllowsControllerSpeaker(bAllowsSpeaker) end
function UWBP_AudioSettings_C:SetPCLanguageOptions() end
function UWBP_AudioSettings_C:CheckPlatform() end
---@param LanguageName FString
function UWBP_AudioSettings_C:SaveAudioLanguage(LanguageName) end
---@param DynRangeValue int32
---@param DynamicRangeValue int32
---@param Limited boolean
function UWBP_AudioSettings_C:DynamicRangeTextLimit(DynRangeValue, DynamicRangeValue, Limited) end
---@param index int32
function UWBP_AudioSettings_C:GetAudioOutputIndex(index) end
function UWBP_AudioSettings_C:ApplyDefaultLanguageSettings() end
function UWBP_AudioSettings_C:SaveSubtitlesMode() end
function UWBP_AudioSettings_C:UpdateDynamicRangeHeader() end
---@param LimitDynamicRange boolean
---@param OutputValue int32
---@param UsingHeadphones boolean
function UWBP_AudioSettings_C:DynamicRangeLimit(LimitDynamicRange, OutputValue, UsingHeadphones) end
function UWBP_AudioSettings_C:BuildDefaultSettingsValues() end
---@param DescText int32
---@param ListeningCondition FText
function UWBP_AudioSettings_C:UpdateListeningConditions(DescText, ListeningCondition) end
---@param LCPlaybackVolumeValue int32
---@param LCEnvironmentValue int32
function UWBP_AudioSettings_C:SetListeningConditions(LCPlaybackVolumeValue, LCEnvironmentValue) end
---@param Widget UPanelWidget
function UWBP_AudioSettings_C:UpdateWidgetColors(Widget) end
UWBP_AudioSettings_C['Save Settings'] = function() end
function UWBP_AudioSettings_C:LoadSettings() end
function UWBP_AudioSettings_C:BndEvt__ValueMusic_K2Node_ComponentBoundEvent_5_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:BndEvt__ValueEffects_K2Node_ComponentBoundEvent_6_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:BndEvt__ValueVoices_K2Node_ComponentBoundEvent_7_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:InputAction_SystemMenu() end
---@param NewScreenName FName
function UWBP_AudioSettings_C:ReceiveExitScreen(NewScreenName) end
function UWBP_AudioSettings_C:Construct() end
function UWBP_AudioSettings_C:UpdateColor() end
function UWBP_AudioSettings_C:BndEvt__ValueSubtitles_K2Node_ComponentBoundEvent_1_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:BndEvt__ValueSubtitlesMode_K2Node_ComponentBoundEvent_3_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:BndEvt__ValueSubtitlesSize_K2Node_ComponentBoundEvent_4_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:BndEvt__ValueSubtitlesColour_K2Node_ComponentBoundEvent_9_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:BndEvt__ValueSpeakerColour_K2Node_ComponentBoundEvent_10_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:BndEvt__ValueBackgroundOpacity_K2Node_ComponentBoundEvent_11_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:BndEvt__PlaybackVolumeValue_K2Node_ComponentBoundEvent_2_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:BndEvt__EnvironmentValue_K2Node_ComponentBoundEvent_12_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:BndEvt__DialogueValue_K2Node_ComponentBoundEvent_22_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:BndEvt__PartyChatValue_K2Node_ComponentBoundEvent_23_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:BndEvt__ValueMasterVolume_K2Node_ComponentBoundEvent_14_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:BndEvt__ValuePartyChat_K2Node_ComponentBoundEvent_19_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:BndEvt__WBP_SettingSpinner_K2Node_ComponentBoundEvent_24_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:BndEvt__BassValue_K2Node_ComponentBoundEvent_26_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:BndEvt__TrebleValue_K2Node_ComponentBoundEvent_28_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:BndEvt__MidnightModeValue_K2Node_ComponentBoundEvent_8_OnValueChanged__DelegateSignature() end
UWBP_AudioSettings_C['Set MidnightModeOverride'] = function() end
function UWBP_AudioSettings_C:BndEvt__ControllerVolumeValue_K2Node_ComponentBoundEvent_13_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:BndEvt__ValueSpeakerName_K2Node_ComponentBoundEvent_15_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:RestoreToDefault() end
---@param SubtitlesEnabled boolean
UWBP_AudioSettings_C['Hide Subtitle Options'] = function(SubtitlesEnabled) end
---@param SettingPreviewType PreviewPanelType
function UWBP_AudioSettings_C:BndEvt__SettingPlaybackVolume_K2Node_ComponentBoundEvent_0_FocusReceived__DelegateSignature(SettingPreviewType) end
---@param SettingPreviewType PreviewPanelType
function UWBP_AudioSettings_C:BndEvt__SettingEnvironmentNoise_K2Node_ComponentBoundEvent_16_FocusReceived__DelegateSignature(SettingPreviewType) end
---@param SettingPreviewType PreviewPanelType
function UWBP_AudioSettings_C:BndEvt__SettingAudioOutput_K2Node_ComponentBoundEvent_17_FocusReceived__DelegateSignature(SettingPreviewType) end
---@param AudioOutputSystemIndex int32
function UWBP_AudioSettings_C:AudioOutputSystemNotified(AudioOutputSystemIndex) end
function UWBP_AudioSettings_C:onHeadphonesRemoved() end
---@param SettingPreviewType PreviewPanelType
function UWBP_AudioSettings_C:BndEvt__SettingAudioOutputScroll_K2Node_ComponentBoundEvent_20_FocusReceived__DelegateSignature(SettingPreviewType) end
function UWBP_AudioSettings_C:BndEvt__ValueAudioOutput_Scroll_K2Node_ComponentBoundEvent_18_OnValueChanged__DelegateSignature() end
---@param IsDesignTime boolean
function UWBP_AudioSettings_C:PreConstruct(IsDesignTime) end
function UWBP_AudioSettings_C:Destruct() end
function UWBP_AudioSettings_C:BndEvt__ValueAudioLanguage_K2Node_ComponentBoundEvent_18_OnValueChanged__DelegateSignature() end
---@param SettingWidget UWBP_SettingBase_C
function UWBP_AudioSettings_C:BP_FocusKepper(SettingWidget) end
function UWBP_AudioSettings_C:BndEvt__Button_11_K2Node_ComponentBoundEvent_25_OnButtonClickedEvent__DelegateSignature() end
---@param SettingTab UWBP_SettingsTabBtn_C
function UWBP_AudioSettings_C:BP_FocusKeeperTab(SettingTab) end
---@param SettingPreviewType PreviewPanelType
function UWBP_AudioSettings_C:BndEvt__SettingAudioOutputScroll_PC_K2Node_ComponentBoundEvent_29_FocusReceived__DelegateSignature(SettingPreviewType) end
function UWBP_AudioSettings_C:BndEvt__ValueAudioOutput_Scroll_PC_K2Node_ComponentBoundEvent_30_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:MidnightModeValuePC() end
function UWBP_AudioSettings_C:PlaybackVolumeValuePC() end
function UWBP_AudioSettings_C:EnvironmentValuePC() end
function UWBP_AudioSettings_C:BP_FocusKeeperHeader() end
UWBP_AudioSettings_C['Set Controller Speaker Visibility'] = function() end
function UWBP_AudioSettings_C:BndEvt__ValueRaytracedAudio_K2Node_ComponentBoundEvent_27_OnValueChanged__DelegateSignature() end
function UWBP_AudioSettings_C:StartRefocus() end
function UWBP_AudioSettings_C:EndRefocus() end
function UWBP_AudioSettings_C:ChangeGameLanguage() end
---@param EntryPoint int32
function UWBP_AudioSettings_C:ExecuteUbergraph_WBP_AudioSettings(EntryPoint) end
function UWBP_AudioSettings_C:FocusKeeperHeader__DelegateSignature() end
---@param SettingTab UWBP_SettingsTabBtn_C
function UWBP_AudioSettings_C:FocusKeeperTab__DelegateSignature(SettingTab) end
---@param SettingWidget UWBP_SettingBase_C
function UWBP_AudioSettings_C:FocusKeeper__DelegateSignature(SettingWidget) end
function UWBP_AudioSettings_C:OnInputAction_SystemMenu__DelegateSignature() end


