---@meta

---@class UWBP_DataBankWeaponDetails_C : UTouristWidgetBase
---@field UberGraphFrame FPointerToUberGraphFrame
---@field DetailsSwitcher UWidgetSwitcher
---@field DetailsType UOverlay
---@field Image_InfoHighlight UImage
---@field Image_TraitComplete UImage
---@field Image_TraitComplete_1 UImage
---@field Image_TraitComplete_2 UImage
---@field Image_TraitHighlight UImage
---@field Info UHMQRichTextBlock
---@field PromptInfo UHMQRichTextBlock
---@field Prompttraits UHMQRichTextBlock
---@field RichText_Description UHMQRichTextBlock
---@field ScrollBox_Description UScrollBox
---@field Tier1Border_Overlay UOverlay
---@field Tier1TextUnlock UHMQRichTextBlock
---@field Tier1UnlockOverlay UOverlay
---@field Tier2Border_Overlay UOverlay
---@field Tier2TextUnlock UHMQRichTextBlock
---@field Tier2UnlockOverlay UOverlay
---@field Tier3Border_Overlay UOverlay
---@field Tier3TextUnlock UHMQRichTextBlock
---@field Tier3UnlockImage UImage
---@field Tier3UnlockOverlay UOverlay
---@field Tier4Border_Overlay UOverlay
---@field Tier4TextUnlock UHMQRichTextBlock
---@field Tier4UnlockImage UImage
---@field Tier4UnlockOverlay UOverlay
---@field TraitLevelBackgroundImage UImage
---@field TraitLevelBackgroundImage_1 UImage
---@field TraitLevelBackgroundImage_2 UImage
---@field Traits UHMQRichTextBlock
---@field TraitsTear1 UVerticalBox
---@field TraitsTear2 UVerticalBox
---@field TraitsTear3 UVerticalBox
---@field TraitsTear4 UVerticalBox
---@field VerticalBox_72 UVerticalBox
---@field VerticalBox_Details UVerticalBox
---@field WBP_DataBankWeaponTrait UWBP_DataBankWeaponTrait_C
---@field WBP_DataBankWeaponTrait_1 UWBP_DataBankWeaponTrait_C
---@field WBP_DataBankWeaponTrait_2 UWBP_DataBankWeaponTrait_C
---@field WBP_DataBankWeaponTrait_3 UWBP_DataBankWeaponTrait_C
---@field WBP_DataBankWeaponTrait_4 UWBP_DataBankWeaponTrait_C
---@field WBP_DataBankWeaponTrait_5 UWBP_DataBankWeaponTrait_C
---@field WBP_DataBankWeaponTrait_6 UWBP_DataBankWeaponTrait_C
---@field WBP_DataBankWeaponTrait_7 UWBP_DataBankWeaponTrait_C
---@field WBP_DataBankWeaponTrait_8 UWBP_DataBankWeaponTrait_C
---@field WBP_HorizontalLine UWBP_HorizontalLine_C
---@field WBP_HorizontalLine_1 UWBP_HorizontalLine_C
---@field WBP_HorizontalLine_2 UWBP_HorizontalLine_C
---@field WBP_HorizontalLine_3 UWBP_HorizontalLine_C
---@field WBP_HorizontalLine_4 UWBP_HorizontalLine_C
---@field WBP_HorizontalLine_5 UWBP_HorizontalLine_C
---@field WBP_HorizontalLine_6 UWBP_HorizontalLine_C
---@field WBP_HorizontalLine_7 UWBP_HorizontalLine_C
---@field WBP_HorizontalLine_8 UWBP_HorizontalLine_C
---@field WBP_HorizontalLine_9 UWBP_HorizontalLine_C
---@field WBP_VerticalLine UWBP_VerticalLine_C
---@field WBP_VerticalLine_1 UWBP_VerticalLine_C
---@field WBP_VerticalLine_2 UWBP_VerticalLine_C
---@field WBP_VerticalLine_3 UWBP_VerticalLine_C
---@field WBP_VerticalLine_4 UWBP_VerticalLine_C
---@field WBP_VerticalLine_5 UWBP_VerticalLine_C
---@field WBP_VerticalLine_6 UWBP_VerticalLine_C
---@field WBP_VerticalLine_7 UWBP_VerticalLine_C
---@field WBP_VerticalLine_8 UWBP_VerticalLine_C
---@field WBP_VerticalLine_9 UWBP_VerticalLine_C
---@field WBP_VerticalLine_10 UWBP_VerticalLine_C
---@field WBP_VerticalLine_11 UWBP_VerticalLine_C
---@field WBP_VerticalLine_12 UWBP_VerticalLine_C
---@field WBP_VerticalLine_13 UWBP_VerticalLine_C
---@field WBP_VerticalLine_14 UWBP_VerticalLine_C
---@field WBP_VerticalLine_15 UWBP_VerticalLine_C
---@field WBP_VerticalLine_16 UWBP_VerticalLine_C
---@field WBP_VerticalLine_17 UWBP_VerticalLine_C
---@field WBP_VerticalLine_18 UWBP_VerticalLine_C
---@field WBP_VerticalLine_19 UWBP_VerticalLine_C
---@field WBP_VerticalLine_20 UWBP_VerticalLine_C
---@field WBP_VerticalLine_21 UWBP_VerticalLine_C
---@field WBP_VerticalLine_22 UWBP_VerticalLine_C
---@field WBP_VerticalLine_23 UWBP_VerticalLine_C
---@field WBP_VerticalLine_24 UWBP_VerticalLine_C
---@field WBP_VerticalLine_25 UWBP_VerticalLine_C
---@field WBP_VerticalLine_26 UWBP_VerticalLine_C
---@field WBP_VerticalLine_27 UWBP_VerticalLine_C
---@field PromptKey FKey
---@field IsTraitsShowing boolean
---@field DAProfStats UPrimaryDataAsset
---@field ProficiencyText FText
---@field TraitTier1Index int32
---@field TraitTier2Index int32
---@field TraitTier3Index int32
---@field TraitTier4Index int32
UWBP_DataBankWeaponDetails_C = {}

---@param TraitTier int32
---@param TrautWideetRet UWBP_DataBankWeaponTrait_C
function UWBP_DataBankWeaponDetails_C:FindTraitWidget(TraitTier, TrautWideetRet) end
---@param VBox UVerticalBox
function UWBP_DataBankWeaponDetails_C:SetTraitUnlockIfNotActive(VBox) end
---@param TraitWidget UWidget
function UWBP_DataBankWeaponDetails_C:ShowTrait(TraitWidget) end
---@param VBox UVerticalBox
---@param NotUnlockedOverlay UOverlay
---@param BorderOverlay UOverlay
function UWBP_DataBankWeaponDetails_C:HideGroup(VBox, NotUnlockedOverlay, BorderOverlay) end
---@param VBox UVerticalBox
---@param NotUnlockedOverlay UOverlay
---@param BorderOverlay UOverlay
function UWBP_DataBankWeaponDetails_C:ShowGroup(VBox, NotUnlockedOverlay, BorderOverlay) end
---@param Tier int32
function UWBP_DataBankWeaponDetails_C:ShowGroupByTier(Tier) end
---@param WidgetObject UWidget
function UWBP_DataBankWeaponDetails_C:HideTrait(WidgetObject) end
---@param IsMeleeSelected boolean
function UWBP_DataBankWeaponDetails_C:IsMeleeSelected(IsMeleeSelected) end
---@param Description FText
function UWBP_DataBankWeaponDetails_C:SetDescription(Description) end
function UWBP_DataBankWeaponDetails_C:SwapDetails() end
---@param TraitNames TArray<FText>
---@param TraitTiers TArray<int32>
---@param WeaponTraits TArray<FInventoryWeaponTraitData>
---@param Weapon APlayerWeapon
function UWBP_DataBankWeaponDetails_C:SetTraitInformation(TraitNames, TraitTiers, WeaponTraits, Weapon) end
---@param IsDesignTime boolean
function UWBP_DataBankWeaponDetails_C:PreConstruct(IsDesignTime) end
function UWBP_DataBankWeaponDetails_C:Construct() end
---@param WidgetIndex int32
function UWBP_DataBankWeaponDetails_C:SetDetailsFocus(WidgetIndex) end
function UWBP_DataBankWeaponDetails_C:ControllerSettingsChanged() end
---@param EntryPoint int32
function UWBP_DataBankWeaponDetails_C:ExecuteUbergraph_WBP_DataBankWeaponDetails(EntryPoint) end


