---@meta

---@class UWBP_SystemSettings_3Panel_C : USystemSettingsMenu
---@field UberGraphFrame FPointerToUberGraphFrame
---@field CanvasPanel_65 UCanvasPanel
---@field PageTitle UHMQRichTextBlock
---@field Prompt_Apply_Screen UWBP_SettingsPromptBarItem_C
---@field Prompt_Benchmark UWBP_SettingsHoldPromptBarItem_C
---@field Prompt_GameLanguage UWBP_SettingsPromptBarItem_C
---@field Prompt_Graphics_Preview UWBP_SettingsPromptBarItem_C
---@field Prompt_Navigation UWBP_SettingsPromptBarItem_C
---@field Prompt_Preview UWBP_SettingsPromptBarItem_C
---@field Prompt_Rebind UWBP_SettingsPromptBarItem_C
---@field Prompt_Return UWBP_SettingsPromptBarItem_C
---@field Prompt_ReturnDefault UWBP_SettingsPromptBarItem_C
---@field Prompt_Select UWBP_SettingsPromptBarItem_C
---@field Prompt_Shaders UWBP_SettingsHoldPromptBarItem_C
---@field Prompt_ShowMenuControls UWBP_SettingsPromptBarItem_C
---@field Prompt_Toggle UWBP_SettingsPromptBarItem_C
---@field Prompt_Unbind UWBP_SettingsPromptBarItem_C
---@field SizeBox_PC USizeBox
---@field Spacer_forGraphicsTab USpacer
---@field Tab_Audio UWBP_SettingsTabBtn_C
---@field Tab_Controller UWBP_SettingsTabBtn_C
---@field Tab_Gameplay UWBP_SettingsTabBtn_C
---@field Tab_Graphics UWBP_SettingsTabBtn_C
---@field Tab_Video UWBP_SettingsTabBtn_C
---@field WBP_AltFireIndicatorPreview UWBP_AltFireIndicatorPreview_C
---@field WBP_AudioSettings UWBP_AudioSettings_C
---@field WBP_Background UWBP_Background_C
---@field WBP_ColourblindPreview UWBP_ColourblindPreview_C
---@field WBP_ControllerOverride2Panel UWBP_ControllerOverride2Panel_C
---@field WBP_ControllerOverridePreview UWBP_ControllerOverridePreview_C
---@field WBP_ControllerSettings UWBP_ControllerSettings_C
---@field WBP_ControllerSetupPreview UWBP_ControllerSetupPreview_C
---@field WBP_CrosshairPreview UWBP_CrosshairPreview_C
---@field WBP_DefaultPreview UWBP_DefaultPreview_C
---@field WBP_DynamicRangePreview UWBP_DynamicRangePreview_C
---@field WBP_GameLanguagePreview UWBP_GameLanguagePreview_C
---@field WBP_GameLanguageSettings UWBP_GameLanguageSettings_C
---@field WBP_GameplaySettings UWBP_GameplaySettings_C
---@field WBP_GraphicsPreview UWBP_GraphicsPreview_C
---@field WBP_GraphicsSettings UWBP_GraphicsSettings_C
---@field WBP_GraphicsTabOverlay UWBP_GraphicsTabOverlay_C
---@field WBP_HorizontalLineOpaqueEdges UWBP_HorizontalLineOpaqueEdges_C
---@field WBP_HUDPreview UWBP_HUDPreview_C
---@field WBP_KeybindingPreview UWBP_KeybindingPreview_C
---@field WBP_KeyboardRemappingSettings UWBP_KeyboardRemappingSettings_C
---@field WBP_SettingsMenuTabs UWBP_SettingsMenuTabs_C
---@field WBP_SubtitlePreview UWBP_SubtitlePreview_C
---@field WBP_SystemMenuOverlay UWBP_SystemMenuOverlay_C
---@field WBP_VideoSettings UWBP_VideoSettings_C
---@field Intro UWidgetAnimation
---@field ChangesWarning boolean
---@field OnInputAction_SystemMenu FWBP_SystemSettings_3Panel_COnInputAction_SystemMenu
---@field Style FString
---@field WidgetStyle_Default UBP_WidgetStyle_C
---@field PageTitleText FText
---@field SelectedTabIndex int32
---@field SelectText FText
---@field TabChangedSound UAkAudioEvent
---@field Audio_AllowTabSounds boolean
---@field SettingsExitBackToGameSound UAkAudioEvent
---@field LastFocusedWidget UWBP_SettingBase_C
---@field LastFocusedTab UWBP_SettingsTabBtn_C
---@field InvalidFocusedWidget UWBP_SettingBase_C
---@field bIsRendering boolean
---@field HorizontalTabSwitcher_SizeInGraphicsTab float
---@field LastFocusedRebinding UWBP_SettingValueBase_C
---@field GoToAudioTab boolean
---@field PerformanceCounterVisible boolean
---@field GraphicsTabOpen boolean
---@field ResetPauseTickStatus boolean
---@field ButtonDown boolean
---@field ContinueDelay float
---@field Audio_HasCompleted boolean
---@field Audio_IsHolding boolean
---@field BenchmarkEnabled boolean
---@field ShaderButtonDown boolean
---@field ShaderContinueDelay float
UWBP_SystemSettings_3Panel_C = {}

---@param IsWindows boolean
function UWBP_SystemSettings_3Panel_C:SetLayoutSize(IsWindows) end
---@param visible boolean
function UWBP_SystemSettings_3Panel_C:TogglePerformanceCounterVisibility(visible) end
---@param MyGeometry FGeometry
---@param MouseEvent FPointerEvent
---@return FEventReply
function UWBP_SystemSettings_3Panel_C:OnMouseMove(MyGeometry, MouseEvent) end
---@param MyGeometry FGeometry
---@param InFocusEvent FFocusEvent
---@return FEventReply
function UWBP_SystemSettings_3Panel_C:OnFocusReceived(MyGeometry, InFocusEvent) end
function UWBP_SystemSettings_3Panel_C:RefocusSetting() end
---@param FocusStatus boolean
function UWBP_SystemSettings_3Panel_C:ChangeTabButtonFocus(FocusStatus) end
function UWBP_SystemSettings_3Panel_C:AdjustLayoutDependingOnGraphicsTab() end
---@param MyGeometry FGeometry
---@param MouseEvent FPointerEvent
---@return FEventReply
function UWBP_SystemSettings_3Panel_C:OnMouseButtonDown_0(MyGeometry, MouseEvent) end
function UWBP_SystemSettings_3Panel_C:ExitMenu() end
---@param index int32
function UWBP_SystemSettings_3Panel_C:SetSelectedTab(index) end
---@param HUDBase UWBP_HUDBase_C
function UWBP_SystemSettings_3Panel_C:GetHudPreview(HUDBase) end
---@param wbp UPanelWidget
function UWBP_SystemSettings_3Panel_C:UpdateColors(wbp) end
function UWBP_SystemSettings_3Panel_C:Construct() end
function UWBP_SystemSettings_3Panel_C:UpdateColor() end
---@param OldScreenName FName
---@param bFirst boolean
function UWBP_SystemSettings_3Panel_C:ReceiveEnterScreen(OldScreenName, bFirst) end
---@param NewScreenName FName
function UWBP_SystemSettings_3Panel_C:ReceiveExitScreen(NewScreenName) end
---@param IsDesignTime boolean
function UWBP_SystemSettings_3Panel_C:PreConstruct(IsDesignTime) end
---@param bIsShoulderLeft boolean
---@param OldTab int32
function UWBP_SystemSettings_3Panel_C:BPOnShoulderPressed(bIsShoulderLeft, OldTab) end
function UWBP_SystemSettings_3Panel_C:OnSpecialRight() end
---@param bIsNavigatingLeft boolean
function UWBP_SystemSettings_3Panel_C:LeftPanelFocusChanged(bIsNavigatingLeft) end
---@param FocusedSystemSetting USystemSettingBase
function UWBP_SystemSettings_3Panel_C:OnSettingFocused(FocusedSystemSetting) end
function UWBP_SystemSettings_3Panel_C:OnInitialized() end
---@param Focused_Setting UWBP_SettingBase_C
function UWBP_SystemSettings_3Panel_C:MouseFocusOnWidget(Focused_Setting) end
---@param SettingTab UWBP_SettingsTabBtn_C
function UWBP_SystemSettings_3Panel_C:BP_FocusKeeperTab(SettingTab) end
---@param SettingWidget UWBP_SettingBase_C
function UWBP_SystemSettings_3Panel_C:BP_FocusKeeper(SettingWidget) end
---@param RebindSetting UWBP_SettingValueBase_C
function UWBP_SystemSettings_3Panel_C:BP_FocusKeeperRebinding(RebindSetting) end
function UWBP_SystemSettings_3Panel_C:CheckForTutorialShortcut() end
function UWBP_SystemSettings_3Panel_C:BP_FocusKeeperHeader() end
function UWBP_SystemSettings_3Panel_C:PreviewClicked() end
function UWBP_SystemSettings_3Panel_C:SelectClicked() end
function UWBP_SystemSettings_3Panel_C:UnbindClicked() end
function UWBP_SystemSettings_3Panel_C:ReturnClicked() end
function UWBP_SystemSettings_3Panel_C:ReturnDefaultClicked() end
---@param FocusedTab USystemSettingBase
function UWBP_SystemSettings_3Panel_C:OnTabFocused(FocusedTab) end
function UWBP_SystemSettings_3Panel_C:BP_ApplyingVideoSettings() end
function UWBP_SystemSettings_3Panel_C:ApplyScreenSettings() end
function UWBP_SystemSettings_3Panel_C:ShowMenuPreset() end
function UWBP_SystemSettings_3Panel_C:ControllerSettingsChanged() end
function UWBP_SystemSettings_3Panel_C:GameLanguage() end
function UWBP_SystemSettings_3Panel_C:BndEvt__Prompt_Benchmark_K2Node_ComponentBoundEvent_0_PromptPressed__DelegateSignature() end
function UWBP_SystemSettings_3Panel_C:BndEvt__Prompt_Benchmark_K2Node_ComponentBoundEvent_1_PromptRelease__DelegateSignature() end
---@param MyGeometry FGeometry
---@param InDeltaTime float
function UWBP_SystemSettings_3Panel_C:Tick(MyGeometry, InDeltaTime) end
function UWBP_SystemSettings_3Panel_C:BP_BenchmarkPressed() end
function UWBP_SystemSettings_3Panel_C:BP_BenchmarkReleased() end
function UWBP_SystemSettings_3Panel_C:Audio_HoldStarted() end
function UWBP_SystemSettings_3Panel_C:Audio_HoldStopped() end
function UWBP_SystemSettings_3Panel_C:Audio_HoldComplete() end
function UWBP_SystemSettings_3Panel_C:BndEvt__Prompt_Shaders_K2Node_ComponentBoundEvent_2_PromptPressed__DelegateSignature() end
function UWBP_SystemSettings_3Panel_C:BndEvt__Prompt_Shaders_K2Node_ComponentBoundEvent_3_PromptRelease__DelegateSignature() end
function UWBP_SystemSettings_3Panel_C:BP_RecompileShadersPressed() end
function UWBP_SystemSettings_3Panel_C:BP_RecompileShadersReleased() end
---@param EntryPoint int32
function UWBP_SystemSettings_3Panel_C:ExecuteUbergraph_WBP_SystemSettings_3Panel(EntryPoint) end
function UWBP_SystemSettings_3Panel_C:OnInputAction_SystemMenu__DelegateSignature() end


