---@meta

---@class UWBP_HUDBase_C : UGameHUDWidget
---@field UberGraphFrame FPointerToUberGraphFrame
---@field Animation_ContentHide UWidgetAnimation
---@field Starting_Animation_7_CircleGlitch UWidgetAnimation
---@field Starting_Animation_6_RainbowGlitch UWidgetAnimation
---@field Starting_Animation_5_TextRunning UWidgetAnimation
---@field Starting_Animation_4_Blue_Laggy UWidgetAnimation
---@field Starting_Animation_3_UpsideDown UWidgetAnimation
---@field Starting_Animation_2_Red UWidgetAnimation
---@field Starting_Animation UWidgetAnimation
---@field CanvasPanel_Map UCanvasPanel
---@field HorizontalBox_0 UHorizontalBox
---@field Next UWBP_LabelGenericPrompt_C
---@field Overlay_FullScreen UOverlay
---@field Prev UWBP_LabelGenericPrompt_C
---@field SizeBoxHUDEffects USizeBox
---@field Spacer_AudioLogVisualizer USpacer
---@field Spacer_SessionTime USpacer
---@field SpectatingName UHMQRichTextBlock
---@field WBP_AdrenalinePanel_1 UWBP_AdrenalinePanel_C
---@field WBP_AltFireStatus UWBP_AltFireStatus_C
---@field WBP_AnimatedText UWBP_AnimatedText_C
---@field WBP_AnimatedText_2 UWBP_AnimatedText_C
---@field WBP_AudioLogVisualizer_HUD UWBP_AudioLogVisualizer_HUD_C
---@field WBP_BrushImage_BootCircle UWBP_BrushImage_C
---@field WBP_BrushImage_GlitchFast UWBP_BrushImage_C
---@field WBP_BrushImage_GlitchRainbow UWBP_BrushImage_C
---@field WBP_ChallengeHUDScore UWBP_ChallengeHUDScore_C
---@field WBP_Comms UWBP_Comms_C
---@field WBP_CurseList UWBP_CurseList_C
---@field WBP_DashRecharge UWBP_DashRecharge_C
---@field WBP_EnemyHealthBarManager UWBP_EnemyHealthBarManager_C
---@field WBP_HealthPanel UWBP_HealthPanel_C
---@field WBP_HUDAdrenalineBuffPanel UWBP_HUDAdrenalineBuffPanel_C
---@field WBP_HUDBuffPanel UWBP_HUDBuffPanel_C
---@field WBP_HUDProficiencyPanel UWBP_HUDProficiencyPanel_C
---@field WBP_HUDToggleControl UWBP_HUDToggleControl_C
---@field WBP_HUDTraitUnlockStatus UWBP_HUDTraitUnlockStatus_C
---@field WBP_ImmobilizedState UWBP_ImmobilizedState_C
---@field WBP_InfoPanelCollectibles UWBP_CollectibleInfoPanel_C
---@field WBP_InteractableSelectorControlGuide UWBP_InteractableSelectorControlGuide_C
---@field WBP_LargeCommsFrame UWBP_LargeCommsFrame_C
---@field WBP_MapCurrentRoom_54 UWBP_MapCurrentRoom_C
---@field WBP_MeleeRecharge UWBP_MeleeRecharge_C
---@field WBP_MultiConsumableDisplay UWBP_MultiConsumableDisplay_C
---@field WBP_MusicInfo UWBP_MusicInfo_C
---@field WBP_NotificationLog UWBP_NotificationLog_C
---@field WBP_ObjectiveList UWBP_ObjectiveList_C
---@field WBP_RemotePlayerInfo UWBP_RemotePlayerInfo_C
---@field WBP_ReviewMatchPrompt UWBP_ReviewMatchPrompt_C
---@field WBP_ReviveStatus UWBP_ReviveStatus_C
---@field WBP_SessionTime UWBP_SessionTime_C
---@field WBP_SocialCommHUD UWBP_SocialCommHUD_C
---@field WBP_SystemInfo_95 UWBP_SystemInfo_C
---@field WBP_TetheringStatus UWBP_TetheringStatus_C
---@field WBP_TTScoreSummary UWBP_TTScoreSummary_C
---@field WidgetSwitcher_0 UWidgetSwitcher
---@field MainCrosshair UCrosshairWidget
---@field AltFireCrosshair UCrosshairWidget
---@field AltFireModeActive boolean
---@field AltFireCrosshairs TMap<EGunTraitType::Type, TSubclassOf<UCrosshairWidget>>
---@field FocusAimActive boolean
---@field RunningBootAnimation UWidgetAnimation
---@field WidgetsToHandleDuringBossFights TArray<UWidget>
---@field HUDClass TSubclassOf<AHUD>
---@field IsPreviewHUD boolean
UWBP_HUDBase_C = {}

function UWBP_HUDBase_C:SequenceEvent__ENTRYPOINTWBP_HUDBase_6() end
function UWBP_HUDBase_C:SequenceEvent__ENTRYPOINTWBP_HUDBase_5() end
function UWBP_HUDBase_C:SequenceEvent__ENTRYPOINTWBP_HUDBase_4() end
function UWBP_HUDBase_C:SequenceEvent__ENTRYPOINTWBP_HUDBase_3() end
function UWBP_HUDBase_C:SequenceEvent__ENTRYPOINTWBP_HUDBase_2() end
function UWBP_HUDBase_C:SequenceEvent__ENTRYPOINTWBP_HUDBase_1() end
function UWBP_HUDBase_C:SequenceEvent__ENTRYPOINTWBP_HUDBase_0() end
function UWBP_HUDBase_C:UpdateHUDEffects() end
function UWBP_HUDBase_C:UpdateHUDIndicators() end
function UWBP_HUDBase_C:SetHUDSafeZone() end
---@return UVerticalBox
function UWBP_HUDBase_C:GetCurseListBox() end
function UWBP_HUDBase_C:HideWidgetsBySettings() end
---@param Widget UPanelWidget
function UWBP_HUDBase_C:CrosshairRecolour(Widget) end
---@param CrosshairRef UCrosshairWidget
---@param CrosshairWidgetClass TSubclassOf<UCrosshairWidget>
---@param CrosshairOffset FVector2D
function UWBP_HUDBase_C:CreateAndAssignCrosshair(CrosshairRef, CrosshairWidgetClass, CrosshairOffset) end
function UWBP_HUDBase_C:UpdateUIColors() end
function UWBP_HUDBase_C:SetupCrosshair() end
function UWBP_HUDBase_C:BootAnimationAudio() end
---@param Notification UNotificationWidget
function UWBP_HUDBase_C:ShowNotification(Notification) end
---@param NewWeapon APlayerGun
---@param OldWeapon APlayerGun
function UWBP_HUDBase_C:OnMainWeaponChanged(NewWeapon, OldWeapon) end
function UWBP_HUDBase_C:OnGameplayStarted() end
function UWBP_HUDBase_C:GameplayIntroVideoStarted() end
---@param bActive boolean
function UWBP_HUDBase_C:AltFireActiveChanged(bActive) end
---@param visible boolean
---@param InteractableCount int32
function UWBP_HUDBase_C:SetInteractableSelectorControlGuideWidgetVisibility(visible, InteractableCount) end
---@param visible boolean
function UWBP_HUDBase_C:BndEvt__WBP_HUDToggleControl_K2Node_ComponentBoundEvent_0_OnVisibilityToggleChanged__DelegateSignature(visible) end
---@param bVisible boolean
function UWBP_HUDBase_C:SetContentVisibility(bVisible) end
---@param bIsFocusAiming boolean
function UWBP_HUDBase_C:FocusAimStatusChanged(bIsFocusAiming) end
---@param DeltaSeconds float
function UWBP_HUDBase_C:ReceiveDelayTick(DeltaSeconds) end
function UWBP_HUDBase_C:ToggleDebugInfo() end
function UWBP_HUDBase_C:BootAnimationFinished() end
function UWBP_HUDBase_C:OnBossFightEnter() end
function UWBP_HUDBase_C:OnBossFightExit() end
---@param visible boolean
function UWBP_HUDBase_C:BndEvt__BossHealth_K2Node_ComponentBoundEvent_1_OnVisibilityChanged__DelegateSignature(visible) end
UWBP_HUDBase_C['Update Color'] = function() end
---@param Hide_Widget boolean
function UWBP_HUDBase_C:HideMinimap(Hide_Widget) end
---@param Hide_Widget boolean
function UWBP_HUDBase_C:HideConsumable(Hide_Widget) end
---@param Hide_Widget boolean
function UWBP_HUDBase_C:HideHealthBar(Hide_Widget) end
---@param Hide_Widget boolean
function UWBP_HUDBase_C:HideProficiency(Hide_Widget) end
---@param Hide_Widget boolean
function UWBP_HUDBase_C:HideAltFire(Hide_Widget) end
---@param TagChange FGameplayTag
---@param NewCount int32
function UWBP_HUDBase_C:OnGameplayTagChanged_Event_0(TagChange, NewCount) end
---@param Hide_Widget boolean
function UWBP_HUDBase_C:HideCollectables(Hide_Widget) end
---@param Hide_Widget boolean
function UWBP_HUDBase_C:HideAdrenalineBar(Hide_Widget) end
function UWBP_HUDBase_C:ToggleDebugMusicInfo() end
function UWBP_HUDBase_C:Reconstruct() end
function UWBP_HUDBase_C:Construct() end
---@param Dynamic boolean
function UWBP_HUDBase_C:SetDynamicHUD(Dynamic) end
---@param HideWidget boolean
function UWBP_HUDBase_C:HideSessionTime(HideWidget) end
function UWBP_HUDBase_C:SetSafeZone() end
function UWBP_HUDBase_C:ViewportResized() end
function UWBP_HUDBase_C:UpdateIndicators() end
---@param HideWidget boolean
function UWBP_HUDBase_C:HideBossHealthBar(HideWidget) end
---@param HideWidget boolean
function UWBP_HUDBase_C:HideEnemyHealthBar(HideWidget) end
---@param IsDesignTime boolean
function UWBP_HUDBase_C:PreConstruct(IsDesignTime) end
---@param Hide_Widget boolean
function UWBP_HUDBase_C:HideWeaponTrait(Hide_Widget) end
---@param HideWidget boolean
function UWBP_HUDBase_C:HideMultiplayerName(HideWidget) end
---@param EntryPoint int32
function UWBP_HUDBase_C:ExecuteUbergraph_WBP_HUDBase(EntryPoint) end


